### ISSUE TITLE
Correctly document ABI issues between v4.x and v5.0

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#10099]
Per #10098 and ed9a670074eaf64a34f7fdfdcba843f4eaf0219e, we will need to update several sections about ABI in the docs.  For example, several sections in docs/building-apps/removed-mpi-constructs.rst will need to be updated.

It should also probably be mentioned prominently somewhere what the ABI differences are (e.g., if the C MPI bindings ABI was maintained, but the Fortran MPI bindings ABI was not).

**Comment by edgargabriel** [comment]
This is a list of functions on the MPI document that have been deprecated meanwhile but are not mentioned in our docs:

Starting from MPI-2.0 (See chapter 16.1 in MPI-4)
------------------------------------------------------
`MPI_Keyval_create` -> `MPI_Comm_reate_keyval`
(need to check `MPI_Copy_function` prototype and `MPI_Delete_function prototype`)
`MPI_Kevval_free` -> `MPI_Comm_free_keyval`
`MPI_Attr_put` -> `MPI_Comm_set_attr`
`MPI_Attr_get` -> `MPI_Comm_get_attr`
`MPI_Attr_delete` -> `MPI_Comm_delete_attr`

Deprecated since MPI-2.2 (see section 16.2 in MPI 4.0)
------------------------------------------------------------
`MPI_Info_get` -> `MPI_Info_get_string`
`MPI_Info_get_valuelen` -> 'MPI_Info_get_string`

`MPI_Sizeof()`  -> `c_sizeoff()` or `storage_size() ` (Note: Fortran only)
All C++ bindings

**Comment by edgargabriel** [comment]
According to my (limited) tests, I can confirm that a code compiled with ompi 4.1.4 is correctly running if I change the MPI installation to ompi 5.0 without having to recompile the application.

Tested with a C code and some Fortran testcodes as well.

**Comment by jsquyres** [comment]
Has now been merged on both main and v5.0.x.  Closing!
