### ISSUE TITLE
mpirun ignores port setting for the local machine

### ISSUE THREAD

**Issue by lockywolf** [open-mpi/ompi#10151]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.0 and 4.0.5.0.88d8972a4085

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

4.0.5.0.88d8972a4085 was from OpenSUSE Leap 15.3, 4.1.0 was self-built on Slackware 15.0.

### Please describe the system on which you are running

* Operating system/version: OpenSUSE Leap 15.3, Slackware 15.0
* Computer hardware: x86_64
* Network type: loopback

-----------------------------

## Details of the problem

This is my hostfile:
```
laptop port=10002
```

This is how I run mpirun:

```
>mpirun -n 1    --default-hostfile ./hostfile --hostfile ./hostfile --mca btl tcp --mca oob tcp ls
hostfile
```

The result is showing the hostfile, however, the actual result should be a timeout, because there is no sshd running on port 10002.

**Comment by ggouaillardet** [comment]
are you running on `laptop`?
if so, `mpirun` does not (use SSH to) spawn an `orted` daemon and you should not expect a timeout.

Not you need to add `self` to the list of `btl` if you plan to run a MPI application.

**Comment by lockywolf** [comment]
`laptop` is the name of the machine. It is not a laptop.

> if so, mpirun does not (use SSH to) spawn an orted daemon and you should not expect a timeout.

Why and where is this documented?

> Not you need to add self to the list of btl if you plan to run a MPI application.

The absence of `tcp` in the command-line is intentional. I need it to connect by ssh to the tcp port 10002 (as written in the hostfile), and launch `orted` on whatever machine it connects to.

**Comment by jsquyres** [comment]
@lockywolf What is it that you are trying to do?

I do not think we have much documentation on the exact inner-workings of how Open MPI launches across localhost and remote hosts.  The short version is that on localhost, we just fork/exec -- there's no need to ssh to localhost just to launch a process locally.

**Comment by lockywolf** [comment]
The local port 10002 is forwarded to the port 22 on  different machine, as are ports 10000-11000, to exactly the same port numbers on that different machine.

Mca on that different machine has
oob_tcp_dynamic_ports=10000-11000

Mca on local machine has 
oob_tcp_dynamic_ports=9000-9999

I need to run an mpi application on these two machines via forwarded ports.

**Comment by ggouaillardet** [comment]
My question was whether you invoke `mpirun` on the machine called `laptop`.
It makes zero difference if this machine is indeed a laptop or something else.
If you use `pml/ob1`, you always have to include `btl/self` otherwise your app will fail in `MPI_Init()`

you might be able to trick `mpirun` by using different hostnames (such as `laptop1`, `laptop2` and so on) and tweak your `~/.ssh/config` (for example
```
Host laptop1
    Hostname 127.0.0.1
    Port 10002
```

but I am afraid you will find other issues after that with `oob/tcp` and then with `btl/tcp` if you even get there.

At this stage, I suggest you consider an other approach such as running a VPN between your machines so Open MPI use a "standard" IP network with full connectivity.

**Comment by jsquyres** [comment]
@lockywolf I think the root cause here is that you are using the run time system of Open MPI in a configuration that we simply did not design for (i.e., using localhost but not really as localhost).

There are many, many places in Open MPI (not just the run time system) where there is a fundamental difference between how things happen to peers on localhost vs. how things happen to peers not on localhost.  The rationale behind that is that Open MPI aims to provide high performance, not just functionality.  E.g., using fork/exec to launch (and therefore having direct access to local resources) is definitely faster / more efficient than using ssh.  Hence, when possible, the Open MPI run time system prefers fork/exec.

I think that @ggouaillardet is correct: if using a trick like `~/.ssh/config` gets past this one issue, you may still run into other issues because of this fundamental localhost-vs-not-localhost kind of posturing throughout the Open MPI code base.  One way or another, it would be best to treat remote peers like remote peers.
