### ISSUE TITLE
Question: VSCode Reference Finding not working

### ISSUE THREAD

**Issue by a-szegel** [open-mpi/ompi#10154]
Has anyone gotten VSCode reference finding (i.e.. go to definition functionality) working with this project?  I have googled how to get VSCode to work with large C projects to no avail.  I was wondering if anyone has had this issue and figured out how to solve it.

Thanks!!!

**Comment by bosilca** [comment]
I'm using VSCode among other editors while developing in OMPI. Most of them can handle references in the same part of the code (info, groups, communicators, datatype), but they fail to work nice with our internal API, because the interactions of the core with the MCA components (such as send/recv, one-sided, ...) go through a structure with function pointers (dynamically selected at runtime), and none of them could figure it out automatically. I did not look deeper than that, but if you find a way I would be interested to hear about.

**Comment by jsquyres** [comment]
@a-szegel Did that answer your question?

**Comment by a-szegel** [comment]
Yes, my problem was that I forgot to install the plugins on my remote machine.  Thanks!
