### ISSUE TITLE
prterun -help fails with the error "ompi/share/prte/help-cli.txt: No such file or directory"

### ISSUE THREAD

**Issue by artemry-nv** [open-mpi/ompi#10168]
Open MPI v5.0.x

```
$ prterun -help
Test output

--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    unrecognized-option
But I couldn't open the help file:
    /build-result/hpcx-v2.11-gcc-MLNX_OFED_LINUX-5-redhat7-cuda11-gdrcopy2-nccl2.11-x86_64/ompi/share/prte/help-cli.txt: No such file or directory.  Sorry!
 ```

 OS: RHEL 7.x

**Comment by awlauria** [comment]
Thanks for the report @artemry-nv . This is actually a dup of: https://github.com/open-mpi/ompi/issues/10097

We'll have this fixed in rc4. The submodule pointer that has these fixes is already in for v5.0.x here: https://github.com/open-mpi/ompi/pull/10161

on main, the pointer update to bring these fixes in is here: https://github.com/open-mpi/ompi/pull/10165

Closing this since #10097 is tracking.
