### ISSUE TITLE
Openmpi-4.1.4 installation issue

### ISSUE THREAD

**Issue by diffracteD** [open-mpi/ompi#10490]
Hi,
I downloaded Openmpi-4.1.4 and tried to install on my server with instructions mentioned in INSTALL file. But it failed. I'm not sure what this error message means.
Steps taken to install:
```
$ sudo ../configure --with-cuda
$ sudo autoreconf -f -i ../configure.ac
$ sudo make all install
```

Error after `make install` step:
```

....
....
Making all in mca/compress
make[2]: Entering directory '/usr/local/openmpi-4.1.4/build/opal/mca/compress'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/local/openmpi-4.1.4/build/opal/mca/compress'
Making all in mca/crs
make[2]: Entering directory '/usr/local/openmpi-4.1.4/build/opal/mca/crs'
  GENERATE opal_crs.7
Option package-version requires an argument
Usage: ../../../../config/make_manpage.pl --package-name=<package name> --package-version=<package version> --ompi-date=<ompi date> --opal-date=<opal date> --orte-date=<orte date> --input=<input file> --output=<output file> [--nocxx] [ --nofortran] [--nof08]
make[2]: *** [Makefile:2245: opal_crs.7] Error 1
make[2]: Leaving directory '/usr/local/openmpi-4.1.4/build/opal/mca/crs'
make[1]: *** [Makefile:2430: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/openmpi-4.1.4/build/opal'
make: *** [Makefile:1912: all-recursive] Error 1

```
I'm not sure why it's failing. 
Please help me out here.

Thanks.

**Comment by ggouaillardet** [comment]
Assuming you created a `build` (like) directory in the source tree and ran from there, you should only need to

```
$ ../configure --with-cuda
$ make all
$ sudo make install
```

**Comment by diffracteD** [comment]
I tried these but didn’t help.
Finally I read somewhere that I need to run autoreconf before running install. 
this worked perfectly fine.
Thanks

**Comment by diffracteD** [comment]
This didn’t work.
Although, I found out somewhere, running `./autogen.pl — force` before `make all install `works.
And it worked in my case too.
Thanks.

**Comment by jsquyres** [comment]
Per @ggouaillardet's comment: he's right -- you should not run `autoreconf`.  That will almost certainly give you incorrect results.  I could not find anywhere in the Open MPI v4.1.x `INSTALL` file where it says to run `autoreconf` -- can you point to where you found that documentation?

To be clear: You should be able to take a freshly-expanded tarball (not one where you have previously run `autoreconf` or `autogen.pl`) and be able to run `configure` and `make all` and `make install`.

You *can* run `autogen.pl --force` -- there's usually not any harm in doing that.  But for end users, it should be unnecessary.

Since you have this working, I'll close the issue.  Feel free to open a new issue if you have new questions.

**Comment by lxsjgzs** [comment]
The command `$autogen.pl --force` was run before `$sudo ./configure CC=gcc-12 CXX=g++-12` and `make all`, and it seemed working for me as well.
