### ISSUE TITLE
mpirun+dvm failing to find the dvm

### ISSUE THREAD

**Issue by naughtont3** [open-mpi/ompi#11020]
mpirun (prterun) failing to find dvm when using `mpirun --dvm ...` option

### What version of Open MPI are you using? 
 - v5.0.x branch

 - 0ada41c Merge pull request #11002 from hppritcha/fix_for_issue_10986_v50x
 - branch: v5.0.x
 - +1dbf8e7b5d1f1eafd0ad824bbb76ec502fd30ee9 3rd-party/openpmix (v1.1.3-3651-g1dbf8e7)
 - +7a17d22d5c94dde6e59e008443ed8ffc17af9396 3rd-party/prrte (psrvr-v2.0.0rc1-4499-g7a17d22)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone / source build

```sh
../configure \
       --disable-slurm \
       --enable-debug \
       --with-devel-headers \
    --enable-mpirun-prefix-by-default \
    --prefix=${OMPI_INSTALL_DIR}
```

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware: x86_64
* Network type: 

-----------------------------

## Details of the problem

When trying to use a pre-existing DVM instance, the tool fails to locate/connect to the DVM. However, a standard `prun` works fine.  This case worked in a test last week so maybe just a missing commit from prte/pmix upstreams.

```shell
node0: (v5.0.x)$ prte --report-uri dvm.uri &
[2] 20980
node0: (v5.0.x)$ DVM ready

node0: (v5.0.x)$ prun --dvm-uri file:dvm.uri --np 1 hostname
[node0:20998] [prun.node0.20998,0] pmix: spawn called
[node0:20998] [prun.node0.20998,0] pmix: spawn_nb called
node0
node0: (v5.0.x)$ mpirun --dvm file:dvm.uri --np 1 hostname
--------------------------------------------------------------------------
PMIx has found multiple possible servers to which it could
connect. Further guidance is required to ensure the connection
is made to a desirable server. Guidance can be in the form
of the namespace or PID of a specific server, a directive to
connect to a system server, a specific URI to use, or the name
of a rendezvous file.

Some connection handles have been read from files named pmix.*
in subdirectories of $TMPDIR; delete them if they are stale.
--------------------------------------------------------------------------
prterun failed to initialize, likely due to no DVM being available
node0: (v5.0.x)$ mpirun --np 1 hostname
[node0:21036] [prterun-node0-21036@0,0] pmix: spawn_nb called
node0
node0: (v5.0.x)$ mpirun --dvm  --np 1 hostname
--------------------------------------------------------------------------
PMIx has found multiple possible servers to which it could
connect. Further guidance is required to ensure the connection
is made to a desirable server. Guidance can be in the form
of the namespace or PID of a specific server, a directive to
connect to a system server, a specific URI to use, or the name
of a rendezvous file.

Some connection handles have been read from files named pmix.*
in subdirectories of $TMPDIR; delete them if they are stale.
--------------------------------------------------------------------------
prterun failed to initialize, likely due to no DVM being available

node0: (v5.0.x)$ prun --dvm-uri file:dvm.uri --np 1 hostname
[node0:21058] [prun.node0.21058,0] pmix: spawn called
[node0:21058] [prun.node0.21058,0] pmix: spawn_nb called
node0

node0: (v5.0.x)$ prun  --np 1 hostname
--------------------------------------------------------------------------
PMIx has found multiple possible servers to which it could
connect. Further guidance is required to ensure the connection
is made to a desirable server. Guidance can be in the form
of the namespace or PID of a specific server, a directive to
connect to a system server, a specific URI to use, or the name
of a rendezvous file.

Some connection handles have been read from files named pmix.*
in subdirectories of $TMPDIR; delete them if they are stale.
--------------------------------------------------------------------------
prun failed to initialize, likely due to no DVM being available
node0: (v5.0.x)$
```

Looks kind of like case where `prun` could not find the DVM (e.g., multiple dvms availiable), maybe we are not passing the dvm arg all the way through.

Added some debug output and looks like DVM option not getting parsed properly.

```sh
node0: (v5.0.x)$ prterun  --dvm file:dvm.uri --np 1 hostname
(main:276) DBG: pargv[0] = 'prterun'
(main:276) DBG: pargv[1] = '--dvm'
(main:276) DBG: pargv[2] = 'file:dvm.uri'
(main:276) DBG: pargv[3] = '--np'
(main:276) DBG: pargv[4] = '1'
(main:276) DBG: pargv[5] = 'hostname'
(main:427) DBG: got PRTE_CLI_DVM option opt=???????? proxyrun=1
```

**Comment by rhc54** [comment]
Couple of thoughts:

I see the following at the start of your note:
```
prte --report-uri dvm.uri &
[2] 20980
```
This indicates that there is something else already running in the background - do you perhaps have another `prte` already running? It would explain the rest of the observations.

When you get into this mode of continuing to execute cmd after cmd after cmd that all fail, you are getting into a situation where leftover cruft from a prior run creates confusion and generates the errors. You can also hit situations where a run will error out, but cleanup the cruft - often clearing out any lingering _good_ connection files.

When encountering these situations, your best option is to STOP, kill any lingering jobs, and then forcibly remove the session directory tree to clear out all lingering rendezvous files. Otherwise, you are just chasing your tail for no gain.

> Looks kind of like case where prun could not find the DVM (e.g., multiple dvms availiable), maybe we are not passing the dvm arg all the way through.

Given that this worked up at the top of your journey, I find it unlikely that we are not passing the argument thru. I wonder if it is possible that the schizo/ompi component is interpreting `--dvm file:<path>` as being the same as `--report-uri file:<path>` when passing to `prterun`? Would explain much of the above.

**Comment by naughtont3** [comment]
looks like it is 

> Given that this worked up at the top of your journey, I find it unlikely that we are not passing the argument thru. I wonder if it is possible that the schizo/ompi component is interpreting `--dvm file:<path>` as being the same as `--report-uri file:<path>` when passing to `prterun`? Would explain much of the above.

Hmmm, definitely is related to the value getting passed to `dvm` option.  I switched from `PMIX_ARG_OPTIONAL` to `PMIX_ARG_REQD` in the ompioptions and worked as expected.

**Comment by naughtont3** [comment]
doh!  :facepalm:

this is totally stupid mistake on my part.  I just realized that the optional arg for `mpirun --dvm` requires you to use an equal  (`=`) sign if providing the optional argument, (`mpirun --dvm ...` to search, `mpirun --dvm=file:dvm.uri ...`).  

Its spelled out clear as day in the `mpirun --help --dvm` info. 


Summary of *correct* commands:
```sh
prte --report-uri dvm.uri &

  # be specific about which dvm
mpirun --dvm=file:dvm.uri --np 1 hostname

   # just search for the dvm
mpirun --dvm --np 1 hostname
```

**Comment by rhc54** [comment]
If you got caught, then so will others - especially given the disconnect between `mpirun` and `prun` cmd line behavior. I would propose making them the same, but there are too many `prun` users out there already to change their side, and I don't have an immediate suggestion for the `mpirun` side. It's also a tad weird about the behavior when you misused the `--dvm` option. Since it didn't take `file:<path>` to be the argument for `--dvm`, what exactly did it do with it??

Anyway, glad you figured it out. Up to you if you want to spend a little more time trying to understand the behavior and devise a way of helping the user understand what is going on. I _might_ take a peek, but cannot guarantee it.

**Comment by naughtont3** [comment]
@rhc54 Fair point, maybe i'll add something to the stock `--dvm` output so you recognize the use of `=` when providing an optional argument.  

As for behavior, getopt treated the `file:<path>` as something unrelated to the `--dvm` option, and it would either fall back and try to connect to an existing DVM (b/c it recognized it should be looking for an existing dvm), or it would eventually fail after a spawn request with a mapper error.  I didn't look to see exactly why it ended up in map failure but assume it had to do with either a stray arg string landing down in the tail args, or further confusion about a dvm URI.

**Comment by rhc54** [comment]
Or maybe make the `--dvm` directive require an argument, and use something like `search` or `default` to indicate they should find whatever is available? I know it is less convenient than just a bare `--dvm`, but it would eliminate the potential for user confusion. Up to you.

It ended up in map because the parser interpreted the `file` to be the application, used the `:` to indicate separation between two app-contexts, and then the rest of the line as a second app. The `-np` then only applies to the second app, while the first would fill all available slots. Hence, you should error out of map due to a lack of slots. Not exactly indicative of the real problem, but I don't know what else you can do in that scenario.
