### ISSUE TITLE
node sorting with alps

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#1132]
Hi @rhc54, how about a trip down memory lane? :-)

You remember the context of the sorting in 0660221?
If so, is it still required?

I have been banging my head over some task misplacement and it turned out that the PLM and the RAS have a different notion of the daemon ordering.

The sorting code has gone over a couple of iterations, but if I disable the sorting in the current version of ALPS RAS in https://github.com/open-mpi/ompi/blob/master/orte/mca/ras/alps/ras_alps_module.c#L601, then the mapping is correct.

**Comment by rhc54** [comment]
The root cause was indeed the difference in understanding of order between PLM and RAS in systems where the selected components are different between those two frameworks. So if you are using the tm component in RAS and alps component in PLM, then you could get the problem.

If you are using the same type of component in both places, then you shouldn't need to do it. I honestly haven't thoroughly explored that behavior pattern - probably worth looking to see if we can come up with a better algorithm for setting the "reorder on launch" flag.

**Comment by marksantcroos** [comment]
The joy of (leaky) abstractions.

Once I grasp the mapping I might be able to offer a suggestion too.

**Comment by marksantcroos** [comment]
We ran into this again.

@hppritcha Whats your general configuration on Cray wrt RAS and PLM? Are you familiar with this problem?

**Comment by rhc54** [comment]
I can see the problem - it arises from the nodes being ordered to "flow" around the dragonfly, but the node naming scheme wasn't done that way. So "nid1234" isn't next to "nid1235" on the network, which is why it might show up on one Cray system and not another. This causes the regex generator to not be as efficient, which leads to overly long results that cause problems on the cmd line due to length limits.

So what we need is some way of passing both the node name and the launch id in a compressed manner. Or we need to "rediscover" and "reorder" the nodes after launch - which is what the code is supposed to be doing today. It sounds like that code isn't working correctly, or perhaps your setup is confusing it (and so the code needs some work).

I'll see if I can reproduce the issue on Gadget since I have access to that machine.

**Comment by rhc54** [comment]
Well, that didn't work - Gadget is apparently being converted to SLURM, and so I may not be able to use it to debug this problem (plus the system is stuck in half-converted state, and thus nothing works right now). I'll try to add a param that lets me test this mode.

**Comment by marksantcroos** [comment]
Thanks for the update. I'll be able to look at it myself tomorrow too. Feel free to drop me any pointers to look at.

**Comment by rhc54** [comment]
Just FYI: I'm working on this now as part of fixing the broader problem of launch at scale, which is currently messed up on the Cray due to the node reordering and a couple of other things.

**Comment by marksantcroos** [comment]
This seems to be resolved indeed! Thanks!
