### ISSUE TITLE
openmpi-4.1.4 configure fails

### ISSUE THREAD

**Issue by 1117z** [open-mpi/ompi#11411]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? 

openmpi version 4.1.4

### Describe how Open MPI was installed 

I build it from source.
and run command `./configure --prefix=${my_install_dir}` to configure

### Please describe the system on which you are running

* Operating system/version: Linux version 5.10.0-60.18.0.50.oe2203.aarch64 （openeuler os）
* Computer hardware:  HiSilicon Kunpeng 920-6426
* Network type: 

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

I ran command `./configure --prefix=${my_install_dir}` , and I got errors as followed. It didn't generate a Makefile
```
--- MCA component pmix:ext3x (m4 configuration macro)
checking for MCA component pmix:ext3x compile mode... dso
checking if external component is version 3.x or higher... yes
configure: WARNING: EXTERNAL PMIX SUPPORT REQUIRES USE OF EXTERNAL LIBEVENT
configure: WARNING: LIBRARY. THIS LIBRARY MUST POINT TO THE SAME ONE USED
configure: WARNING: TO BUILD PMIX OR ELSE UNPREDICTABLE BEHAVIOR MAY RESULT
configure: error: PLEASE CORRECT THE CONFIGURE COMMAND LINE AND REBUILD
```

**Comment by ggouaillardet** [comment]
It seems an external PMIx was detected.
Try adding
 --with-libevent=external --with-hwloc=external
to your configure command line

**Comment by 1117z** [comment]
Thanks! your suggestion reminds me that --with-xxx option cannot only be the path to external software dependencies. I run the command  `./configure --prefix=/lustre/home/acct-hpc/hpclzy/openmpi_install2 --with-pmix=internel --without-verbs`，and it build successfully. It ran all the examples in the openmpi source code, except  `spc_example`. Does it matter? And if I use internel Pmix, will the performance decrease?

**Comment by 1117z** [comment]
Thanks! your suggestion reminds me that --with-xxx option cannot only be the path to external software dependencies. I run the command ./configure --prefix=/lustre/home/acct-hpc/hpclzy/openmpi_install2 --with-pmix=internel --without-verbs，and it build successfully.  all the examples ran successfully in the openmpi source code, except spc_example. Does it matter? And if I use internel Pmix, will the performance decrease?

**Comment by jsquyres** [comment]
The rule of thumb is that if you use the internally-bundled PMIx, Open MPI will also use the internally-bundled hwloc and libevent.  If you use an external PMIx, just like the configure warnings say, you must use the same external hwloc and libevent that the external PMIx uses (otherwise you'll run into tricky linker problems).

You said that `spc_example` failed, but didn't give any details about the failure, so I can't answer that question.

PMIx is essentially used for startup/shutdown of Open MPI jobs; it's not used in MPI communication at all (there's other details, but that's a close-enough description for the purposes of this discussion).  If you're running at small to moderate scale (e.g., 32 or fewer servers), using the internally-bundled PMIx rather than a newer external PMIx will not show any meaningful difference in startup / shutdown performance wall clock execution time.

**Comment by jsquyres** [comment]
If this resolved your problem, could you close this issue?  Thanks.

**Comment by 1117z** [comment]
OK,thanks!

**Comment by cplateVT** [comment]
I had the same error, for me adding " --with-libevent=external --with-hwloc=external" did not work. The solution for me was loading the external PMIx module before configuring. Namley 'module load PMIx/4.2.6'

**Comment by dongyaolin** [comment]
我把那个--with-hwloc=/usr/local/hwloc 改为 --with-hwloc=/usr/local/hwloc-2就好的
