### ISSUE TITLE
`MPI_Waitsome` and `MPI_Testsome` don't document `statuses` array

### ISSUE THREAD

**Issue by eschnett** [open-mpi/ompi#1153]
`MPI_Waitsome` and `MPI_Testsome` do not document in their man page how the `statuses` array is defined. It is unclear whether `status[i]` corresponds to the `i`th request that was passed in, or whether it corresponds to the `i`th request that completed.

The MPI standard says "Returns in the first outcount locations of the array array_of_status the status for these completed operations." A similar sentence should be added to the two man pages.

**Comment by bosilca** [comment]
The man page for Waitsome published online (which is supposed to map one to
one with the man pages that are installed by a specific version) clearly
mention how the statuses are defined (first paragraph).

https://www.open-mpi.org/doc/v1.10/man3/MPI_Waitsome.3.php

The man page for Testsome refers back to Waitsome,  so that could be
improved.  However, it does mention in the first paragraph the return of
UNDEFINED when no requests are active.
https://www.open-mpi.org/doc/v1.10/man3/MPI_Testsome.3.php

George

**Comment by jsquyres** [comment]
@eschnett Are you asking about an older version of the man page, perchance?  @bosilca is describing the man page for v1.10.1.

**Comment by eschnett** [comment]
@jsquyres I have OpenMPI 1.10.1 installed on my OSX system via Macports. I believe I am looking at the `MPI_Testsome` manpage from this version of OpenMPI. This is the page: <https://gist.github.com/eschnett/584ff4f94ed58dc09d8d>. I see that this page is different from <https://www.open-mpi.org/doc/v1.10/man3/MPI_Testsome.3.php>.

By the way, the page <https://www.open-mpi.org/doc/> contains a pointer to man pages for version 1.10.1, but these pages describe themselves as being for version 1.10.0.

**Comment by jsquyres** [comment]
@eschnett Oops -- fixed the /v1.10/ pages to be v1.10.1 man pages.

So I think this issue is boiling down to: the `MPI_Waitsome(3)` page doesn't specify how the OUT values are defined (instead, it refers to the `MPI_Testsome(3)` page, which *does* specify how the OUT values are defined).

I could go either way: should we update `MPI_Waitsome(3)` to redundantly specify the OUT values?  Or just leave it pointing to `MPI_Testsome(3)`?

**Comment by eschnett** [comment]
My personal preference is for duplicating the information, as I'd expect man pages to be independent.
