### ISSUE TITLE
Update mpirun man page

### ISSUE THREAD

**Issue by qkoziol** [open-mpi/ompi#11730]
The mpirun man page is currently essentially an RST-ified version of OMPI v4.1’s man page. There has been some light editing
- Eliminated all -foo options
- Modernized some of the examples
- Add that we do support “single dash” mpirun options, but we don’t want people to do that.
- Much more work needs to be done to update it for all the PRTE changes since Open MPI v4.1.x.

**Comment by qkoziol** [comment]
Status update on this:
PRRTE will move to generating its help text files from RST docs, which will greatly ease the process of updating (and keeping updated) the mpirun man page.  @jsquyres will update the infrastructure in PRRTE to enable that, then I'll resume updating the mpirun man page.

**Comment by rhc54** [comment]
Just to be clear:

> PRRTE will move to generating its help text files from RST docs

This is purely an experiment at this time. @jsquyres is going to _try_ to make this work. _If_ he can successfully generate the text files in their current form, then we will look at the required RST syntax to see if it is overly complex. If it isn't, _then_ we can go this route - otherwise, we won't.

**Comment by jsquyres** [comment]
We have a draft PR where we're doing the PRTE work: https://github.com/openpmix/prrte/pull/1765

**Comment by jsquyres** [comment]
OMPI main PR merged.  All PRRTE work is now also merged, on both master and v3.0.

OMPI v5.0.x cherry pick PR is now up: #11943

**Comment by awlauria** [comment]
Thanks @jsquyres . 

v5.0.x pr merged - can we close?
