### ISSUE TITLE
[openmpi 5.0] `error: 'OPAL_RECURSIVE_MUTEX_STATIC_INIT' undeclared here (not in a function); did you mean 'OPAL_MUTEX_STATIC_INIT'?`

### ISSUE THREAD

**Issue by barracuda156** [open-mpi/ompi#12029]
Something is not right here:
```
  CC       instance/instance.lo
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/ompi/instance/instance.c:62:47: error: 'OPAL_RECURSIVE_MUTEX_STATIC_INIT' undeclared here (not in a function); did you mean 'OPAL_MUTEX_STATIC_INIT'?
   62 | static opal_recursive_mutex_t instance_lock = OPAL_RECURSIVE_MUTEX_STATIC_INIT;
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               OPAL_MUTEX_STATIC_INIT
make[2]: *** [instance/instance.lo] Error 1
```

@shintaro-iwasaki Could this be related to https://github.com/open-mpi/ompi/commit/bcd376a1158b0960746e592080e430446b5f2218 commit?

**Comment by jsquyres** [comment]
@barracuda156 Could you please provide the information asked for in the Github Issue template?  

https://github.com/open-mpi/ompi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by eschnett** [comment]
I see the same error (this may be unrelated to the original poster) when building on platforms that use `musl` as their C library instead of the GNU libc. The underlying macro you are using to initialize a recursive mutex does not exist there because it is a GNU extension and not part of the POSIX standard.

I encounter this when building OpenMPI 5 for Yggdrasil to make it available for the Julia language; see [here](https://github.com/JuliaPackaging/Yggdrasil/pull/7580). [This patch](https://gist.github.com/eschnett/5504ef80235060ee154be140f1f62625) corrects the problem for me.

**Comment by jsquyres** [comment]
@eschnett Thanks for the additional context.  @bosilca has posted a PR for this issue: https://github.com/open-mpi/ompi/pull/12034

**Comment by barracuda156** [comment]
@jsquyres Sorry, I got overwhelmed with issues to sort :) I guess, this is already understood as an actual bug and getting addressed?

P. S. When I looked through the source code with BBEdit search, I could not find what defines that macro. Now we know why.

**Comment by jsquyres** [comment]
@barracuda156 No, we didn't recognize this as an issue until it was filed and @eschnett filed the additional context (I don't think we have core community members who test on non-glibc / non-macOS platforms, and so it wasn't a problem for us).  But @bosilca filed a PR that should fix it.
