### ISSUE TITLE
How to properly run concurrent jobs without sacrificing speed?

### ISSUE THREAD

**Issue by fiftyfathoms** [open-mpi/ompi#12145]
Please submit all the information below so that we can understand the working environment that is the context for your question.

## Background information
I already asked [this question on Reddit](https://www.reddit.com/r/HPC/comments/188ajt3/), but I couldn't solve the problem using the proposed solutions. I'm going to reuse the text from my Reddit post.  

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
I have tried two Open MPI versions 4.1.6-2.1 and 5.0.0-5.1 both installed from the official repository of my Linux distribution (OpenSUSE Tumbleweed). Neither of them show any significantly different behaviour. 

### Please describe the system on which you are running

* Operating system/version: OpenSUSE Tumbleweed (Snapshot: 20231126)
* Computer hardware: A server with two AMD EPYC 7763 CPUs (each 64 cores), 1 TB RAM, filesystem of the execution path: XFS, filesystem of the root/binary path: BTRFS)
* Network type: Both sockets are on a single chassis connected to internet via Ethernet cable. 

-----------------------------

## Details of the problem

I am battling with a weird situation, where single jobs run much (almost twice) faster than when I run 2 jobs simultaneously. 
No workload manager or job scheduler is used. Jobs are identical, only ran in different directories. Each job uses fewer than the total number of available CPU cores on each socket, e.g. 48 cores. No data outputting occurs during runtime, so I guess read/write bottlenecks can be ruled out. `--bind-to socket` flag does not affect the speed. `--bind-to core` slows even the the jobs when they're run one at a time. Below you can find a summary of my attempted scenarios:

| No. | Number of concurrent jobs | Additional flags                         | Execution time [s] |
| ---: | -------------------------: | :---------------------------------------- | ------------------: |
| 1   | 1                         |                                          | 16.52              |
| 2   | 1                         | \--bind-to socket                        | 16.82              |
| 3   | 1                         | \--bind-to core                          | 22.98              |
| 4   | 1                         | \--map-by ppr:48:socket --bind-to socket | 29.54              |
| 5   | 1                         | \--map-by ppr:48:node --bind-to socket   | 16.60              |
| 6   | 1                         | \--cpu-set 0-47                          | 34.15              |
| 7   | 1                         | \--cpu-set 0-47 –bind-to socket          | 34.09              |
| 8   | 1                         | \--cpu-set 0-47 –bind-to core            | 33.99              |
| 9   | 1                         | \--map-by ppr:1:core --bind-to core      | 33.78              |
| 10  | 1                         | \--map-by ppr:1:core --bind-to socket    | 29.30              |
| 11  | 1                         | \--map-by ppr:48:node --bind-to none     | 17.26              |
| 12  | 2                         |                                          | 30.23              |
| 13  | 2                         | \--bind-to socket                        | 29.23              |
| 14  | 2                         | \--bind-to core                          | 47.00              |
| 15  | 2                         | \--map-by ppr:48:socket --bind-to socket | 67.76              |
| 16  | 2                         | \--map-by ppr:48:node --bind-to socket   | 29.50              |
| 17  | 2                         | \--map-by ppr:48:node --bind-to none     | 28.20              |
| 18  | 2                         | \--map-by ppr:1:core --bind-to core      | 73.25              |
| 19  | 2                         | \--map-by ppr:1:core --bind-to core      | 73.05              |  
  
My expectation is two or more jobs would take as long as a single job to complete, given that enough cpu core are available for each (or at worst with a 10%-20% overhead not ~100%). I appreciate if you could please help me fix the issue.

**Comment by ggouaillardet** [comment]
Your assumption that two concurrent jobs should take the same time that a single job is only valid for compute-bound programs (such as HPL). Most apps are memory bound, so that assumption is generally invalid.

Anyway, if you invoke `mpirun` concurrently from a terminal, both jobs know nothing about each other and you will likely end up sharing some resources.
Your best option is to use a resource manager so both jobs get assigned different resources.
If this is not possible, a lesser evil is to `mpirun --bind-to none ...` and let the Linux scheduler assign different cores to each jobs.
If your job is hybrid MPI+OpenMP, you will also need to make sure the OpenMP runtime does not perform any binding.

**Comment by rhc54** [comment]
Alternatively, you can manually separate the two by adding to each cmd line a list of cpu's that invocation of `mpirun` is allowed to use. Precise syntax is different for OMPI versions, but `mpirun --help` should hopefully give you a hint on how to do it.

**Comment by fiftyfathoms** [comment]
> Anyway, if you invoke `mpirun` concurrently from a terminal, both jobs know nothing about each other and you will likely end up sharing some resources. Your best option is to use a resource manager so both jobs get assigned different resources. 

By resource manager do you mean something like Slurm? I though usage of Slurm would only make sense for more than one node and for many users. This is not the case for me. If you think it can circumvent this problem somehow, I will definitely give it a go.   
  
> If this is not possible, a lesser evil is to `mpirun --bind-to none ...` and let the Linux scheduler assign different cores to each jobs. If your job is hybrid MPI+OpenMP, you will also need to make sure the OpenMP runtime does not perform any binding.  
  

I already tried `--bind-to none`. I couldn't get any benefit from it, compared to using no flags at all. You can find the results for single and two jobs in the table. My job is not hybrid.

**Comment by fiftyfathoms** [comment]
> Alternatively, you can manually separate the two by adding to each cmd line a list of cpu's that invocation of `mpirun` is allowed to use. Precise syntax is different for OMPI versions, but `mpirun --help` should hopefully give you a hint on how to do it.

If you mean assigning exact CPU numbers I have tried this as well without any success. For example take a look at attempts 6 to 8.  I also tried the syntax with all CPU numbers separated by commas, which led to similar execution times.   

If I understood your answer wrong, please give a bit more detail what you mean. What I don't understand is, why without any flags we get the best performance, and with any kind of binding we get either the same or worse results.  

I also wonder what another scheduler/resource manager would do under the bonnet that cannot be replicated with flags or simple scripts for a few jobs directly with Open MPI.

**Comment by rhc54** [comment]
A resource manager would only help to separate the resources - and yes, you can accomplish the same thing using appropriate flags for `mpirun`. That said, your problem isn't separation of resources as you show major runtime differences when executing a single job using different flags. So you really need to sort that out first.

You have two sockets of 48 cores each, so by default OMPI sees 96 slots on the node. Example 1 doesn't specify the number of procs, so we will run 96 procs. When running more than 2 procs, OMPI will default to bind to the socket. Hence, no surprise that your examples 1 and 2 yield the same time.

Example 3 being slower likely means that you do have resource contention somewhere in your app, perhaps in a layer underneath your own code. Regardless, it looks like you need to share resources, and so binding a proc to a specific core may not be the best for you.

Example 5 runs only half of the procs as examples 1-4 do - only 48 procs on the node instead of 96. Interesting that it completes in the same time as examples 1-2. I have no idea what your code does, but it appears that more procs doesn't help it achieve faster completion.

Examples 6-8 may well be incorrect in their cpu specification - I don't know how AMD and your BIOS set the cpu numbering. You might want to look at that more carefully. AMD added something to OMPI v5 that allows them to harvest the mapping info to display it on their website - supposedly wanted to help users determine the best mapping to use by giving them an interactive "set the policy and see the results" site. You might want to look for that or ask them about it.

Example 9 is the same as example 3, and the times aren't that dissimilar. Again, it runs 96 procs instead of 48 like you do in other examples.

Example 10 is the same as example 2 - odd that the times are so different. You might want to add `--display map-devel` to your cmd line and compare the layout to see why.

Example 11 is 48 procs - even though we don't bind them, the OS will strive to keep a proc on the same socket as it moves from one scheduling slice to the next. So binding to the socket layer isn't all that critical, and the times reflect it.

So it looks to me like your app runs just as fast with 48 procs as it does with 96 - which supports @ggouaillardet comments regarding resource contention beyond that of the cpus. Binding procs to their socket seems to work best, and that is the default anyway - which is why no flags is just as good as passing the right flags.

**Comment by ggouaillardet** [comment]
You can first run one job alone on half the cores with

`mpirun --bind-to core --map-by socket ...` in order to use half the cores of each socket (that should be run `3`)
Then run `mpirun --bind-to core --map-by core ...` in order to use half the cores but on a single socket (that should be run `9`)
The performance difference is likely explained by your application being memory bound (two sockets means twice the memory bandwidth and hence better performances), so your initial assumption that two concurrent jobs should not impact each other is likely wrong.

Also note run `3` is slower than run `1`, my guess is your app is using OpenMP or threads under the hood, and hence using more than one core per MPI task in run `1` (in run `3` it uses one thread per task, or multiple threads that end up doing time sharing).

**Comment by fiftyfathoms** [comment]
I just want to thank you for your replies and assistance so far, before going through your points.

> You have two sockets of 48 cores each, so by default OMPI sees 96 slots on the node. Example 1 doesn't specify the number of procs, so we will run 96 procs. 
  
Two sockets of 64 cores each. So OMPI should see 128 slots on the node with hyper threading off. I omitted all of the `-np 48` from the table. Every run reported on the table is started using `-np 48`. The concurrent jobs as well, which means even when both jobs are started still 32 physical cores should be left free on the node.  

> When running more than 2 procs, OMPI will default to bind to the socket. Hence, no surprise that your examples 1 and 2 yield the same time. Example 3 being slower likely means that you do have resource contention somewhere in your app, perhaps in a layer underneath your own code. Regardless, it looks like you need to share resources, and so binding a proc to a specific core may not be the best for you.
  
Ok, these make sense to me.   

> Example 5 runs only half of the procs as examples 1-4 do - only 48 procs on the node instead of 96. Interesting that it completes in the same time as examples 1-2. I have no idea what your code does, but it appears that more procs doesn't help it achieve faster completion.  
  
I'm not sure if I get what you mean here. I just tried this combination out of curiosity. Again, there is no difference between `np` of any of the jobs. If I understand correctly I have 1 node, two sockets, and 128 cores. So mapping 48 to node, should not start at all. It's strange that it starts, and it's the one of the fastest jobs. While run 4 takes twice as long. I have used this code previously on Slurm-managed much bigger clusters with many nodes, although with intel cores, and on small workstations (which have 1 socket). This is the first time I'm testing it on a node that has the OS running on the same node. Maybe that's somehow relevant.  

> Examples 6-8 may well be incorrect in their cpu specification - I don't know how AMD and your BIOS set the cpu numbering. You might want to look at that more carefully. AMD added something to OMPI v5 that allows them to harvest the mapping info to display it on their website - supposedly wanted to help users determine the best mapping to use by giving them an interactive "set the policy and see the results" site. You might want to look for that or ask them about it.  

This is a very good point. Which made me think about looking at their documentation and contacting them about this issue. 
  
> Example 9 is the same as example 3, and the times aren't that dissimilar. Again, it runs 96 procs instead of 48 like you do in other examples.
> 
> Example 10 is the same as example 2 - odd that the times are so different. You might want to add `--display map-devel` to your cmd line and compare the layout to see why.
> 
> Example 11 is 48 procs - even though we don't bind them, the OS will strive to keep a proc on the same socket as it moves from one scheduling slice to the next. So binding to the socket layer isn't all that critical, and the times reflect it.
> 
> So it looks to me like your app runs just as fast with 48 procs as it does with 96 - which supports @ggouaillardet comments regarding resource contention beyond that of the cpus. Binding procs to their socket seems to work best, and that is the default anyway - which is why no flags is just as good as passing the right flags.  

I guess these statements stem from the misunderstanding that my code is run with 96 processes in some runs. I hope I have made it clear now. If this is the case, I appreciate if you could revise your comments based on the new information.

**Comment by fiftyfathoms** [comment]
> You can first run one job alone on half the cores with
  
I think there was a misunderstanding. I clarified it in my previous comment. I appreciate if you could update your opinion based on the clarification.  

> `mpirun --bind-to core --map-by socket ...` in order to use half the cores of each socket (that should be run `3`) Then run `mpirun --bind-to core --map-by core ...` in order to use half the cores but on a single socket (that should be run `9`) The performance difference is likely explained by your application being memory bound (two sockets means twice the memory bandwidth and hence better performances), so your initial assumption that two concurrent jobs should not impact each other is likely wrong.  

The  server has 1 TB available memory, on 16 total memory channels (16*64GB). Each process takes like 13GB memory. Can it still be memory related?  

> Also note run `3` is slower than run `1`, my guess is your app is using OpenMP or threads under the hood, and hence using more than one core per MPI task in run `1` (in run `3` it uses one thread per task, or multiple threads that end up doing time sharing).

I don't think this is the case, but I'll investigate. Thanks for your assistance.

**Comment by ggouaillardet** [comment]
One core has 512 kB (private) L2 cache, and one socket has 256MB (shared) L3 cache, so yes, your tasks will be competing for memory bandwidth even with "only" 13GB each.
