### ISSUE TITLE
gpu aware mpi

### ISSUE THREAD

**Issue by fxz08** [open-mpi/ompi#12151]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

5.0.0.tar.gz

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source/distribution tarball

### Please describe the system on which you are running

* Operating system/version: RedHat
* Computer hardware: amd gpu*4
* Network type:  

-----------------------------

## Details of the problem

I found that the running time of a single amd gpu of mpi installed with "./congfigure --with-ucx=/usr/local/ucx --with-rocm=/opt/rocm" (ucx is build with rocm) is significantly longer than that of "./congfigure --with-ucx=/ usr/local/ucx" (ucx is build without rocm)，a test case I used took 720s and 680s for a single amd gpu respectively.

**Comment by fxz08** [comment]
Is this situation normal？

**Comment by fxz08** [comment]
using hipMalloc

**Comment by edgargabriel** [comment]
that is a bit old to be honest, any chance you could update to a newer version (e.g. 5.6 or 5.7 series)? Also, I noticed that you said you run both UCX and Open MPI without rocm support as well? I think the issue there is that this *might* work for smaller problem sizes, but for larger problem sizes it is definitely not recommend, you would have to compile at least UCX with rocm support, I would also recommend to compile Open MPI with rocm (although depending on the MPI functionality in your code you can get away without that)

There is some processing overhead when compile UCX and Open MPI with rocm because both UCX and Open MPI have to check for every pointer whether its device or host memory, but you will see the benefits because of faster data transfer times for device-to-device transfer, the larger the message the larger the performance benefit.

**Comment by fxz08** [comment]
@edgargabrie l also encountered another problem. In a node with 4 v100 graphics cards, the system is ubuntu20.04, the ucx version is 1.14.1 and built with cuda. I calculated the same example using openmpi4.1.6 and 5.0.0 respectively, both are built with cuda, but the difference in the calculation time of using 4 gpu cards is a little obvious. Using openmpi5.0.0 is slower than openpi-4.1.6, with calculation times of 195s and 174s respectively.

**Comment by fxz08** [comment]
@edgargabriel Do OpenMPI versions before 5.0.0 support direct device-to-device transmission on AMD GPUs?

**Comment by edgargabriel** [comment]
Open MPI itself does not. However, if you use Open MPI 4.1.x with a UCX version that has rocm support, you will be able to achieve device-to-device transfers through UCX for AMD GPUs

**Comment by janjust** [comment]
Closing, please reopen if we need to address further or can move the discussion to the slack channel
