### ISSUE TITLE
Configure --with-tm=/opt/pbs/ with PBS Professional fails with openmpi-5.0.3, succeeds with openmpi-4.1.4

### ISSUE THREAD

**Issue by scc138** [open-mpi/ompi#12538]
The same script run on the same system with the same version of PBS Pro installed succeeds with openmpi-4.1.4.tar.gz rather than openmpi-5.0.3.tar.gz

```
OS:
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"

Installed packages:
pbspro-devel/now 2024.1.0.20240130071604-1 amd64 [installed,local]
pbspro-server/now 2024.1.0.20240130071604-1 amd64 [installed,local]


root@PBSServer:~/openmpi-5.0.3# cat buildit
#/usr/bin/bash

#set -euxo pipefail

# Make a directory for the output files
dir="`pwd`/ompi-output"
mkdir $dir

# Fill in the options you want to pass to configure here
options="--with-tm=/opt/pbs/"
./configure $options 2>&1  | tee $dir/config.out
tar -cf - `find . -name config.log` | tar -x -C $dir

# Build and install Open MPI
make V=1 all 2>&1          | tee $dir/make.out
make install 2>&1          | tee $dir/make-install.out

# Bundle up all of these files into a tarball
filename="ompi-output.tar.bz2"
tar -jcf $filename `basename $dir`
echo "Tarball $filename created"





root@PBSServer:~/openmpi-5.0.3# ./buildit

...

--- MCA component ess:tm (m4 configuration macro)
checking for MCA component ess:tm compile mode... static
checking for pbs-config path... /opt/pbs//bin/pbs-config
checking if pbs-config works... no
checking for tm pkg-config name... /opt/pbs//lib/pkgconfig/tm.pc
checking if tm pkg-config module exists... no
checking for tm header at /opt/pbs//include... found
checking for tm library (pbs) in /opt/pbs/... found -- lib
checking for tm cppflags... -I/opt/pbs//include
checking for tm ldflags... -L/opt/pbs//lib
checking for tm libs... -lpbs -lcrypto -lz
checking for tm static libs... -lpbs -lcrypto -lz
checking for tm.h... yes
checking for tm_init... no
checking for tm pkg-config name... (cached) /opt/pbs//lib/pkgconfig/tm.pc
checking if tm pkg-config module exists... (cached) no
checking for tm header at /opt/pbs//include... found
checking for tm library (pbs) in /opt/pbs/... found -- lib
checking for tm cppflags... -I/opt/pbs//include
checking for tm ldflags... -L/opt/pbs//lib
checking for tm libs... -lpbs -lcrypto -lz
checking for tm static libs... -lpbs -lcrypto -lz
checking for tm.h... (cached) yes
checking for tm_init... (cached) no
checking for tm pkg-config name... (cached) /opt/pbs//lib/pkgconfig/tm.pc
checking if tm pkg-config module exists... (cached) no
checking for tm header at /opt/pbs//include... found
checking for tm library (torque) in /opt/pbs/... not found
configure: error: TM support requested but not found.  Aborting
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
make: *** No rule to make target 'all'.  Stop.
make: *** No rule to make target 'install'.  Stop.
Tarball ompi-output.tar.bz2 created

```

It can find libpbs, but not tm_init()?

root@PBSServer:/opt/pbs/lib# nm libpbs.so  | grep tm_init
0000000000057ad0 T tm_init

In the attached .zip
ompi-output_5.0.3_fails.tar.bz2 has all requested logs/output for the failure case
ompi-output_4.1.4_works.tar.bz2 has all requested logs/output for the successful case 

[OpenMPI_PBSPro.zip](https://github.com/open-mpi/ompi/files/15267524/OpenMPI_PBSPro.zip)

**Comment by rhc54** [comment]
Altair changed the way they package PBSPro with respect to Torque and therefore changed the configure logic in PRRTE (which is used in OMPI v5 while OMPI v4 has the old logic in ORTE). You need to ensure you have installed the Torque library - it is missing or installed in a different location on your system. The correct options would now be:
```
--with-pbs=<pbs-location> --with-tm=<torque-location>
```

**Comment by scc138** [comment]
Thanks for the quick information, I confirm that replacing 
options="--with-tm=/opt/pbs/"
with 
options="--with-pbs=/opt/pbs"
allows configure to succeed and results in a completed build, though I haven't gotten things working yet.  I'll ignore that for the purposes of this issue ticket, though.

In your comment are you saying I need to have BOTH --with-pbs= and --with-tm=?  I don't have torque installed on this system.

I am still puzzled about what you think changed in PBS Professional, as well.  We (I am with Altair) didn't make any significant packaging change that I am aware of, and in the above example I kept the PBS Pro version the same (2024.1.0, the most current release) and changed only the OpenMPI version.  If you can provide any more detail I would really appreciate it.


After seeing your message I went looking for --with-pbs in the online OpenMPI docs and don't see any mention.  https://docs.open-mpi.org/en/main/installing-open-mpi/configure-cli-options/runtime.html still says:

```
--with-tm=DIR: Specify the directory where the TM libraries and header files are located. This option is generally only necessary if the TM headers and libraries are not in default compiler/linker search paths.

TM is the support library for the Torque and PBS Pro resource manager systems, both of which are frequently used as a batch scheduler in HPC systems.
```

And the information that I (only just now, I fully admit) see in configure --help also seems a bit off:


```
root@PBSServer:~/openmpi-5.0.3# ./configure --help | grep -i pbs
  --with-pbs              Build PBS scheduler component (default: yes)
  --with-tm(=DIR)         Build TM (Torque, PBSPro, and compatible) support,
```

--with-pbs looks like a Boolean here, rather than something that accepts a path to a directory, and --with-tm still mentions PBS Pro.


Thanks!

**Comment by rhc54** [comment]
Hey Scott!! I should have recognized the name - my apologies.

Things changed a few years back - not terribly long ago, but still not last week kind of thing. It used to be that the Torque launch support and the PBS scheduler were commingled, so if we built one we built both. We then started hitting places where someone had PBS installed, but not Torque - apparently the packaging changed where that was now possible.

So we altered our configure logic to mirror that new reality by adding a `--with-pbs` flag alongside the `--with-tm` one. We don't link against any PBS libraries, so `--with-pbs` is indeed just a binary for now - if we someday do need to link against a lib, we can extend the configure support for that option. The `--with-tm` option needs to tell us where to find the Torque library.

This was all initially encountered in PRRTE and so it only made its way into OMPI v5. I don't think the OMPI folks made the changes in the OMPI v4 series, but I haven't really been tracking them.

**Comment by rhc54** [comment]
So just to be clear:

* `--with-pbs` means to build the PBS scheduler support. Builds the PRRTE component that picks up the allocation and the PBS support component in PMIx, assuming it was populated (currently is not). The latter is to enable support for the PMIx scheduler integration.
* `--with-tm=<foo>` means to build the Torque launcher support and points to where the Torque library can be found. Minus that, some people use the ALPS or PALS launchers in place of Torque, depending on their system. If nothing else is available, we default to `ssh`.

Hope that helps.

**Comment by subhasisb** [comment]
hi, you are really saying that we need both --with-pbs and --with-tm to build with PBS + with the task manager launcher integration. Just --with-pbs would build PBS PMIx support, but OpenMPI will launch using ssh, so --with-tm will be needed to ask OpenMPI to launch via the PBS task manager interface.

**Comment by rhc54** [comment]
Yes, that is correct - with one change. The `--with-pbs` option also builds the PBS PRRTE support for detecting and parsing the PBS allocation into PRRTE's resource tracker.

**Comment by rhc54** [comment]
My apologies - I wasn't entirely complete in my answers. I went back and looked at the configure code as I was a little bothered by the `--with-pbs` option being required. It isn't quite that simple. Because we don't link to a library to obtain the allocation, the resource discovery component automatically builds unless the user requests that it _not_ be built. Specifically:

* if configured `--without-pbs` or `--with-pbs=no`, then the PBS resource discovery component will not be built
* if configured `--with-pbs`, or `--with-pbs=yes`, or if no option was specified, then the component will be built _if_ we are on a Linux, AIX, or OSX system. AFAIK, those are the only environments supported by PBS

The TM launch component requires a library, and so we have to find it. Thus, it's configure logic is more complicated:

* if configured `--without-tm` or `--with-tm=no`, then the TM launch component will not be built
* if configured `--with-tm`, or `--with-tm=yes`, then we will search the default locations for the TM library - the launch component will be built _if_ the library is found. The configure procedure will _fail_ if the library is not found since support was specifically requested
* if no option is provided, then we will search the default locations for the TM library - the launch component will be built _if_ the library is found. Configure will continue and the component will not be built if the library is not found
* if configured `--with-tm=<foo>`, then we will search only the specified location - if the library is found there, then the component will be built, otherwise configure will fail

Note that we also deal with the following change that occurred:
```text
    # Note that Torque 2.1.0 changed the name of their back-end
    # library to "libtorque".  So we have to check for both libpbs and
    # libtorque.
```
Sorry this sounds complex - it is an attempt to build PBS scheduler and Torque launch support wherever possible.

Please note that I explicitly turned over maintenance of the RM-specific components in PRRTE to the respective RM companies a couple of years ago as I attempt to retire (your rep was at the meetings that discussed this, and I'm pretty sure he at least tried to pass it along - but I know how such things can fall thru cracks). So you folks technically "own" these components- which means you can change this logic as you deem fit. Last changes I see were done by me in 2022.

**Comment by subhasisb** [comment]
Thanks for the detailed explanation Ralph. We will try this out and report back further. I am not sure we (anybody from the PM/engineering teams) were aware about owning the RM component, i guess we will follow up about that separately.
