### ISSUE TITLE
Why does the program still listen to 0.0.0.0 after I set the mca parameter btl_tcp_if_include，the  btl_tcp_if_include not effect?

### ISSUE THREAD

**Issue by heilengleng** [open-mpi/ompi#12668]
### v4.1.5

-----------------------------

## Details of the problem

```shell
shell$ mpirun -host xx.xx.xx.86,xx.xx.xx.87 --mca btl_tcp_port_min_v4 40000 -n 2 ./main7
```

**ifconfig result:**

```shell
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet xx.xx.xx.86  netmask 255.255.255.0  broadcast xx.xx.xx.255
        RX packets 189867318  bytes 433957064916 (404.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 52421420  bytes 82846961456 (77.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 61036  bytes 7362307 (7.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 61036  bytes 7362307 (7.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

ompi_info -all result:

```shell
ompi_info -all | grep btl_tcp_if_include
             MCA btl tcp: parameter "btl_tcp_if_include" (current value: "eth0", data source: environment, level: 1 user/basic, type: string)
                          Comma-delimited list of devices and/or CIDR notation of networks to NOT use for MPI communication -- all devices not matching these specifications will be used (e.g., "eth0,192.168.0.0/16").  If set to a non-default value, it is mutually exclusive with btl_tcp_if_include.

```

The btl_tcp_if_include parameter is set using export OMPI_MCA_btl_tcp_if_include=eth0, but not effect in my program.

0.0.0.0 and 127.0.0.1(lo) still listened, why?

**netstat result:**

```shell
netstat -nap | grep main

tcp        0      0 xx.xx.xx.86:42135       0.0.0.0:*               LISTEN      1340804/main7       
tcp        0      0 0.0.0.0:40000           0.0.0.0:*               LISTEN      1340804/main7       
tcp        0      0 127.0.0.1:47299         0.0.0.0:*               LISTEN      1340804/main7       
tcp        0      0 127.0.0.1:53376         127.0.0.1:57619         ESTABLISHED 1340804/main7       
tcp        0      0 xx.xx.xx.86:40000       xx.xx.xx.87:48643       ESTABLISHED 1340804/main7       
tcp       64      0 xx.xx.xx.86:48412       xx.xx.xx.87:49627       ESTABLISHED 1340804/main7 
```

**Comment by bosilca** [comment]
`btl_tcp_if_include` limits the egress interfaces. Listening to `0.0.0.0` is common practice to listen on all local interfaces. Look at all the establiched connections and you will notice they respect the `btl_tcp_if_include`.

**Comment by heilengleng** [comment]
> `btl_tcp_if_include` limits the egress interfaces. Listening to `0.0.0.0` is common practice to listen on all local interfaces. Look at all the establiched connections and you will notice they respect the `btl_tcp_if_include`.

my expected listening result should be something like this:

```
tcp        0      0 xx.xx.xx.86:42135       0.0.0.0:*               LISTEN      1340804/main7    
tcp        0      0 xx.xx.xx.86:40000       xx.xx.xx.87:48643       ESTABLISHED 1340804/main7       
tcp       64      0 xx.xx.xx.86:48412       xx.xx.xx.87:49627       ESTABLISHED 1340804/main7 
```

what are the function of the listening and established functions?

```
tcp        0      0 0.0.0.0:40000           0.0.0.0:*               LISTEN      1340804/main7       
tcp        0      0 127.0.0.1:47299         0.0.0.0:*               LISTEN      1340804/main7       
tcp        0      0 127.0.0.1:53376         127.0.0.1:57619         ESTABLISHED 1340804/main7
```

**Comment by heilengleng** [comment]
I think it's not safe to enable all-zero listening.

**Comment by ggouaillardet** [comment]
As pointed by George, sockets are bound to a specific network interface.

Also, `btl/tcp` will drop connections coming from an unexpected IP address.

**Comment by heilengleng** [comment]
> As pointed by George, sockets are bound to a specific network interface.
> 
> Also, `btl/tcp` will drop connections coming from an unexpected IP address.

I think all-zero listening means that my external IP address is also enabled for listening, which may cause attackers to use this external IP address to  attack my server.

**Comment by heilengleng** [comment]
Is there a way to disable all-zero listening

**Comment by ggouaillardet** [comment]
is the external IP address on a dedicated interface?
if so, are you able to connect on the listening port from an external machine via this external IP?

**Comment by heilengleng** [comment]
> is the external IP address on a dedicated interface? if so, are you able to connect on the listening port from an external machine via this external IP?

I think so. I set the **lo** to run program via btl_tcp_if_include=lo, on the other server, run the **telnet eth0 40000** command. The connection can be established.(the test program runs only on the local computer.)

```shell
mpirun  --mca btl_tcp_port_min_v4 40000 -n 2 ./main7

ompi_info -all | grep btl_tcp_if_include
             MCA btl tcp: parameter "btl_tcp_if_include" (current value: "lo", data source: environment, level: 1 user/basic, type: string)
                          Comma-delimited list of devices and/or CIDR notation of networks to NOT use for MPI communication -- all devices not matching these specifications will be used (e.g., "eth0,192.168.0.0/16").  If set to a non-default value, it is mutually exclusive with btl_tcp_if_include.

```

on the other server, run the **telnet eth0 40000** command.

```
telnet xx.xx.xx.86 40000

Connecting to xx.xx.xx.86:40000...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

```

```shell
[root@localhost bin]# netstat -nap | grep main7
tcp        0      0 xx.xx.xx.86:54695       0.0.0.0:*               LISTEN      2340201/main7       
tcp        0      0 127.0.0.1:45897         0.0.0.0:*               LISTEN      2340201/main7       
tcp        0      0 xx.xx.xx.86:44051       0.0.0.0:*               LISTEN      2340200/main7       
tcp        0      0 127.0.0.1:46169         0.0.0.0:*               LISTEN      2340200/main7       
tcp        0      0 0.0.0.0:40000           0.0.0.0:*               LISTEN      2340201/main7       
tcp        0      0 0.0.0.0:40001           0.0.0.0:*               LISTEN      2340200/main7       
tcp        0      0 xx.xx.xx.86:40000       xx.xx.xx.120:52544    ESTABLISHED 2340201/main7  --this connection     
tcp        0      0 127.0.0.1:41636         127.0.0.1:53837         ESTABLISHED 2340201/main7       
tcp        0      0 127.0.0.1:41626         127.0.0.1:53837         ESTABLISHED 2340200/main7 
```

And found another problem, after I telnet establish a connection, my program hangs, do not execute the next.

**Comment by bosilca** [comment]
It did not hang, It waits for the handshake. If the special signature is not provided, the connection will eventually be dropped. Annoying maybe but not a security breach. Install a firewall and problem solved.

**Comment by jsquyres** [comment]
I think @heilengleng is correct: the TCP BTL (component in Open MPI) opens a single listening socket and binds it to all interfaces.  At a minimum, it has done this for many, many years -- possibly ever since 1.0.  That definitely does allow OS-level inbound connections on any interface.  The TCP BTL does expect a certain handshake when an inbound connection is accepted and processed; if that handshake does not occur properly, Open MPI will drop the connection.

This is *not* intended as any form of authentication, mind you.  Indeed, none of Open MPI's network connections are either authenticated nor protected (e.g., encrypted).  Instead, this is mainly to ensure that the Open MPI processes in a single job connect to each other and not others.

MPI / HPC jobs are typically run in back-end systems where little networking authentication occurs.  Some HPC-class networking protocols do have some nominal security features (e.g., shared keys), but most production environments do not add features such as strong authentication or data protection (outside of typical networking checksums, that is), and instead rely on air-gapped systems and networks, and/or intrinsic network separation mechanisms (e.g., VLANs) to segregate traffic.  Large, centralized HPC providers typically offer stronger multi-tenant protection than this -- but at the network layer (e.g., at the hypervisor and networking firmware/hardware layer), not the application layer.  (note: these are *very* general statements -- individual vendors may do different things, and I'm not attempting to speak for everyone)

This is not an excuse, it's more explaining that security at the MPI layer has never been much of a concern, mainly because of the environments where these jobs typically run.  Another reason we don't put security in the MPI layer is because that typically detracts from performance (e.g., encrypting and decrypting would definitely eat up a lot of CPU cycles).  And HPC environments typically dislike things that detract from the performance of their compute jobs (again: these are general statements; different users and different environments have different tolerances for networking overheads).

The point here is that, as @bosilca mentioned above, the `tcp_btl_*clude` filters are used for *egress* traffic of the TCP BTL, not *ingress* traffic.  I'm guessing that this point is probably not clear in our documentation.

That being said, it's likely that the TCP BTL could be adapted to only listen on specified interfaces with no (or negligible) performance difference than listening on 0.0.0.0 (and the IPV6 equivalent), but this would require a bunch of work.  It would require discerning which interfaces to listen on, creating an array of listening sockets (vs. a single socket), actively monitoring those listening sockets, ensuring the close them all down properly at process termination, etc.  This is not necessarily rocket science, but it is quite a lot of not-entirely-straightforward code that -- as far as I can remember, at least -- you're the first person to ask for.

Does that all make sense?

It may not be the answer you're looking for, but I just wanted to shed light on why Open MPI's TCP BTL is the way it is.

**Comment by rhc54** [comment]
You have the same issue and explanation for the RTE connections. I would only add that I went thru a similar exercise recently, and even the simplest port scanner will quickly find whatever port you are listening to - so assigning the listeners to something other than 0 really doesn't accomplish very much in terms of security.

Suggestion given above is the only real solution - turn on your firewall (or buy a firewall appliance) and tell it to block inbound connection requests from the Internet. I would disagree about it taking much skill to install/configure the appliance - they pretty much come out-of-the-box to block inbound connections. The skill enters in when you want to do something more complicated. 🤷‍♂️
