### ISSUE TITLE
How to get correct nread after MPI_File_read_all? 

### ISSUE THREAD

**Issue by xiaochiyue** [open-mpi/ompi#12973]
hello,

This is my code,. After MPI_File_read_all, I cannot get the right io_nread, but if  changed to MPI_File_read, io_nread is correct!

```fortran 
program test
  use mpi
  implicit none
  integer::rank,nproc
  integer::fh
  integer::ierr

  integer(kind=MPI_OFFSET_KIND)::offset
  integer::status(MPI_STATUS_SIZE)
  
  integer,parameter::io_n=11
  integer::io_nread
  integer::my_global(io_n)

  call MPI_Init(ierr)
  call MPI_Comm_size(MPI_COMM_WORLD,nproc,ierr)
  call MPI_Comm_rank(MPI_COMM_WORLD,rank,ierr)
  
  call MPI_File_open(MPI_COMM_WORLD,'cell.global',MPI_MODE_RDONLY,MPI_INFO_NULL,fh,ierr)

  do
     call MPI_File_read_all(fh,my_global,io_n,MPI_INTEGER,status,ierr)
     call MPI_Get_count(status,MPI_INTEGER,io_nread,ierr)

     offset=offset+io_nread*4
     
     if(rank==0) write(*,*) 'io_nread=',io_nread
     if(io_nread==0) exit 
  enddo
  
  
  call MPI_File_close(fh,ierr)
  
  call MPi_Finalize(ierr)
  
  
end program test

```

Thx 

xg

**Comment by edgargabriel** [comment]
Getting the correct number of elements for collective I/O operations is actually surprisingly tricky. Collective I/O is typically implemented by selecting a few processes to perform additional operations (e.g. data gathering from other processes, sorting based on file offsets etc.), the so-called aggregators. The aggregators are also performing the actual file I/O, i.e. reading and writing the data. If an aggregators reads less data than requested by user, breaking this down to what this translates to every single process is not trivial, since an aggregator manages the data of multiple processes, and it needs break it down which process is affected and how much.

If your code truly relies on that information, I would recommend to stick to individual I/O operations instead of collective I/O, but this will come at a performance penalty. With Open MPI, you could also force to use the individual component for collective I/O (eg. add ```--mca fcoll individual``` to your mpirun command line), in which case it will also return the correct values, but it does that by implementing File_read_all using File_read, so the same performance issue will be there as well.

Alternative would be that your code determines the actual file size ahead of time such that it can post the correct size read operation, and not rely on the status ocunter.

**Comment by xiaochiyue** [comment]
Edgar, your comment is very helpful ! Thank you very much
