### ISSUE TITLE
MPI_GET_ADDRESS fails with MPI_BOTTOM

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1355]
As pointed out by @dalcinl, MPI_GET_ADDRESS fails when passed MPI_BOTTOM.

See http://www.open-mpi.org/community/lists/devel/2016/02/18578.php

**Comment by jsquyres** [comment]
@dalcinl also sent a small test reproducer which should be added to our regression tests:

```c
#include <mpi.h>
int main(int argc, char *argv[])
{
 MPI_Aint addr;
 MPI_Init(&argc, &argv);
 MPI_Get_address(MPI_BOTTOM, &addr);
 MPI_Finalize();
 return 0;
}
```

**Comment by bosilca** [comment]
MPI_BOTTOM is defined as a "constant" by the MPI standard. I don't understand what you expect to get as it's address ?

**Comment by jsquyres** [comment]
Actually, you're right -- I read it too quickly this morning and thought it was segv'ing.  It's invoking an MPI exception, which seems to be the correct response.

@dalcinl please feel free to reply if you think that's incorrect.

**Comment by dalcinl** [comment]
On 11 February 2016 at 21:36, Jeff Squyres <notifications@github.com> wrote:

> Actually, you're right -- I read it too quickly this morning and thought
> it was segv'ing. It's invoking an MPI exception, which seems to be the
> correct response.
>
> @dalcinl <https://github.com/dalcinl> please feel free to reply if you
> think that's incorrect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/ompi/issues/1355#issuecomment-183001129>.
>

​Of course MPI_BOTTOM is a constant, I'm not asking about taking the
"address" of a constant expression. My point is that the following two
lines should succeed (at least on platforms where MPI_BOTTOM is equivalent
to NULL):

​MPI_Get_address(MPI_BOTTOM,&address);
assert(address == 0);

​i.e. this is equivalent to a cast

address = (MPI_Aint)MPI_BOTTOM;

Writing the C code in as slightly different way:

MPI_Aint address;
void *location = MPI_BOTTOM;
​MPI_Get_address(location, &address);
assert(address == 0);

I'm obviously not asking for the address of "location" (otherwise I would
write &location), I'm just asking MPI_Get_address() to "translate" the
address MPI_BOTTOM represents to a signed integral (of type MPI_Aint). Why
would the code above fail?

And of course, MPI_Get_address(NULL, &address) should return address==0.
Once more, I'm not trying to compute the address of NULL (in the &NULL
sense), but asking MPI to translate NULL to a signed integral (zero in this
case)


-- 
Lisandro Dalcin
============
Research Scientist
Computer, Electrical and Mathematical Sciences & Engineering (CEMSE)
Numerical Porous Media Center (NumPor)
King Abdullah University of Science and Technology (KAUST)
http://numpor.kaust.edu.sa/

4700 King Abdullah University of Science and Technology
al-Khawarizmi Bldg (Bldg 1), Office # 4332
Thuwal 23955-6900, Kingdom of Saudi Arabia
http://www.kaust.edu.sa

Office Phone: +966 12 808-0459

**Comment by dalcinl** [comment]
I forgot to mention that the Fortran bindings likely require some extra care, but in the C code implementing ``MPI_Get_address()``, removing the check for ``location == NULL`` is enough.

**Comment by hjelmn** [comment]
I think @dalcinl might be correct here. MPI_Get_address does not explicitly forbid passing MPI_BOTTOM. The text in the standard says that MPI_Get_address will return the address relative to MPI_BOTTOM. So, by definition MPI_Get_address (MPI_BOTTOM, &address) should return 0 in address.

**Comment by jsquyres** [comment]
Ok.  I'm flip-flopping here, then.  :smile: 

Let's fix it.

**Comment by bosilca** [comment]
@hjelmn argument make sense. However, the use of NULL for MPI_Get_address is only tolerated as a side-effect of the fact that we define MPI_BOTTOM as (void*)0.

**Comment by hjelmn** [comment]
True, but statements like this seem to indicate that it is a valid interpretation:

```
There is the MPI constant MPI_BOTTOM to indicate
the start of the address range. For retrieving absolute addresses or any calculation
with absolute addresses, one should use the routines and functions provided in Section 4.1.5.
``

Which helped lead me to the conclusion that MPI_Get_address(MPI_BOTTOM, ...) should give back 0. I could be wrong though.
