### ISSUE TITLE
[v1.10.0] segfault when using MPI_RECV on IB

### ISSUE THREAD

**Issue by chivee** [open-mpi/ompi#1424]
HI, i would like to know that if there is a known bug in 1.10.0 with InfiniBand.

i have wrote a simple logic with MPI_RECV and MPI_ISEND, but i got an weird bug only can reproduced when i used 8 ranks( 2 \* 4), the programs works well when i use 4(1 \* 4) or 2(1*2) ranks.

here are the call stack.

```
'''
gcrgpu1017:00188] Failing at address: 0xb9
[gcrgpu1017:00188] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f1c09819340]
[gcrgpu1017:00188] [ 1] /usr/local/openmpi-1.10.0/lib/openmpi/mca_mpool_grdma.so(mca_mpool_grdma_register+0x70)[0x7f1bf06952f0]
[gcrgpu1017:00188] [ 2] /usr/local/openmpi-1.10.0/lib/openmpi/mca_btl_openib.so(mca_btl_openib_prepare_dst+0x17d)[0x7f1bf006115d]
[gcrgpu1017:00188] [ 3] /usr/local/openmpi-1.10.0/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_recv_request_get_frag+0x5b)[0x7f1beddcaacb]
[gcrgpu1017:00188] [ 4] /usr/local/openmpi-1.10.0/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_recv_request_progress_rget+0x2d1)[0x7f1beddcb411]
[gcrgpu1017:00188] [ 5] /usr/local/openmpi-1.10.0/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_recv_req_start+0x4b7)[0x7f1beddce3c7]
[gcrgpu1017:00188] [ 6] /usr/local/openmpi-1.10.0/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_recv+0xb6)[0x7f1beddc5976]
[gcrgpu1017:00188] [ 7] /usr/local/mpi/lib/libmpi.so.12(MPI_Recv+0x12f)[0x7f1c03fbb5cf]
'''

```

```
'''
[gcrgpu1051:00790] Signal code: Address not mapped (1)
[gcrgpu1051:00790] Failing at address: 0x5d
[gcrgpu1051:00790] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7ffb8fadb340]
[gcrgpu1051:00790] [ 1] /usr/local/openmpi-1.10.0/lib/openmpi/mca_rcache_vma.so(mca_rcache_vma_tree_find_all+0x74)[0x7ffb77172a44]
[gcrgpu1051:00790] [ 2] /usr/local/openmpi-1.10.0/lib/openmpi/mca_mpool_grdma.so(mca_mpool_grdma_release_memory+0x41)[0x7ffb76557661]
[gcrgpu1051:00790] [ 3] /usr/local/mpi/lib/libmpi.so.12(mca_mpool_base_mem_cb+0x65)[0x7ffb8a29b005]
[gcrgpu1051:00790] [ 4] /usr/local/openmpi-1.10.0/lib/libopen-pal.so.13(opal_mem_hooks_release_hook+0xa5)[0x7ffb7a498d85]
[gcrgpu1051:00790] [ 5] /usr/local/openmpi-1.10.0/lib/libopen-pal.so.13(opal_memory_linux_free_ptmalloc2_munmap+0x27)[0x7ffb7a511017]
[gcrgpu1051:00790] [ 6] /usr/local/openmpi-1.10.0/lib/libopen-pal.so.13(opal_memory_ptmalloc2_free+0xb8)[0x7ffb7a513298]
[gcrgpu1051:00790] [ 7] /var/storage/shared/ipgsp/sys/jobs/application_1456339312024_0751/cntkbin/bin/cntk(_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv+0x39)[0x597c69]
'''
```

**Comment by jsquyres** [comment]
Can you upgrade to Open MPI v1.10.2?  There were definitely bug fixes between 1.10.0 and 1.10.2.  I don't know if they would specifically address your issue or not.

**Comment by chivee** [comment]
@jsquyres thank you for your suggestion, i will trying upgrade to v.1.10.2. but I would like to know is there a bug list or release note so that i can identify the problem.

**Comment by jsquyres** [comment]
We keep a list in the NEWS file in the tarball.  I *glanced* through it quickly before I replied to you; nothing jumped out at me.  But that doesn't mean that there wasn't some fix that would fix your issue.

Here's NEWS at the head of the v1.10 branch (i.e., what will eventually become 1.10.3): https://github.com/open-mpi/ompi-release/blob/v1.10/NEWS.  Note that we typically update it shortly before a release, so it hasn't gotten any bullets for the fixes that have gone in post-v1.10.2.

Finally, I notice that your 2nd stack trace shows that something is freeing memory (it looks like some kind of C++ method -- the symbol looks like typical C++ name mangling).  Have you verified that you don't have some kind of memory corruption going on in your application?  I ask because segv's when freeing memory are typically a symptom of some other problem that occurred earlier to corrupt memory, thereby causing subsequent memory manipulations to fail.

**Comment by chivee** [comment]
@jsquyres Thanks for your kindly help. i'll check the list to see that if is a known issue. for the 2nd stack trace, it seems to be some wild pointer bug with my code, but i can't reproduce that in single machine multiple processes, or with MSMPI. so i'm guessing there is a very deep bug.

**Comment by chivee** [comment]
i upgrade to the v1.10.3 and the problem still haunting me. i'm trying to rewrite an simple example to locate the bug. will let you know the updates.

**Comment by jsquyres** [comment]
Excellent; thanks.

**Comment by rhc54** [comment]
Series 1.10 has been "closed" in deference to later OMPI releases.
