### ISSUE TITLE
External PMIx server support is broken

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#1425]
@ggouaillardet @rhc54 @jladd-mlnx 
The following commit:
https://github.com/open-mpi/ompi/commit/b55b9e6aeee96fe76768b0438fad11ffb4e49fe4
Brakes launch through the SLURM plugin the assert:
https://github.com/open-mpi/ompi/blob/master/ompi/proc/proc.h#L399
is triggered because jobid was created from hash function:
https://github.com/open-mpi/ompi/blob/master/opal/mca/pmix/pmix112/pmix1_client.c#L122

**Comment by artpol84** [comment]
P.S. if I negate the 0x8000 bit all works fine:
```
OPAL_HASH_STR(my_proc.nspace, pname.jobid);                                                                                                   
pname.jobid &= ~(0x8000);
```

**Comment by ggouaillardet** [comment]
@artpol84 that is the right fix for me.

**Comment by artpol84** [comment]
@ggouaillardet Thank you,
Lets see what Ralph will say. And if everybody OK I'll PR.

**Comment by artpol84** [comment]
I think that the right solution would be to hash to `32 - 1 = 31` bit and then form the jobid so that bit 0x8000 is not used.
Otherwise we can weaken the hash.

**Comment by ggouaillardet** [comment]
right,
this is cryptology and I have no such skills ...

**Comment by rhc54** [comment]
I don't think it really matters, to be honest - SLURM doesn't support cross-job connections anyway, and so the jobid is totally arbitrary (we could just set it to '1', I suppose). One alternative we could use would be to have pmix_init check for an envar setting PMIX_JOBID, and then we could atoi that string. Would that help?

**Comment by artpol84** [comment]
SLURM may support multi job in future, so it'll be grate to consider that.
I was thinking about using PMIx_Get(PMIX_JOBID) to get the jobid. I think it is more portable way.

**Comment by rhc54** [comment]
We would need to add that to the list of things required to be provided in the environment, but that might be okay - basically, we want an int32_t that corresponds to the nspace string? Also has to be unique across the potential connection space, which could be tricky to guarantee...which is why we went to the string nspace anyway.

I wonder if we should just worry about a temporary fix here? The plan is for orte to move to using the nspace instead of an int jobid anyway, so this may not be a longterm problem.

**Comment by jsquyres** [comment]
Per the 2016-03-08 call, @rhc54 will fix this.  He thinks it's a trivial fix (even if it's a short-term fix).
