### ISSUE TITLE
ROMIO:  MPI_MODE_EXCL, Lustre striping

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#158]
Arguments passed to MPI_File_open() include
- a path on a Lustre filesystem
- a file mode containing the (MPI_MODE_CREATE | MPI_MODE_EXCL) flags
- striping parameters in the MPI_Info (e.g. "striping_factor" or "striping_unit")

The expected behavior for a non-existant path would be for the file to be created with the provided Lustre striping properties.  Instead, the file is created but MPI_File_open() returns MPI_IO_ERR (35) and does not return a file handle.

The problem stems from ADIOI_LUSTRE_SetInfo()'s pre-creating the file if striping parameters are present in the initial MPI_Info (ca. ad_lustre_hints.c:92) and then closing the descriptor so that ADIOI_LUSTRE_Open() can re-open the file.  However, ADIOI_LUSTRE_SetInfo() does not remove the MPI_MODE_EXCL flag from the ADIO_File's access_mode bit vector, so when ADIOI_LUSTRE_Open() is called it will always fail to open the file since it now exists.

Two possible solutions:

(1) Remove the MPI_MODE_EXCL flag from access_mode on successful file creation in ADIOI_LUSTRE_SetInfo(); once the file is created, all further application of this flag to the ADIO_File will cause failure.

(2) Do not close() the file descriptor open()'ed by ADIOI_LUSTRE_SetInfo(); modify ADIOI_LUSTRE_Open() to check for fd_sys already set and bypass the open() call if so.

**Comment by roblatham00** [comment]
> Has this bug been reported upstream to MPICH/ROMIO?

nope.  Or perhaps, "not at that time" but now it has.  I've opened http://trac.mpich.org/projects/mpich/ticket/226

**Comment by hjelmn** [comment]
I think Ron means http://trac.mpich.org/projects/mpich/ticket/2261

**Comment by dshrader** [comment]
I have run in to similar behavior and Nathan asked me to comment on it here. Basically, the problem is that whenever  MPI_MODE_EXCL is used with a panasas target file, a non-zero return status is returned from MPI_File_open. However, the file is created on the panasas volume but has size zero. If MPI_MODE_EXCL is not used, the file opens just fine. I am using Open MPI 1.8.5.

So, this works: 
ret = MPI_File_open(MPI_COMM_WORLD, file, MPI_MODE_CREATE|MPI_MODE_WRONLY, MPI_INFO_NULL, &fh);

This does not:
ret = MPI_File_open(MPI_COMM_WORLD, file, MPI_MODE_CREATE|MPI_MODE_WRONLY|MPI_MODE_EXCL, MPI_INFO_NULL, &fh);

I strongly suspect that a double-open is happening, but I haven't had a chance to dig in to the ad_panfs code to verify this. I did try mvapich2/1.9, and it handles MPI_MODE_EXCL just fine with a panasas target.

**Comment by roblatham00** [comment]
The problem has been perfectly explained.  I just need a bit of time to patch it.  If we open files in the hinted path, we need to either close them or update the EXCL flag.   I think close is the way to go, unless there's some weirdness about a closed file forgetting its hints?
