### ISSUE TITLE
mxm mtl component needs better configury checks

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#1876]
The mxm mtl component is not doing a good job at configury checks for devel rpms that need to be installed.  So far I've hit no zlib devel and no binutils-devel.   Its not friendly to have the build fail at the link stage for the mxm mtl component.

**Comment by ggouaillardet** [comment]
@hpptritcha that is kind of a tricky case.
```libz```, ```libbfd```, ```libiberty``` nor ```libxml2``` are not directly required by the ```mtl/mxm```.

these libraries are pulled by ```libtool``` when linking with ```libhcoll.la```.
note if you manually remove ```libhcoll.la```, then Open MPI linking works just fine.

bottom line, i do not know an elegant way of solving this.
ugly ways are 
- assume ```libhcoll``` requires ```libz```, ```libbfd```, ```libiberty``` and ```libxml2``` and require them in ```mxm/mtl```
- look for ```libhcoll.la```, and parse it in order to find the required libraries

@jsquyres any thoughts ?

**Comment by hppritcha** [comment]
closing this as not that important and as pointed out here would be tricky.  this problem is best solved using rpmbuild, etc. instead to handle dependencies on lib/devel rpms.
