### ISSUE TITLE
hello_oshmemfh link failure with xlc/ppc32/linux

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#188]
Per mail from Paul Hargrove: http://www.open-mpi.org/community/lists/devel/2014/02/14057.php

Both trunk and v1.7.5 fail to compile the oshmem examples with some undefined references.

**Comment by jsquyres** [comment]
@miked-mellanox @PHHargrove Is this issue still present?

**Comment by PHHargrove** [comment]
My recent testing of 1.8.4 release candidates and master on the effected system have been configured with `--disable-oshmem-fortran` to avoid this issue.  So, I've queue re-tests without that option and will report the results when available.

**Comment by PHHargrove** [comment]
Both 1.8.4 and master still have this problem.

**Comment by jsquyres** [comment]
@miked-mellanox Do you intend to fix this issue?

**Comment by miked-mellanox** [comment]
we don`t have access to ppc32-xlc setup to trace it.

so, I guess it is no

**Comment by PHHargrove** [comment]
@jsquyres Can we please add something about this to the README as we've done with other compiler-specific Fortran problems.

**Comment by jsquyres** [comment]
Sure, that sounds reasonable.

@miked-mellanox Can you guys add something about this at an appropriate place in the README?

**Comment by miked-mellanox** [comment]
I`m not familiar with this specific fortran software package details and setup.

@PHHargrove - could you please send proper description of the setup and limitation text and we will put it into Limitation section?
Thanks

**Comment by PHHargrove** [comment]
@miked-mellanox 

I just had a look and the README on master and 1.8 *both* contain
```
- IBM's xlf compilers: NO known good version that can build/link
  the MPI f08 bindings or build/link the OSHMEM Fortran bindings.
```

That might actually be a stronger statement than necessary, but it certainly covers the configuration I was seeing the current issue on.  So, I withdraw my request for any addition to README.

**Comment by PHHargrove** [comment]
@miked-mellanox 
While we closed this issue via documentation, I just wanted to note a few new things.
I leave it up to you to decide if this should be reopened or not.

1.  This issue is still present with Open MPI 2.0.2rc1 and current xlc/xlf.
1.  I can reproduce on OpenPOWER (64-bit little-endian, as opposed to the 32-bit big-endian of the original report).
1.  If Mellanox has an interest in pursuing this, then one can now obtain a free "Community Edition" version of xlc/xlf which reproduce the problem.
1.  I can now even offer accounts on a system where I have reproduced the problem.

**Comment by PHHargrove** [comment]
@jjhursey I figured you might be interested in the option to reopen this issue as well.
As noted in my previous comment on this issue, this oshmem link failure is now occurring on OpenPOWER with the Community Edition of the XL compilers (as opposed to the original 32-bit big-endian failures).
