### ISSUE TITLE
v2.x: --disable-mpi-io build broken w.r.t. C++ MPI bindings

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2179]
See https://mtt.open-mpi.org/index.php?do_redir=2360.

Did this get broken with https://github.com/open-mpi/ompi/pull/2064?

@ggouaillardet @edgargabriel @hjelmn Can you have a look?

**Comment by edgargabriel** [comment]
I honestly don't know anything about the C++ interface. I can try to look into this, but it will be friday until I get to it.

That being said, I honestly think more and more that the disable-mpi-io flag is non-sensical. I understand the original motivation, but I am not aware of any system where this approach (having an external MPI I/O library) is used.  There is a stronger case for --disable-io-ompio and --disable-io-romio, but not having MPI_File defined in the mpi header file? Isn't this technically a violation of the MPI spec?

**Comment by jsquyres** [comment]
I'm *guessing* that this was because of @hjelmn's #2064 (which was just merged in), but I'm not 100% sure.  Let @hjelmn have a look first.

**Comment by jsquyres** [comment]
@edgargabriel's question is probably relevant here: do we even need `--disable-mpi-io` any more?

I *think* it was motivated back when ROMIO was a standalone distribution.  But it isn't anymore.  So is this a moot point?  Should we just remove `--disable-mpi-io` support?  (I don't know if we can do this in v2.x at this point, but we certainly can for master)

**Comment by ggouaillardet** [comment]
a few #ifdef were missing, and i fixed that.

@hjelmn
open-mpi/ompi@95e63d78038b9776e5aab04536063b6017f8afeb should be cherry-picked into #2162 and #2163

**Comment by edgargabriel** [comment]
To come back to Jeff's last point, I personally think that we should remove the flag in a long term (i.e. probably on master first). My reasoning is similar to what Jeff said, but to go even one step further: the only options somebody would have to use as an MPI I/O library are ROMIO or OMPIO. There is literally nothing else out there (there are some vendor adapted versions of ROMIO, but they come prepacked with the vendor MPI libraries, and are not open source).  Open MPI supports both available MPI I/O libraries, and - as you mentioned - since ROMIO is not distributed as a standalone library anymore,  it is highly unlikely (or unheard of) that somebody would extract by themselves maybe a newer version of ROMIO from MPICH to use it with Open MPI.

**Comment by jsquyres** [comment]
#2185 filed to remove the `--disable-mpi-io` switch.
