### ISSUE TITLE
Add support for specifying SSH port

### ISSUE THREAD

**Issue by ivotron** [open-mpi/ompi#2224]
Would it be possible to have support for specifying an SSH port in for the hosts URL? E.g. `my.mpi.node:2222`

**Comment by ggouaillardet** [comment]
Did you try to use this syntax in a machine file ?

**Comment by ivotron** [comment]
Yes, on 2.0.1:

```
$ cat hostfile
my.mpi.node:2222
my.mpi.node:2222

$ mpirun --hostfile ./hostfile -np 8 lulesh2.0 -i 1 -s 240 -p
Host key verification failed.
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
Host key verification failed.
```

**Comment by jsquyres** [comment]
I do not believe that we support this functionality at present.

Two workarounds:

1. Set the `plm_rsh_args` MCA var to `-p 5678` (or whatever port number you want)
1. Set the `plm_rsh_agent` MCA var to a script that simply invokes `ssh -p 5678 $*` (or whatever port number you want)

We can leave this issue open as a feature request.

**Comment by ggouaillardet** [comment]
i made a proof of concept in #2225 
your hostfile should be updated like this
```
my.mpi.node1 port=2222
my.mpi.node2 port=2222
````

fwiw, if only port 2222 can be used to access these nodes, an other option is to edit your ```$HOME/.ssh/config``` and add an entry like this

```
Host my.mpi.node*
    Port 2222
```

**Comment by Kernle32DLL** [comment]
Are there any plans to backport this to 2.x?

**Comment by ggouaillardet** [comment]
@hppritcha shall i issue a PR for ```v2.x``` ?

**Comment by Kernle32DLL** [comment]
@ggouaillardet Also, on a related note I realized that ompi is a bit to clever for a special use-case with ports.

Trying to configure a hostfile like this will yield no error, but will not work as expected. It will start 4 nodes on cluster03pc01, using port 3313 instead.

```
cluster03pc01 port=3310
cluster03pc01 port=3311
cluster03pc01 port=3312
cluster03pc01 port=3313
```

Ompi interprets the lines all as the same node, and at each line parsed the same node instance is reused and the port overwritten. The question if it would be feasible (and desirable) to change this behavior to consider the nodes name + port combination unique, instead of just the name.

My usecase for this behavior is that cluster03pc01 is a docker server, with multiple containers running. Internally they expose the default port 22 for SSH, but externally use the ports provided above. So cluster03pc01 with different ports actually maps to different containers internally.

**Comment by rhc54** [comment]
Tracking a node based on both its name and a user-provided port would require massive changes to the code base that just wouldn't make any sense for us to absorb. I would strongly recommend you use singularity as your container instead of docker as it was designed to support HPC from the start and doesn't suffer from these issues.

**Comment by ggouaillardet** [comment]
@Kernle32DLL keep in mind that nodes must be able to communicate with each other for ```oob/tcp``` (aka out of band management) and ```btl/tcp``` for MPI communications.
since you cannot SSH directly into a container, i doubt two containers can reach each other (especially if running on two different nodes)
as a proof of concept, you can add this to your ```$HOME/.ssh/config```
```
Host c1
    Hostname cluster03pc01
    Port 3310
Host c2
    Hostname cluster03pc01
    Port 3311
```
and then
```
mpirun --hosts c1,c2 -np 2 ring_c
```
```mpirun``` will launch ```orted``` in each container, and from that, you will very likely run into an other issue such as the one i described earlier.

as explained by @rhc54, docker was not built with HPC in mind, but singularity was.

**Comment by Kernle32DLL** [comment]
@rhc54 @ggouaillardet Thanks for the input, I appreciate it! I will do some tests, and will probably move the topic to SO, as to not pollute the issue with OT discussion.

Still - the request for backport stands ;-)

**Comment by zrss** [comment]
> i made a proof of concept in #2225
> your hostfile should be updated like this
> 
> ```
> my.mpi.node1 port=2222
> my.mpi.node2 port=2222
> ```
> 
> fwiw, if only port 2222 can be used to access these nodes, an other option is to edit your `$HOME/.ssh/config` and add an entry like this
> 
> ```
> Host my.mpi.node*
>     Port 2222
> ```

@ggouaillardet  sorry for quote a old issue, but i found that it doesn't work as expected

hostfile

```
lm-mpi-job-mpiworker-0.lm-mpi-job port=2222
lm-mpi-job-mpiworker-1.lm-mpi-job port=2222
```

error info

```
Open RTE detected a parse error in the hostfile:
    /root/mpiworker.host
It occured on line number 37 on token 3.
```

mpirun command

```
mpirun --allow-run-as-root --hostfile ~/mpiworker.host -np 4 mpi_hello_world
```

**Comment by ggouaillardet** [comment]
@zrss which version of Open MPI are you running ?

**Comment by zrss** [comment]
thx ggouaillardet ! ... i get it, how an old version

```
root@lm-mpi-job-mpimaster-0:/home# mpirun --version
mpirun (Open MPI) 1.10.2

Report bugs to http://www.open-mpi.org/community/help/
```
