### ISSUE TITLE
Configure fails if path has a space character in some directory name

### ISSUE THREAD

**Issue by DemjanGrubic** [open-mpi/ompi#2269]
If some directory on the path to openmpi folder has a space character, then configure fails.
I am using ubuntu 16.04, and here are steps to reproduce:

Make a directory with name "test1 test2" (include space between).

Execute following:

```
cd test1\ test2/
wget https://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.3.tar.gz
tar -xzvf ./openmpi-1.10.3.tar.gz
cd openmpi-1.10.3
./configure --prefix=/usr/local/mpi
```

Message I get:

```
checking if MCA component dl:libltdl can compile... no
configure: WARNING: Did not find a suitable static opal dl component
configure: WARNING: You might need to install libltld (and its headers) or
configure: WARNING: specify --disable-dlopen to configure.
configure: error: Cannot continue
```

Instead of using "test1 test2" directory, it creates directory "test1" and tries to use it, if I am not wrong.
If directory doesn't contain a space character, everything works.

**_EDIT:**_ Added verbatim blocks for easier reading

**Comment by jsquyres** [comment]
@DemjanGrubic To be honest, I'm not surprised by this bug report.  Spaces are not a common convention in Linux filenames (although, as you point out, they are valid), so it's not a case that we test.  We're almost certainly missing some quoting in our configury/m4 scripting.

Unfortunately, I doubt that many of us core contributors can justify spending the time to fix this case (since it's so uncommon).  But in the spirit of [Hacktoberfest 2016](https://github.com/blog/2260-hacktoberfest-is-back), would you be interested in submitting a pull request to fix it?

**Comment by jsquyres** [comment]
We went a different way here: we just fail early if configure detects a space in various paths.  Will be in the next v4.0.x, v4.1.x, and 5.0.0 releases.

See #8128.
