### ISSUE TITLE
Something wrong with configure for atomics on master

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#3032]
I am consistently seeing this output in builds, both on my machine and from Jenkins servers:

```shell
11:10:41 checking dependency style of gcc -std=gnu99... gcc3
11:10:41 checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
11:10:41 checking the name lister (/bin/nm -B) interface... BSD nm
11:10:41 checking for fgrep... /bin/grep -F
11:10:41 checking for __atomic builtin atomics... yes
11:10:41 checking for processor support of __atomic builtin atomic compare-and-swap on 128-bit values... no
11:10:41 checking for __atomic builtin atomic compare-and-swap on 128-bit values with -mcx16 flag... yes
11:10:41 checking if __int128 atomic compare-and-swap is always lock-free... yes
11:10:41 checking if .proc/endp is needed... no
11:10:41 checking directive for setting text section... .text
11:10:41 checking directive for exporting symbols... .globl
11:10:41 checking for objdump... objdump
11:10:41 checking if .note.GNU-stack is needed... yes
11:10:41 checking suffix for labels... :
11:10:41 checking prefix for global symbol labels... 
11:10:41 checking prefix for lsym labels... .L
11:10:41 checking prefix for function in .type... @
11:10:41 checking if .size is needed... yes
11:10:41 checking if .align directive takes logarithmic value... no
11:10:41 checking if processor supports x86_64 16-byte compare-and-exchange... yes
11:10:41 checking if compiler correctly handles volatile 128bits... yes
11:10:41 checking for assembly architecture... AMD64
11:10:41 checking for builtin atomics... BUILTIN_GCC
11:10:41 checking for pre-built assembly file... no (atomic-amd64-linux
11:10:41 amd64-linux-nongas.s not found)
11:10:41 checking whether possible to generate assembly file... failed
11:10:41 configure: WARNING: Could not build atomic operations assembly file.
11:10:41 configure: WARNING: There will be no atomic operations for this build.
11:10:41 checking for atomic assembly filename... none
```

Note that this is on Intel architectures. Digging a little deeper, it isn't clear to me where the ```host``` variable is getting set, and that appears to lead to the architecture being mistakenly identified.

**Comment by ggouaillardet** [comment]
in ```OPAL_ASM_FIND_FILE``` should we also make an exception for ```BUILTIN_GCC``` just like we do for ```BUILTIN_SYNC``` and others ?

**Comment by rhc54** [comment]
I have no idea - what would that do to fix the problem of mis-identifying the architecture?

**Comment by ggouaillardet** [comment]
i will make a poc today.
at this stage, i do not think we should execute this part, so that would avoid a problem that should not exist in the first place.
i also think the arch should be 
AMD64	default-.text-.globl-:--.L-@-1-0-1-1-{0,1}
(e.g. __not__ x86_64), and it looks like the error message is just a false positive
(e.g. builtin gcc atomics are used)
but once again, i will review this today

**Comment by rhc54** [comment]
Not quite sure what you mean - I guarantee my arch is x86_64, not AMD64

**Comment by ggouaillardet** [comment]
the "arch" is used to grep ```opal/asm/asm-data.txt```
this file currently support ```AMD64```, ```IA32```, ```IA64``` and other platform.
my best bet is ```AMD64``` comes back from the first Opteron days, and it was not renamed to
a vendor neutral strings such as ```X86_64``` when Intel started building compatible processors.

then in ```OPAL_ASM_FIND_FILE```, we do 
```
if $GREP "$opal_cv_asm_arch" "${OPAL_TOP_SRCDIR}/opal/asm/asm-data.txt" | $FGREP "$opal_cv_asm_format" >conftest.out 2>&1 ; then
    opal_cv_asm_file="`cut -f3 conftest.out`"
```

```$opal_cv_asm_format``` is ```AMD64```, but because ```BUILTIN_GCC``` are used, ```opal_cv_asm_format``` is ```""```, so grep catches two lines and that part fails
 
makes sense ?

i will start the poc from now

**Comment by ggouaillardet** [comment]
@rhc54 this is fixed on master, and i will follow up on open-mpi/ompi#3039
my understanding is that the warning message is a false positive and you can safely ignore it.
here, ```AMD64``` should be read as ```x86_64``` since there is nothing specific to AMD processor
(just like ```IA32``` is not specific to Intel processors in this context)
