### ISSUE TITLE
OMPI cannot build with Libtool 2.4.3 and above

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#311]
It fails with the following error:

```
CDPATH="${ZSH_VERSION+.}:" && cd ../../../ompi/opal/libltdl && /bin/sh /Users/bosilca/unstable/ompi/trunk/ompi/config/missing aclocal-1.14 -I ../../config
aclocal-1.14: error: ../../config/autogen_found_items.m4:312: file ‘opal/mca/backtrace/configure.m4’ does not exist
```

**Comment by jsquyres** [comment]
There are now two PRs that can solve this issue (each has tradeoffs):

1. open-mpi/ompi#366: Remove libltdl from the tree
  * PRO: libltdl is now just like any other library -- we build support for it if it's there, skip it if it's not
  * CON: default behavior of dlopen/DSO support will likely disappear from many installations because libltdl-devel support (i.e., ltdl.h) is not frequently installed by default
  * CON: lose "good" error messages for when DSOs fail to open (OMPI has been locally applying a patch that didn't go upstream to Libtool)
  * CON: potentially increase MPI process size (because unused plugins can't be closed/unloaded)
1. open-mpi/ompi#390: Embed libltdl from the tree
  * PRO: preserve default dlopen/DSO behavior
  * PRO: preserve "good" ltdl error messages
  * CON: have to maintain embedded libltdl

As a community, we need to decide which one we want.

**Comment by jsquyres** [comment]
Per the Tuesday 17 Feb 2015 webex, we decided to go with #390 and ditch #366.

However, per https://github.com/open-mpi/ompi/pull/390#issuecomment-75045811, #366 has become untenable.  I'm working on a new approach; more details soon.

**Comment by jsquyres** [comment]
Just to tie off this issue: #410 was the PR that contained the final solution for this issue.
