### ISSUE TITLE
Errors compiling when using MPI within OpenMP parallel region

### ISSUE THREAD

**Issue by ccaamad** [open-mpi/ompi#3150]
Hi,

One of my users has reported that he gets compilation errors relating to `ompi_mpi_comm_world` and `ompi_mpi_int` when he uses MPI to communicate between OpenMP threads using openmpi 2.0.2.

openmpi has been configured/built with: 
        --with-sge \
        --with-io-romio-flags=--with-file-system=lustre+ufs \
        --enable-mpi-cxx \
        --with-cma \
        --enable-mpi-thread-multiple

Here's an example program:
```
#include<stdio.h>
#include<mpi.h>
#include<omp.h>

int main(int argc, char *argv[]) {
   int size, rank, required = MPI_THREAD_MULTIPLE, provided;

   MPI_Init_thread(&argc, &argv, required, &provided);

   MPI_Comm_size(MPI_COMM_WORLD, &size);
   MPI_Comm_rank(MPI_COMM_WORLD, &rank);

   if(rank == 0)
      printf("The provided thread level is = %u\n", provided);

#pragma omp parallel shared(size) firstprivate(rank) default(none)
   {
      int tid;
      int total_threads;

      tid = omp_get_thread_num();
      total_threads = omp_get_num_threads();

      if(rank == 0)
         if(tid == 0)
            printf("Total threads for each process are %u\n - printed by rank %d\n",
                   total_threads, rank);

      int send_data = rank * total_threads + tid;
      int recv_data = -1;

      MPI_Request request1, request2;
      MPI_Isend(&send_data, 1, MPI_INT, (rank+1)%size, tid, MPI_COMM_WORLD, &request1);
      MPI_Irecv(&recv_data, 1, MPI_INT, (rank + size-1)%size, tid, MPI_COMM_WORLD, &request2);

      MPI_Wait(&request1, MPI_STATUS_IGNORE);
      MPI_Wait(&request2, MPI_STATUS_IGNORE);

      printf("RANK = %u, THREAD_ID = %u, DATA RECEIVED = %u \n", rank, tid, recv_data);
   }

   MPI_Finalize();

   return 0;
```

And here is the error (GCC 4.8.5 on Centos7 x86_64 - see similar errors with Intel and PGI compilers):
```
$ mpicc -fopenmp -o g2 g2.c
g2.c: In function ‘main’:
g2.c:33:16: error: ‘ompi_mpi_comm_world’ not specified in enclosing parallel
       MPI_Isend(&send_data, 1, MPI_INT, (rank+1)%size, tid, MPI_COMM_WORLD, &request1);
                ^
g2.c:16:9: error: enclosing parallel
 #pragma omp parallel shared(size) firstprivate(rank) default(none)
         ^
g2.c:33:16: error: ‘ompi_mpi_int’ not specified in enclosing parallel
       MPI_Isend(&send_data, 1, MPI_INT, (rank+1)%size, tid, MPI_COMM_WORLD, &request1);
                ^
g2.c:16:9: error: enclosing parallel
 #pragma omp parallel shared(size) firstprivate(rank) default(none)
         ^

```

Can you help, please?

Thanks,

Mark

**Comment by ggouaillardet** [comment]
@ccaamad i C, Open MPI defines ```MPI_COMM_WORLD``` and ```MPI_INT``` macros as ```ompi_mpi_comm_world``` and ```ompi_mpi_int```. fwiw, there are many others, and Fortran is different.

that should be internal stuff that is transparent to users 99% of the time ...

because you do an omp parallel with ```default(none)```, your user is in the 1%
so he/she can either
- add a ```shared(ompi_mpi_comm_world,ompi_mpi_int)``` clause to the omp parallel
- move from ```default(none)``` to ```default(shared)``` (that will fix this issue, but might potentially hide others)

as a matter of taste, you might want to advise your user to replace
```MPI_Request/MPI_Isend/MPI_Irecv/MPI_Wait``` with a single call to ```MPI_Sendrecv()```

iirc, ```mpich``` define these as numbers instead of symbols, so you might not face this issue with mpich or its derivative.

**Comment by ccaamad** [comment]
Hi Gilles,

Thanks for the response :)

I would have thought that adding 'default(none)' was quite popular and not only used in 1% of cases.

Both of those options are pretty ugly and, since you say that there are plenty others, only going to get uglier the more MPI is used from within a OpenMP parallel region.

You are right, trying this out on a couple of mpich-derived MPIs, they work without complaint.

Is there nothing to be done to avoid exposing internal ompi variables to the user in future, please? At the very least this is a portability issue.

Cheers,

Mark

**Comment by ggouaillardet** [comment]
Mark,

```default(none)``` is pretty popular indeed. by 1% i meant invoking MPI within an omp parallel
(it will likely get more and more popular, but i am not sure many are doing this now)

i will ask other folks if they have any idea on how to make things clean and/or portable.
at this stage, i think that moving to handler a la mpich is unlikely in a near future
(we will be branching Open MPI 3 branch shortly)
so unless OpenMP allows global declaration such as
```
!$OMP alwayshared(ompi_mpi_comm_world)
```
i do not see how we can move from there.

@jsquyres @rhc54 @bosilca @hjelmn @hppritcha @PHHargrove any thoughts ?

**Comment by jsquyres** [comment]
@hppritcha You're the OpenMP expert -- thoughts?

**Comment by hppritcha** [comment]
I think at this point Gilles' always shared pragma is best way to handle this.  Probably need to do same for mpi comm self etc.

**Comment by lcebaman** [comment]
From my point of view, this makes a) `shared(ompi_mpi_comm_world,ompi_mpi_int)` not a portable solution b) `default(shared) `dangerous and bad practice

**Comment by gpaulsen** [comment]
Could someone please re-verify this with Open MPI v5 or master?
If this is still an issue, we should try to resolve this.  Please also comment as to which "current" version of OMP has been tested.

**Comment by ggouaillardet** [comment]
First things first:
the MPI standard does not specify how `MPI_COMM_WORLD` and other MPI "things" have to be implemented, this is left to the implementors.
That means that if a MPI "thing" is used inside an OpenMP region with the `default(none)` and no explicit declaration such as `shared(...)`, this is undefined behavior.
Because of MPICH implementation choices, the undefined behavior is "it works".
Because of Open MPI implementation choices, the undefined behavior is "it does not compile".
Portability does not mean a fully specified undefined behavior, so this is **not** a portability issue strictly speaking.

It might be interesting to report the fact that MPI+OpenMP is undefined behavior at the source code level to the MPI Forum. I am pretty sure they cannot do anything about that besides adding a note and/or suggesting to adopt the MPICH ABI)


if we look at this simple program (it is incorrect w.r.t. MPI, but the point here is to build and not run)
```
#include <mpi.h>

void foo() {
#pragma omp parallel default(none)
        MPI_Barrier(MPI_COMM_WORLD);
}
```
and build it

```
$ mpicc -c -fopenmp omp.c 
omp.c: In function ?foo?:
omp.c:5:2: error: ?ompi_mpi_comm_world? not specified in enclosing ?parallel?
  MPI_Barrier(MPI_COMM_WORLD);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
omp.c:4:9: error: enclosing ?parallel?
 #pragma omp parallel default(none)
         ^~~
```

same error as before ...

One way to address it would be to engage the OpenMP forum and ask them a solution.
For example, I suggested something like a `#pragma omp always_shared(...)` that has yet to be requested, specified, approved and implemented.

An other approach is to try to make Open MPI more friendly to this.
FWIW, the compilation passes (at least with GCC 8.3.1) if we replace
```
OMPI_DECLSPEC extern struct ompi_predefined_communicator_t ompi_mpi_comm_world;
```
with 
```
OMPI_DECLSPEC extern const struct ompi_predefined_communicator_t ompi_mpi_comm_world;
```
in `/.../include/mpi.h`

Note the change might not be legit, and the behavior might be an implementation choice of GCC 8.3.1.

**Comment by rhc54** [comment]
FWIW: having worked a bit between these two worlds while at my former employer, IMO @ggouaillardet is 100% correct. There is no specification for how these two programming models should interact, and thus there is no portability between various combinations of OMP and MPI implementations (and yes, the OMP ones have their little quirks too, just like MPI).

If portability is truly desired, you'll have to find a way to get the two sides together to agree on a method. The "always_shared" is the most likely solution, I suspect, as ABI compatibility across the various MPI implementations is unlikely in my lifetime (though I am admittedly old).

**Comment by hppritcha** [comment]
closing as won't fix.
