### ISSUE TITLE
2.0.x missing include/openmpi/ompi/mpi/cxx

### ISSUE THREAD

**Issue by yqin** [open-mpi/ompi#3173]
After a clean build and install, it wouldn't compile the very basic mpi_hello.cc.

$ cat mpi_hello.cc
#include <mpi.h>
int main(int argc, char* argv[])
{
    MPI::Init(argc, argv);
    int num_procs = MPI::COMM_WORLD.Get_size();
    int rank = MPI::COMM_WORLD.Get_rank();
    MPI::Finalize();
    return 0;
}

Errors:

$ mpicxx mpi_hello.cc
mpi.cc: In function 'int main(int, char**)':
mpi.cc:5: error: 'MPI' has not been declared
mpi.cc:6: error: 'MPI' has not been declared
mpi.cc:7: error: 'MPI' has not been declared
mpi.cc:8: error: 'MPI' has not been declared

So I traced it and notice that the whole $OMPI_ROOT/include/openmpi/ompi/mpi/cxx directory is missing from the installation. Is this expected?

**Comment by ggouaillardet** [comment]
shouldn't you
```c
#include <mpicxx.h>
```
instead ?

**Comment by ggouaillardet** [comment]
also note the C++ bindings are no more built by default (the driving factor is they are now deprecated from the standard), so you have to
```
configure --with-mpi-cxx
```

fwiw, some C++ developers think MPI C++ bindings were poorly designed, and BoostMPI is a better alternative

**Comment by jsquyres** [comment]
This is [almost] the issue.  

The MPI Forum has *deleted* the C++ bindings from the MPI-3.0 standard (they were deprecated in MPI-2.2 and deleted in MPI-3.0).

Open MPI v2.x therefore no longer builds the C++ bindings by default.  Hence, you need to `--enable-mpi-cxx` on the configure command line to build C++ bindings support in your Open MPI (Gilles got the CLI option *almost* correct 😉 ).

Also, you do *not* need to include `<mpicxx.h>` -- once you configure/build Open MPI with `--enable-mpi-cxx`, including `<mpi.h>` will include the C++ bindings properly.

I'm going to close this issue, because this should solve your problem.  Please let us know if it does not.

**Comment by dineiar** [comment]
Just to keep documented if anyone needs it, the switch to compile C++ bindings in [OpenMPI v2.1](https://www.open-mpi.org/software/ompi/v2.1/) (the last supported version with C++ bindings available) is:
```
./configure --enable-mpi-cxx
```
