### ISSUE TITLE
MESOS support

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#3211]
Transferring this from the PMIx issue tracker:

```
High level my use case is I'm trying to start up some kind of process manager / server
on some machine, have a number of processes all running on separate machines
connect to it, then create an intracommunicator and start making MPI calls like
normal (I'm using OMPI 2.x). Obviously normally you would do this with an mpiexec
that lists all the hosts up front, but I'm trying to use Mesos where I need to launch
a task on each machine separately and then have them connect up somehow.
Mesos provides a way to do this with an older version of MPICH that uses mpd, and
there's some other code out there that does it with a newer version of MPICH
that uses Hydra, but in both cases the underlying implementation of how that
Mesos code does this is kind of brittle.

I have thoughts on how I can shoehorn Open MPI into doing what I need, but I
was hoping PMIx would help with this. If I'm totally misunderstanding what PMIx
is intended for / how it might help in this case, just let me know. :o)
```

There has been at least one prior attempt to port OMPI to Mesos, but that was done by a graduate student who didn't transition the code to the OMPI repo before he graduated and left school. The primary issue, IIRC, is that Mesos doesn't support fork/exec, and so the daemons cannot start the local procs.

Assuming that is accurate, then the procedure to make this work would be:

1. start mpirun somewhere with a new ```--self-organize N``` cmd line option. We would create a new state machine component to support this mode, which basically tells mpirun that it won't be launching any daemons - it will just wait to hear from the indicated number of daemons as they "phone home". You would also use the ```--report-uri``` to have mpirun provide (either in a file or to stderr/out) its contact info.

1. have Mesos start an orted on each node, passing the orted the contact info from mpirun using the ```--hnp``` cmd line option. This will cause the orted to "phone home" to mpirun, letting it know that this orted is alive.

1. we would add a new "mesos" component to the ORTE/PLM framework. Once all daemons had reported in, this component would (a) inform each daemon as to the number of local procs it should expect, and (b) have Mesos launch that number of procs on the node. We would include the required local orted connection info in the environment of each proc so it could contact that orted.

From there, everything should run as usual. This assumes that we either have programmatic access to a Mesos launch command to launch the procs, or can do it by calling ```system```. Of course, if we have that, then we could also use it to start the daemons, thus making it easier for the user and eliminating the need for the new mpirun cmd line option. All we would need is the last item, which I can help you setup if you know the Mesos interfaces or cmd lines.

@asylvest

**Comment by asylvest** [comment]
Thanks for the thoughts.  This 'phone home' idea is roughly along the lines of what I was thinking, though I was planning on implementing that directly myself in my application via sockets or something similar.  It would of course be cleaner if OMPI supported it directly.

Let me do a little playing around with Mesos to confirm exactly what the constraints are here (confirm we can't fork/exec, etc.) and then I'll get back to you to make sure we're working in the right direction.

Along those lines... I have done a little bit of messing with using a custom launcher in the past when I was trying to get Open MPI working across Docker containers without ssh'ing, but I'm not overly familiar with details of what you can and can't get orted to do.  I know the OMPI doc page says that orted commands are subject to change from version to version and you should just run `orted --help` to see them but this doesn't provide a ton of info.  For example, I'm not really sure what HNP is.  Just wondering if there's any more documentation out there that you could point me to (in a quick Google search I just found this paper which talks about some OpenRTE details - not sure if it's dated but I'll take a closer look when I have a few: https://www.open-mpi.org/papers/euro-pvmmpi-2005-orte/euro-pvm-mpi-2005-orte.pdf).

**Comment by rhc54** [comment]
Yeah, I fear that paper is indeed badly dated. We should probably publish something more current. I've been trying to find time to document ORTE in the wiki, but that's been hard to come by of late.

I'll help you implement this as a way of also transferring some relevant knowledge. Docker is a more complicated problem, frankly, but this one shouldn't be all that hard. There must be some way to tell Mesos "launch this process, with these arguments, on that node". This is all we really need. The rest will be pretty minor and mostly in (probably new) state machine components.

FWIW: "HNP" => "head node process" which translates to "mpirun".

**Comment by asylvest** [comment]
So that I don't have to instantly devolve into ASCII art, I'll reference the architecture diagram at the top of http://mesos.apache.org/documentation/latest/architecture/ for the terminology I'll be using.  I'll have a total of numAgents + 2 separate machines running - one for the scheduler, one for the master, and one for each agent.  Basically what happens is that my scheduler, written in C++, registers itself with the master and then implements a number of callbacks.  The two we care about are called resourceOffers() (where the master tells us which agents are available to do work... it provides us information about those agents including their IP address) and statusUpdate() (where the master tells us if a task finished, failed, etc.).  As the scheduler, our job in resourceOffers() is to identify which agents we want to do work and then give the master a task to execute on that agent.  This task can be something simple like a command line thing to run or we can provide Mesos with a custom executor to do something crazier.  There is a one-to-one correspondence between a task that the scheduler creates and an agent (i.e. I can't launch a task across agents).  When the command that's running in a task finishes, the resources that task was using will become available again (via another call to resourceOffers()).

Mesos runs these tasks with a certain amount of isolation (you may want to run multiple tasks on a single agent and Mesos is trying to make sure they're really limited to the resources that the scheduler says they should get, though in my case I'll be using all CPU and mem on the agent for a single task anyhow), but I confirmed today that using their basic built-in command-line executor, I can create a command-line task that does an mpirun, listing IP addresses of multiple agents, and this will execute just fine from inside the Mesos containerizer.

I would like my scheduler to be as dumb as possible... it's going to be executing lots of different applications (some MPI-based, some that just run on a single machine), and so I'd like it to not even know it's running an MPI job.  I've got an abstraction layer that I can hide this behind, but for our purposes this boils down to that I'd like to make the mpirun call on one of the agents (as opposed to the scheduler itself) if at all possible.

So with these constraints... inside resourceOffers(), I'll have a list of all available agents and their IP addresses.  I can easily create a task on one of them which has the full list of IP addresses and does the actual mpirun.  When mpirun finishes, that task is done, that agent's resources are available again, and I'm good.  So the only trick is that I need some kind of dummy tasks running on all the other agents that MPI is going to connect to so that Mesos realizes those resources are in fact being used... otherwise I'm going to overbook my agents.  I basically want a task that is going to start up right away, wait around for the main agent to kick off the mpirun, and then end when the MPI task is finished (which I think equates to the orted task completing in Open MPI's case); it should also have some kind of timeout and fail if the main agent never makes that connection.

I could implement a kludgy dummy task which would watch for the orted process and end when it sees that process go away... I can envision lots of race conditions when the timing of that doesn't work out quite right.

I could implement a socket-based approach where I basically roll my own custom layer on top of Open MPI.  The main agent starts up, listening on a socket, waits for all other agents to connect with him on that socket, so then he knows all the Mesos tasks have started, and then he does the mpirun.  When that command finishes, he can send another socket communication out to the other agents to tell them they can also exit.  This wouldn't be super complicated to do but it would be nice if there was a more elegant way.

I think logically what I want is a way to have Mesos start orted on those other agents in some kind of mode that it's expecting the main agent to make a connection with it... when mpirun on the main agent starts and it ssh's into those other agents, it would see orted already running and make a connection with it (it's no problem for the other agents to know the IP address of the main agent if that helps).  Then my Mesos task can simply wait for the orted process to exit.  I think this is more or less what you were saying in your earlier post too.

I didn't mean to turn this into a novel but wanted to spell out all the details. :o)  I appreciate any thoughts you have on this.

**Comment by rhc54** [comment]
I'm honestly not sure I follow all that, but the sequence of events is pretty simple. You have to start mpirun first and find a way to communicate to it how many nodes you will be using. This is done in the orte/mca/ras framework, so you'll need a "mesos" component there. Once we have that info, you then move to the next stage of "launching" the orted's, one per node. In this case, you are going to use Mesos to start those orteds, and so you will need another "mesos" component in the orte/mca/plm framework.

The daemons are given the mpirun contact info on their cmd line, and so they will phone home as usual. You'll need to add some info to that callback message - e.g., you'll need local connection info since the orted won't be spawning the local procs. Once the daemons have all been launched and connect back, mpirun can compute the process map. Your plm/mesos component can then launch the application by using Mesos to start each process on its designated node, passing to each process the info required for it to connect to its local daemon.

Where things get tricky again, however, is in detecting process termination. Since the orteds won't have spawned the local procs, it can't detect when they terminate. We'll have to give that some thought as the entire job completion logic depends upon it.

**Comment by rhc54** [comment]
Please reopen if you intend to work on this or run into issues.
