### ISSUE TITLE
MPI_Comm_create performance

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#3368]
## Background information
We observing performance problems related to `MPI_Comm_create()` in Amber app (http://ambermd.org/).

### Open MPI version
v1.10, v2.x, and I believe others as well

## Reproducer
To ease problem resolution I've created simple reproducer that can be found here:  https://github.com/artpol84/poc/tree/master/benchmarks/comm_create.
I was doing my evaluations on 1K procs and the pattern of Amber in my case was creation of lots of small communicators (3 procs per comm), see https://github.com/artpol84/poc/blob/master/benchmarks/comm_create/pattern.h for the detailed info about what ranks are in each communicator.
**NOTE**: that you need to run this repro on at least 1024 procs unless you modify pattern.h  (now it will try to create comm using ranks up to 1K).

## Root cause
While investigating this problem I found that the algorithm used in OMPI has real problems with this pattern: OMPI took ~100 times more time compared to MPICH to execute my benchmark.
Currently OMPI uses the following algorithm for `MPI_Comm_create` (I'm listing only relevant 
steps):
```
0. start = lowest_local_CID; // lowest locally available Comm ID (CID)
1. local_next_cid = next_free_CID(start); 
2. nextcid = Allreduce(old_comm, local_next_cid, MPI_MAX)
3. if( !LOCALLY_USED(nextcid) ){
       local_response = 1;
   } else {
       local_response = 0;
   }
4. response = Allreduce(COMM, local_response, MPI_MIN)
5. if( 1 == response ) {
	goto 6;
   } else { 
        start++; 
        goto 1;
   }
6. new_comm->CID = nextcid;
7. Done
```
I did the profiling and found that for the provided pattern number of iterations of this algorithm is constantly growing. It ended up doing **479 iterations for 1079'th** `MPI_Comm_create()`.
To verify the best perf that we can achieve I hacked OMPI v1.10 as follows: 
https://github.com/artpol84/poc/blob/master/benchmarks/comm_create/ompi_hack.patch

## Measurements
Here are relative numbers that I've collected with this benchmark:
* MPICH - 1 (assume MPICH time as 1)
* OMPI/orig - 106 ( `time(OMPI/orig) / time(MPICH)` )
* OMPI/hack - 1.65 ( `time(OMPI/hack) / time(MPICH)` )
So although OMPI is slower, numbers are at least comparable.

## Future work
I've created experimental PR https://github.com/open-mpi/ompi/pull/3367 to study the ways of improving the algo.

## v1.10 vs v2.x
I also noticed that starting from v2.x we use non-blocking version of nextcid, it is not clear how it can improve things as `MPI_Comm_create()` is blocking and there is a wait anyway.
From the perf perspective v2.x is about 1.2 times slower than v1.10.

**Comment by rhc54** [comment]
Just a random thought: if you are concerned about comparing MPICH times to OMPI, then why not just "port" their algorithm to OMPI?

**Comment by artpol84** [comment]
This is one of the things to try in experimental PR.

**Comment by artpol84** [comment]
MPICH does the reduction on the bit-vectors to locate available CID's.

**Comment by edgargabriel** [comment]
not objecting to improvements, just wanted to add the reminder, that the original algorithm was chosen since it also works in multi-threaded scenarios, e.g. multiple threads executing a comm_dup or comm_create on different communicators simultaneously.

**Comment by artpol84** [comment]
Yeah, I found that this algo is in OMPI from the start :) 536c2795290debd0ab6ffee4d7e02040e6bda084. @edgargabriel I noticed that you were working a lot with it.
It seems like MPICH code also has thread-safety (at least it is mentioned there):
https://github.com/pmodels/mpich/blob/master/src/mpi/comm/contextid.c#L400:L401

**Comment by artpol84** [comment]
@edgargabriel 
https://github.com/open-mpi/ompi/commit/536c2795290debd0ab6ffee4d7e02040e6bda084#diff-988cb1deb1a056196293388ca1b9bfb7R92

Do you know what "docs" are mentioned here?

**Comment by edgargabriel** [comment]
There was a design document in the early days of Open MPI that described the algorithm, but I have no idea where that is. I recall one of the other Open MPI members (Tim Woodall I think) who brought  the algorithm up, claimed that it was theoretically proven to be correct in multi-threaded scenarios.

I also recall a presentation by the MPICH group at one of the EuroMPI conferences about thread safety of CID allocation. Without remembering the details, I *think* our algorithm was a bit more generic.

**Comment by artpol84** [comment]
I just verified that PR #3367 completely solves the problem for Amber.
@edgargabriel can you please review and comment? If it is OK, I will open PR's to master and all other threads to preserve our usual workflow.

**Comment by bosilca** [comment]
One major difference in Open MPI is that we allow for as many communicator as necessary, without the need to recompile the library to set a new upper bound. However, the algorithm as described above is not the one that has been implemented in OMPI originally. In the original version if the first iteration failed, we continue the loop from the result of the first Allreduce (start = nextcid+1 instead of start++). I don't know when it has been changed, but in 2015 we did a paper about allocating CID (we used OMPI r32795). If you want to take a look at the paper ping me offline.

The latest algorithm from MPICH does a bitwise reduction to find the next available spot, an algorithm that is thread safe (as described in their paper), but it needs a known upper-bound. Thus, we cannot simply port their algorithm in OMPI.

**Comment by artpol84** [comment]
George,  i think I mistyped in my pseudo-code. Indeed it should be nextcid + 1. I'll 2-check.

**Comment by artpol84** [comment]
That is correct - typo in pseudo code 

https://github.com/open-mpi/ompi/blob/v1.10/ompi/communicator/comm_cid.c#L313

**Comment by rhc54** [comment]
If we wind up iterating so many times, wouldn't it be faster to just have everyone send to MCW rank=0 and let that rank be the "master" CID assigner? Now that we have async progress, it would seem like that should work and it would have to be faster than all these iterations.

Just have the rank=0 of the new communicator send the request along with all participating proc IDs, and then have MCW rank=0 bcast the results to all. One iteration and you are done.

**Comment by artpol84** [comment]
@rhc54 note, that each rank has it's own range of available and busy CID's. rank = 0 doesn't have the info for every rank. Sending all ranges will introduce significant overhead. If we not sending all the ranges - we will end up doing the same as we do now, but rank = 0 will be a bottleneck.

**Comment by rhc54** [comment]
Your statement is only true because of the way we currently do it. There are two possible methods - one that has every rank maintaining its own CID list and therefore requires multiple iterations to achieve consensus, and another that has a "master" CID list for the entire job and requires that the procs wanting to create a communicator contact the "master" to obtain the next available value.

If the algorithm requires multiple iterations to converge on an available CID, then the centralized approach is quite likely to be faster. When we didn't have async progress, you couldn't do this because MCW rank=0 would only service its recv's when the application dipped into the library. However, that is no longer true. Yes, the centralized approach will slow down if thousands of communicators are being created at the same time, but that is by far the oddball case - and any application that poorly designed deserves it to be slow.

My only point here is to get folks to broaden their thinking - we tend to get too locked in to the current design and spend tons of time (and many, many iterations) trying to bandaid it. Another approach might be worth considering.

**Comment by artpol84** [comment]
That is fine.
However worth mentioning:
* with PR #3367 number of iterations was reduced down to 1-2.
* I have doubts that 1K ranks going to rank = 0 asking for a communicator will be scalable. 
* In the case of simultaneous Comm creation you will need the way on rank = 0 to distinguish between requests. And it sounds tricky because at this stage they obviously doesn't have CID yet - this is the reason they came with the request.
* Our recent research shows that CPU sharing is a tricky task. I'm not familiar with the async implementation yet, I guess it is implemented using service thread. Then given that opal_progress doesn't call sched_yield by default - it is highly likely that you will get significant delays until this service thread will finally get CPU from the main thread.

The application we were working with is quite common. And given that other MPI implementations handle it correctly I don't agree with your argument about "application that poorly designed deserves it to be slow".

**Comment by rhc54** [comment]
@hjelmn @bosilca @artpol84 @edgargabriel Given that different algorithms are possible, and that there may be variations in performance depending on size and application, would it make sense to implement the next_cid function in a framework? I'm just asking as it sounds to me like there may be room for investigation here, and that is what frameworks are for.

@artpol84 I think you misunderstood what I suggested. In the approach I laid out, only one process sends a message to MCW0 that contains the identifiers of all procs participating in the new communicator. MCW0 receives that message, increments the CID counter, and bcasts that value to all the procs in the new communicator.

Thus, the "next_cid" operation will _always_ consist of a single message to MCW0 plus a bcast to all members of the new communicator. Simultaneous creation is easily handled by using the identifiers of all the involved procs as a "signature", just as we do in the ORTE collectives. I don't believe any of the proposed algorithms can distinguish between simultaneous attempts to create a communicator involving the exact same participants, yes?

Even doing this over OOB instead of MPI yields very fast results, so that would be an option. Or one could do it over PMIx, I suppose.

Anyway, it was just a suggestion to illustrate an alternative approach that never gets into multiple iterations. If we go the framework route, it might enable such investigations.

**Comment by ggouaillardet** [comment]
@rhc54 i think i also misunderstand your suggestion.

here are my 0.02 US$

each MPI task has its own list of used and available CID, and iirc, orted/mpirun is not involved.
(e.g. this is a fully distributed process, with all tasks being equal)
so unless you suggest rank 0 of ```MPI_COMM_WORLD``` is always involved, i do not see how that can work (and this has other implications if rank 0 is not part of the communicator creation)
at first, i'd rather involve ```orted/mpirun``` and have them manage which local task is using which set of CIDs, so we hopefully reduce the number of steps before every task can agree on the lowest common unused CID. (and obviously, orted/mpirun could delegate this to PMIx)
in order to handle the multithreaded case, i think we have to add the CID of the parent communicator to the signature, for example
```c
MPI_Comm_dup(MPI_COMM_WORLD, &comm1);
MPI_Comm_dup(MPI_COMM_WORLD, &comm2);
thread1: MPI_Comm_dup(comm1, &comm3);
thread2: MPI_Comm_dup(comm2, &comm4);
```
that is a bit convoluted, but i believe this is legit, and the last two ```MPI_Comm_dup()``` have the same signature if it is only based on MPI tasks.

we could also optimize by mimicking mpich. allreduce a bitmap of used CIDs. start with a reasonnable bitmap size, and try again with a bigger size if the used CIDs do not fit the bitmap.

**Comment by rhc54** [comment]
@ggouaillardet I think you missed one key point. We keep getting hung up on this design point that "each MPI task has its own list of used and available CID". This isn't a requirement - it was a design decision made many years ago, and it may not be correct.

So let's look at it a different way. Each task has a list of CIDs to which it belongs. There is (somewhere) a global "master" that allocates CIDs. If a group of procs wants another CID, it selects a "leader" (a very simple algorithm of taking the lowest jobid/vpid will suffice since it doesn't matter who does it) to contact the "master" on behalf of the group. The "leader" sends the "master" a request that includes the list of all procs involved in the request. The "master" increments the global CID and then bcasts that value to the group that requested it.

There is no need for the "master" to be involved in the requested communicator - it is simply executing a very short task on behalf of the group.

We could imagine further. Suppose we have the RM "hold" the counter for us. Now no application proc need act as the "master" - we can just ask the RM to "increment and return" the counter, which we use as a CID (the RM doesn't need to know the purpose of the counter, and hence doesn't need to understand the concept of a CID). If the job is launched via mpirun, then mpirun can act in that role.

Again, I'm not pushing any particular idea. What I'm trying to do is challenge this thinking that it is a _requirement_ that every process have its own notion of the CID counter (which is what is driving all this iterative convergence stuff). This simply isn't true, and it may be that other methods make more sense, especially at different scales...which is why a framework might make sense.

**Comment by ggouaillardet** [comment]
@rhc54 i get your point that any design can/should be reconsidered.

that being said, my first intuition is that the current design is not a bad one.
for example, if we consider a simple program that
```c
MPI_Comm_dup(MPI_COMM_SELF, &comm);
```
currently, there is no communication (or maybe there is but in ```MPI_COMM_SELF``` only, which scales perfectly). if i understand your idea, that would mean n tasks = n leaders = n requests to the master.
regardless the performances (absolute and scalability), a CID is currently a signed integer that is positive, so we are limited to 2 billion CIDs.
one option is to make the CID 64 bits (and assume we will never run out of CIDs), that is bad for binary compatibility, and there might be other side effects.
an other option is to keep an integer and keep __not__ assuming we will never run out of CIDs, then the master must maintain a list of allocated CIDS (worst case scenario is a bitmap of 2 billion bits, which is quite a high memory footprint)

at first glance, a framework is a great idea, so we can experiment and provide options to the end users.

**Comment by rhc54** [comment]
Could be the current design is great - I honestly don't know. For your example, what if the CID was composed of two numbers - a global ID and an intra-comm number? Now Comm_dup could be executed as a single collective across all the members of that specific communicator, telling them all to simply increment the intra-comm ID. You'd only need to go back to the "master" for a global ID.

Like I said, I'm just throwing out ideas here. I just don't want us to fixate on this specific design and ignore other possibilities.

As for tracking CIDs - why would we need to do that? If we make the CID a 64-bit unsigned int, I think we could be comfortable assuming we never run out. If we did, then I'd have to assume someone has a very poorly designed app.

I readily admit that poor design is not an uncommon problem out there - some of the most popular apps are widely considered to be horribly designed. Nobody feels like reworking them, and so we just keep band-aiding the libraries to keep them working (e.g., the coll/sync component). However, this is one where I think we could safely draw a line in the sand.

**Comment by bosilca** [comment]
@rhc54 for scalability reasons we have no luxury to have an MCW0 in the MPI layer. If instead we use the rank 0 for each communicator, we are back on the same issue: how do we coordinate the potential "rank 0" to have a consistent view of the different existing communicators.

There was significant body of research on the topic of creating communicators, and OMPI is not that bad overall. We did however screw it up on this particular example, due to an oversight of the partial communicator creation functionality. But I do think that @artpol84 fix provides a good, and generic, solution in the short run.

**Comment by artpol84** [comment]
#3375 #3376 #3377 #3388

**Comment by jsquyres** [comment]
@artpol84 can you update the tags on this issue?  Should this issue now be closed (i.e., has it been merged everywhere it's going to get merged)?

**Comment by artpol84** [comment]
It's pending for 3.x merge, it was decided not to merge into v3.0.x, but next release.

**Comment by artpol84** [comment]
I don't see any Tag describing post-v3.0.x release.

**Comment by jsquyres** [comment]
I think we have a backwards-incompatible change on master (compared to v3.x -- the datatypes stuff), so go ahead and make a 4.0.x tag.

**Comment by artpol84** [comment]
Closet through https://github.com/open-mpi/ompi/pull/3375
