### ISSUE TITLE
Open MPI detected an unexpected PSM error in opening an endpoint

### ISSUE THREAD

**Issue by adrianreber** [open-mpi/ompi#340]
Since a few days Open MPI does not work with PSM any more on the master branch:

```
n050301:3.0.In PSM version 1.14, it is not possible to open more than one context per process

[n050301:26526] Open MPI detected an unexpected PSM error in opening an endpoint: In PSM version 1.14, it is not possible to open more than one context per process
```

This can also be seen at the MTT result at http://mtt.open-mpi.org/index.php?do_redir=2227

This used to work at least until 2014-12-08: http://mtt.open-mpi.org/index.php?do_redir=2226

This issue has already been partly discussed on ompi-devel: http://www.open-mpi.org/community/lists/devel/2015/01/16765.php

Conclusion so far is, that this is not the expected behaviour and related to the newly added libfabric which also initializes PSM.

A temporary workaround is to specify the MTL to be used with ```--mca mtl psm```.

@afriedle-intel @yburette

**Comment by afriedle-intel** [comment]
Hi,

So the work here is to add some sort of priority mechanism to the MTLs, correct?  I'll volunteer to help out on development if needed.

**Comment by hppritcha** [comment]
Correct.  We need to do something equivalent to the opal/mca/pmix base select method.
I have asked DOE NNSA admins about how often they have MLNX and Intel/Qlogic HCAs together
on the compute nodes - that's my main concern.  Were that to be the case, it would be difficult to 
decide locally in the mtl selection which mtl (mxm, psm) to use.  Fortunately, at least on DOE
systems, that's apparently never the case for production clusters.  I have a very busy schedule for the next several days, but should be able to set up a topic branch with the additions to the mtl base/mxm/psm/ofi/portals4 code to allow for priority selection.  I'd need help with what exactly to put
in to the equivalent of pmix_s2_component_query for something like mxm or psm.  One needs to be careful with what goes on in the query method, otherwise, we'd be in the same situation with 
psm/ofi mtls, where both want to call psm_init.  Something like checking for the presence of the different HCAs via a popen of ibv_devinfo or checking /sys/class/infiniband might suffice.  The fact that, for example, the psm mtl gets built implies that libinfinipath, etc. is present on the build system.

If you'd rather set up the base code in mtl yourself, that's fine.  But seems like at this point you have
a workaround, if you can wait a few days.

**Comment by rhc54** [comment]
Actually, I'm not sure this addresses the problem. The problem isn't priority between MTL components. The problem is that there is a PSM component in the MTL, and another PSM component in the libfabrics code. These are in completely different sections of the code base, and no priority in the MTL framework is going to resolve the conflict.

What you need is a way for the PSM MTL component to indicate "I am active" so that the libfabrics PSM provider can check and say "PSM has already been initialized - ignore me". Or vice versa, depending on which one you want to have active.

**Comment by jsquyres** [comment]
Would it be helpful to have some (PSM) common code that is shared between the PSM MTL and the ofi MTL?  You could ensure to only call psm_init() once, for example.

(disclaimer: I know almost nothing about PSM; my suggestion could be utter nonsense)


> On Jan 19, 2015, at 2:02 PM, rhc54 <notifications@github.com> wrote:
> 
> Actually, I'm not sure this addresses the problem. The problem isn't priority between MTL components. The problem is that there is a PSM component in the MTL, and another PSM component in the libfabrics code. These are in completely different sections of the code base, and no priority in the MTL framework is going to resolve the conflict.
> 
> What you need is a way for the PSM MTL component to indicate "I am active" so that the libfabrics PSM provider can check and say "PSM has already been initialized - ignore me". Or vice versa, depending on which one you want to have active.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by yburette** [comment]
Is there a particular reason for initializing all the MTLs and only picking one? Why not stop as soon as we find one that works?

**Comment by afriedle-intel** [comment]
Jeff -- I was thinking of something like that.  We can track down which PSM call that original error comes from -- psm_ep_open?  And when it returns the error in question, is it too late for whichever component gets that message to disqualify itself?

Yohann, that could work.  Question to anyone though, what is the order in which MTLs are opened/selected?  Perhaps that's where the priority should come in?

**Comment by afriedle-intel** [comment]
OK, I chatted with Yohann for a while and I'm in agreement with his proprosal, without any addition.  Pick the first MTL that works, whatever that may be.  If the user is not satisfied, they can either specify on the mpirun line, in an mca config file, or by removing unwanted MTLs from the installation.

**Comment by jsquyres** [comment]
:+1:

**Comment by adrianreber** [comment]
As a PSM user and not exactly knowing what the plans are with PSM through libfabric on the one side and direct PSM access in Open MPI on the other side I am curious what this means for me as a user.

Is the plan for the future to always go through libfabric for the PSM access or will both access methods be available? About 'pick the first MTL that works': will there be a priority or default PSM access method in Open MPI or will it be random? Can I as user, if I do not specify a certain MTL, expect to always get the same PSM access method? As I know nothing about the technical differences I am just curious what to expect from future releases.

**Comment by afriedle-intel** [comment]
For True Scale, PSM (and corresponding MTL) is and always will be the transport of choice.  If you want the PSM MTL by default, I suggest disabling/removing OFI or setting up an MCA config file to specify PSM.

We are proposing no specific priority among MTLs.  There can only be one MTL active at a time.  Until now, each MTL represented a totally separate network product.  Now we have PSM and OFI.  OFI *might* be running over PSM, but OMPI doesn't know that directly.  How is OMPI supposed to prioritize one over the other?  The answer is that we can't, in general.  Thus the lack of priority for MTLs -- if a user knows something more (or has a preference), they need to specify by selecting a particular MTL via the usual methods.

Another example -- consider a system with both MXM and PSM.  Which should be the default?  How can OMPI know?  Since we can only choose one, and we don't, in general, know the difference, we just pick the first one that works.

**Comment by jsquyres** [comment]
Andrew: I think the point is that it would likely be good if you can enforce that the PSM MTL is chosen over the OFI MTL if no user preference is stated on the command line (e.g., "mpirun a.out").  Right now, it'll be random -- and may even get difference answers on different servers, depending on the filesystem ordering of the PSM and OFI MTL DSOs.  That's no good.

**Comment by afriedle-intel** [comment]
I think there's two problems there -- overall prioritization of networks, and ensuring each process in an MPI job makes the same choice.

Prioritization of networks:  What if a cluster has two networks, let's pick True Scale and Cool-Cisco-network-via-OFI, which theoretically might be faster than True Scale.  How can OMPI know that?  Should we really hardcode a choice of PSM over OFI?  I'm not necessarily disagreeing, mainly stating that I don't see a better solution.

Each process making the same choice:  I don't have an answer.. how is that handled in the existing code?  Right now I believe the last open-able MTL is picked, which isn't good, and leads to psm_init being called twice.

**Comment by jsquyres** [comment]
In the case of usnic, a) we don't support tag matching yet, so it's not an issue for us for the OFI MTL (yet), and b) if/when we do support libfabric tag matching, then it's highly unlikely that you'll be on a machine with both PSM *and* usnic hardware.  Hence, only the ofi MTL will be selectable -- not the PSM MTL.

The issue is currently only on machines with PSM hardware -- because there's 2 possible MTLs that could be chosen for your hardware.

A simple priority scheme would fix the issue.

**Comment by afriedle-intel** [comment]
I retreated and discussed things with Yohann again.  You're right Jeff, we do want a priority scheme, and PSM will have a higher priority than OFI.  I'll volunteer to implement it.  Will need to be careful to have the priority reported up to CM, where it can make a decision on which MTL to use before the MTLs start doing things like psm_init.  OFI will stay out of the way unless specifically requested, and the initial error report is fixed/avoided.

Any further concerns or objections?

**Comment by rhc54** [comment]
You might hit an issue because the OFI code is in the OPAL layer, which means it gets initialized first, before the MPI layer. So you might hit OFI before you get to the MTL's.

**Comment by jsquyres** [comment]
I'll bet you can make the priority be an int member on the component or something.  That way, the MTL base can sort the components by order of priority and query them in priority order.  The first one that works, wins.

**Comment by afriedle-intel** [comment]
Actually, in the long run, we want OFI to be able to report its priority dynamically depending on the underlying priority it would be using.  IE for PSM it'll report a low priority, then if somebody were to have OFI support some faster network, OFI can report a higher priority to take precedence over PSM.

**Comment by afriedle-intel** [comment]
oops: ..priority dynamically depending on the underlying *provider* it would be using.

**Comment by hppritcha** [comment]
Given the way the MCA query method works now, you just want to make sure that however you do 
the query to get the priority, it isn't done in a way that raises an error if a subsequent MTL candidate also needs to use the same method to determine its priority.

**Comment by bosilca** [comment]
Why not simply following an example that worked for a long time? Take a look at how the PML handle this particular case: simple and straightforward. The initialization function (ompi/mca/pml/pml.h:86) returns a priority decided at runtime (thus dynamic) that is used to select the "best". Additionally, as Jeff suggested, moving the initialization code into a common library would completely solve the issue as all MTL will be able to open, but only one will succeed on using the endpoints.

**Comment by afriedle-intel** [comment]
George, that's exactly what I was looking at borrowing from.  The MTL's component_init function will return a priority in a manner similar to the PML design.  mtl_base_select will call component_init on each MTL and select the one that reports the highest priority.  Finally, CM calls component_open for the selected MTL only.

psm_init is called during mtl_component_open, not mtl_component_init.  So, psm_init will only be called once by the selected MTL.  Then, doing initialization in a common library isn't needed.

**Comment by afriedle-intel** [comment]
Sigh, that's not quite right.  Looks like I don't fully understand MCA.

We need one routine that returns a priority like PML component_init.  Then a second routine that does the initialization (calling psm_init).  Need to figure out how to arrange that.

**Comment by hppritcha** [comment]
the MCA has a query method for this stage in the selection process.

**Comment by afriedle-intel** [comment]
I just found that.. you had it covered from the beginning.  So how do the MCA open/register/init/query functions fit together?  Looks like open first, then query OR init to create a module.  Looks like MTL does not define a module_init, but I think we'd want that.  So it'd be open, register, query, then module_init is where psm_init and such goes.  Or is there some other way?

**Comment by hppritcha** [comment]
The first sequence is almost right:

open the framework (good example is in pmi_component_query in ess_pmi_component.c).
The mca_base_framework_open method in pmi_component_query then "registers" the framework
which has the effect of invoking the register method of the components of the framework.
See mca_base_framework.c.  The open methods of the components are then invoked.
For this example, the opal_pmix_base_select is then called, which in turn invokes
the mca_base_select.  This method then cycles through the query method of the components
looking for the ones that return non NULL component modules and an accompanying
priority  The component with the highest priority is picked, and the close method of all of 
the other components is invoked.

I hope this helps.  The pmix mca is a simple example of this.

Note not all mca frameworks act like this - well I guess you already know this. 

Hopefully I'll get time today to test out a basic version of what's needed on the MLNX and
Qlogic systems we have here.

**Comment by afriedle-intel** [comment]
That helps, thanks.  Can you let me know when you have some code I could try out too?

**Comment by hppritcha** [comment]
Certainly.  I'll have a topic branch in my git repo you can check out.
Note this kind of change means we have to change all of the current
MTLs: portals4, mxm, psm, ofi.


2015-01-23 15:51 GMT-07:00 Andrew Friedley <notifications@github.com>:
