### ISSUE TITLE
Open IB deadlocks with coalescing and multiple pending sends

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#343]
When posting a large number of Isend, the application deadlocks when using the OpenIB BTL. The issue is not sensitive to the size of the messages (actually it does deadlock with size=0). It seems to be related to the number of pending sends only. Other BTL are immune to the problem. I have observed that the send sequence numbers and the expected sequence at the receiver are mismatching when the deadlock happens. 

Open MPI trunk rev: 955f3c2730090ea65db5f9328879fcef15881522

The following code illustrates the issue (when nmsg is large enough ~ >= 2000) ;
There are 2 known ways to workaround the issue: 
* Using the MCA option -mca btl_openib_use_message_coalescing false fixes the issue. 
* Blocking sends (as in the ```#if 0``` case) so the problem is only the number of pending sends, not recv). 

```C
        if( rank % 2 ) {
            for( k = 0; k < nmsg; k++ ) {
                MPI_Irecv( &(rb[k*msgsize]), msgsize, MPI_CHAR, 
                           rank-1, 0, comm, &rreqs[k] );                                                                        
            }
            MPI_Barrier( comm );
            MPI_Waitall( nmsg, rreqs, MPI_STATUSES_IGNORE );
        } 
        else {
            MPI_Barrier( comm );
            for( k = 0;  k < nmsg; k++ ) {
#if 0
                MPI_Send( &(sb[k*msgsize]), msgsize, MPI_CHAR, 
                           rank+1, 0, comm );
#else
                MPI_Isend( &(sb[k*msgsize]), msgsize, MPI_CHAR, 
                           rank+1, 0, comm, &sreqs[k] );
#endif
            }
            MPI_Waitall( nmsg, sreqs, MPI_STATUSES_IGNORE );
        }
```

**Comment by ggouaillardet** [comment]
@abouteiller if openmpi is configure'd with --enable-debug, the program crashes with an assertion failure (an item cannot be in two lists at a time)
if v1.8 is tweaked in order to allow the use of coalesced messages, the same error occurs.
this is definitely a bug and i encourage you to disable message coalescing for the time being
@miked-mellanox could you please have someone take care of this ?

**Comment by jladd-mlnx** [comment]
This needs to be addressed by Nathan.

Josh

**Comment by abouteiller** [comment]
Related pull request #332 does not fix this issue.

**Comment by hjelmn** [comment]
@abouteiller We disabled message coalescing in 1.8 because 1) it doesn't work and 2) it provides little/no performance improvement. I may backport my fix to 1.8 if there is a convincing reason to do so.

I will double-check #332 and see why the fix is not working as expected. I pulled the fix out of my BTL 3.0 branch so something might be missing/incorrect.

**Comment by abouteiller** [comment]
I do not think back porting coalescing is useful. Just setting  the default to "off" in trunk until it works as expected is probably fix enough for now.

**Comment by abouteiller** [comment]
My bad, #332 DOES fix the issue.
