### ISSUE TITLE
PSM MTL not handling MPI_Cancel correctly

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#347]
The PSM MTL is not currently handling MPI_Cancel correctly.  George Bosilica supplied a patch in [this thread](http://www.open-mpi.org/community/lists/devel/2015/01/16783.php) on the ompi devel list.

@bosilica

**Comment by jsquyres** [comment]
@yburette Pulling in Yohann as well.

**Comment by bosilca** [comment]
My patch is only partially addressing the issue. A more complete approach seem to emerge from the discussions on the mailing list.

**Comment by adrianreber** [comment]
I tried to disable the error handler provided by PSM on master but master in combination with PSM still seems very broken. Even the workaround decribed in #340 (```--mca mtl psm```) does not help to get PSM working on master with more than one process.

So therefore the following is all on openmpi-v1.8.4-40-ge6cb578:

I extended the patch from @bosilca to look like this:

```
--- openmpi-v1.8.4-40-ge6cb578/ompi/mca/mtl/psm/mtl_psm_cancel.c	2015-01-13 03:19:59.000000000 +0100
+++ openmpi-v1.8.4-40-ge6cb578.new/ompi/mca/mtl/psm/mtl_psm_cancel.c	2015-01-16 10:37:18.026773275 +0100
@@ -37,13 +37,8 @@
     if(PSM_OK == err) { 
       mtl_request->ompi_req->req_status._cancelled = true;
       mtl_psm_request->super.completion_callback(&mtl_psm_request->super);
-      return OMPI_SUCCESS;
-    } else { 
-      return OMPI_ERROR;
     }
-  } else if(PSM_MQ_INCOMPLETE == err) { 
-    return OMPI_SUCCESS; 
   } 
   
-  return OMPI_ERROR;
+  return OMPI_SUCCESS; 
 }
```
In combination with completely disabling the internal PSM error handler
```psm_error_register_handler(ompi_mtl_psm.ep, PSM_ERRHANDLER_NOP);```
I can successfully run ```mpi_test_suite``` which initially triggered the error:
```mpirun mpi_test_suite -t "All,^io,^one-sided"```

In addition I also tried to enable the PSM MTL error handler
```
-- openmpi-v1.8.4-40-ge6cb578/ompi/mca/mtl/psm/mtl_psm.c	2015-01-13 03:19:59.000000000 +0100
+++ openmpi-v1.8.4-40-ge6cb578.new/ompi/mca/mtl/psm/mtl_psm.c	2015-01-16 11:09:22.841141497 +0100
@@ -74,6 +74,8 @@
 			 "unable to open endpoint", true,
 			 psm_error_get_string(error));
 	    break;
+        case PSM_PARAM_ERR:
+	    break;
 
 	/* We can't handle any other errors than the ones above */
 	default:
@@ -154,9 +156,6 @@
       return OMPI_ERROR;
     }
 
-    /* Future errors are handled by the default error handler */
-    psm_error_register_handler(ompi_mtl_psm.ep, PSM_ERRHANDLER_DEFAULT);
-    
     err = psm_mq_init(ep, 
 		      0xffff000000000000ULL, 
 		      NULL,
@@ -342,10 +341,7 @@
 	rc = OMPI_ERROR;
     }
     else {
-	/* Default error handling is enabled, errors will not be returned to
-	 * user.  PSM prints the error and the offending endpoint's hostname
-	 * and exits with -1 */
-	psm_error_register_handler(ompi_mtl_psm.ep, PSM_ERRHANDLER_DEFAULT);
+        psm_error_register_handler(ompi_mtl_psm.ep, ompi_mtl_psm_errhandler);
 		
 	/* Fill in endpoint data */
 	for (i = 0; i < (int) nprocs; i++) { 
```
Now the PSM internal error handler is not enabled as default error handler and Open MPI's PSM MTL error handler can now additionally handle ```PSM_PARAM_ERR``` (by ignoring it) which disables aborting of PSM due to a failed cancel. So ```mpi_test_suite``` is happy with this change but I do not know which other error cases I am ignoring with this change.

**Comment by bosilca** [comment]
The difference between the original patch and the updated version makes the new version less safe. This version returns OPAL_SUCCESS even in cases where the PSM considered the request as broken, and this is not what we want. I would stay with the original patch plus the second one.

**Comment by adrianreber** [comment]
Unfortunately the original patch does not work. I get the following trying to MPI_Cancel():

```
[n050409:23181] *** An error occurred in MPI_Cancel
[n050409:23181] *** reported by process [47690379165697,1]
[n050409:23181] *** on communicator MPI_COMM_WORLD
[n050409:23181] *** MPI_ERR_OTHER: known error not in list
[n050409:23181] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[n050409:23181] ***    and potentially your MPI job)
[n050409:23180] *** An error occurred in MPI_Cancel
[n050409:23180] *** reported by process [47174983090177,0]
[n050409:23180] *** on communicator MPI_COMM_WORLD
[n050409:23180] *** MPI_ERR_OTHER: known error not in list
[n050409:23180] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[n050409:23180] ***    and potentially your MPI job)
```

**Comment by afriedle-intel** [comment]
Sorry for the delay, was swamped last week.  PSM doesn't support cancellation of sends at all.  How about this?

```
--- a/ompi/mca/mtl/psm/mtl_psm_cancel.c
+++ b/ompi/mca/mtl/psm/mtl_psm_cancel.c
@@ -30,7 +30,12 @@ int ompi_mtl_psm_cancel(struct mca_mtl_base_module_t* mtl,

   mca_mtl_psm_request_t *mtl_psm_request =
     (mca_mtl_psm_request_t*) mtl_request;
-
+
+  /* PSM does not support canceling sends */
+  if(OMPI_MTL_PSM_ISEND == mtl_psm_request->type) {
+    return OMPI_SUCCESS;
+  }
+
   err = psm_mq_cancel(&mtl_psm_request->psm_request);
   if(PSM_OK == err) {
     err = psm_mq_test(&mtl_psm_request->psm_request, &status);
```

I think the above will fix the cancel problem independently of the error handler issues.  Using the OMPI level error handler instead of PSM's is probably a good thing, though PARAM_ERR shouldn't be ignored.

**Comment by adrianreber** [comment]
Patch from @afriedle-intel solves the error for me.

**Comment by hppritcha** [comment]
Okay, I'll apply the patch in a PR unless there are objections to afriedle's solution.

**Comment by afriedle-intel** [comment]
OK, unless anyone objects I'll commit to master and submit a pull request to 1.8 later today.

**Comment by afriedle-intel** [comment]
oops :) missed Howard's comment.  Go for it Howard.
