### ISSUE TITLE
Undefined symbol "mca_mpool_base_page_size" on FreeBSD

### ISSUE THREAD

**Issue by daniloegea** [open-mpi/ompi#3479]
## Background information

I'm using the OpenMPI 2.1.0 on the FreeBSD OS and I'm getting the warning bellow when I execute the binary with mpirun:

```
[danilo@capeta /tmp]$ /usr/local/mpi/openmpi2/bin/mpirun -n 2 ./hello
[capeta:97965] mca_base_component_repository_open: unable to open mca_mpool_grdma: /usr/local/mpi/openmpi2/lib/openmpi/mca_mpool_grdma.so: Undefined symbol "mca_mpool_base_page_size" (ignored)
[capeta:97966] mca_base_component_repository_open: unable to open mca_mpool_grdma: /usr/local/mpi/openmpi2/lib/openmpi/mca_mpool_grdma.so: Undefined symbol "mca_mpool_base_page_size" (ignored)
Hello world from processor capeta, rank 0 out of 2 processors
Hello world from processor capeta, rank 1 out of 2 processors
```

I'm seeing this on OpenMPI 2.1.1rc1 as well.

**Comment by jsquyres** [comment]
Does this apply?

https://www.open-mpi.org/faq/?category=building#install-overwrite

**Comment by daniloegea** [comment]
Not really, I'm using a fresh installation here.

**Comment by jsquyres** [comment]
This specific warning almost always occurs when an Open MPI installation tries to open a plugin from a different version of Open MPI.  In itself, the issue is harmless (because Open MPI is just telling you that it unexpectedly failed to correctly open a plugin, and therefore it ignored that plugin), but it usually indicates some other kind of error -- usually that you're either not running the Open MPI installation that you thought you were running, or that the Open MPI install that you're running is somehow seeing more / other plugins than it expects to (i.e., it's somehow finding / trying to use plugins from a different Open MPI installation).

This must be what is happening somehow, because there is no mpool/grdma plugin in the v2.1.0 series.  The mpool/grdma plugin was last included in the v2.0.x series.

Hence, if you're getting that warning, then somehow you are accidentally mixing Open MPI installations.

**Comment by daniloegea** [comment]
Hmm, that's embarrassing, you are right, I made some confusion with my scripts here... I'm sorry for the noise...

**Comment by jsquyres** [comment]
Glad you figured it out!  Good luck.
