### ISSUE TITLE
disable getpwuid by default on Cray?

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#352]
Would there be a reason not to disable getpwuid by default on Cray?

**Comment by rhc54** [comment]
Not really - it is necessary that you do so for static builds on a Cray due to their libc implementation.

**Comment by marksantcroos** [comment]
And in the dynamic scenario the warnings are not very productive either ...

**Comment by hppritcha** [comment]
Hi Mark,

Unfortunately this is not so simple for several reasons.  First, the place
where getpwuid is used currently in OMPI
is in a platform independent section of code.  Just putting in an

#ifndef __CRAY_SYSTEM
do the getpwuid stuff
#endif

would not likely go over very well.

Also, you are using the NERSC systems, where ldap or similar user
authentication mechanism is not
extended to the compute nodes by default.  However, if you are using CCM,
then LDAP service is enabled
and there may be a use case for the session_dir mechanism.  Also, some
smaller XE/XC systems do
have ldap, etc. on the compute nodes, so maybe they want to use getpwuid
too.

This behavior can be controlled by an ORTE MCA parameter.  You can, for
example, add the following line

orte_create_session_dirs = 0

to your ${HOME}/.openmpi/mca-params.conf

file and it will disable session dir for all your open mpi jobs.

For this option, I think this is the way to go since its both site, and
potentially user specific setting.

Hope this helps,


Howard




2015-01-19 15:03 GMT-07:00 Mark Santcroos <notifications@github.com>:

**Comment by rhc54** [comment]
I'm confused, Howard. We ensured that systems (regardless of Cray or otherwise) would work just fine if you configure with --disable-getpwuid. If you have found some reason why that no longer works, please let me know. I think Mark's question was more "why not define disable-getpwuid in the Cray configury". I can think of no reason why you wouldn't as it doesn't disable anything in the system.

**Comment by hppritcha** [comment]
As I said in the issue, on some customer configs it may be useful to have
the sessions_dir mechanism set up.
Indeed, I use one precisely set up with LDAP on the compute nodes and can
use the sessions dir stuff without
a problem.  There also may be reasons why, if we get OMPI working with CCM
mode on Cray, that those
users may want to use the sessions_dir cap as well.  So I see this as a
user/site specific thing to see via
the MCA params thing.

Note the static linking issue is different.  For those wishing to use
static linking with ompi, the sys admins
should indeed configure with --disable-getpwuid.

So I think the current way things are handled is the best.  Users wanting a
non-standard build can put
--disable-getpwuid on the configure line to avoid warning messages when
doing static linking.  Admins
who by default don't project LDAP out to compute nodes can set the MCA
param in a system wide
params file.

I'm not sure who was doing the ensuring.  Likely someone only addressing
the static linking issue or
someone who isn't aware of the many ways in which cray systems are being
used by customers.




2015-01-19 17:01 GMT-07:00 rhc54 <notifications@github.com>:

**Comment by marksantcroos** [comment]
> This behavior can be controlled by an ORTE MCA parameter. You can, for example, add the following line orte_create_session_dirs = 0 to your ${HOME}/.openmpi/mca-params.conf file and it will disable session dir for all your open mpi jobs.

FYI: If I do that, then I get the following error:

```
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
```

Anyway, its not a big deal for me, its not too much of a problem to add the `enable_getpwuid=no
` to my build config.

Thanks for the clarification.
