### ISSUE TITLE
Compile error on i386

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi#3680]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

openmpi 2.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Compiling Fedora package

### Please describe the system on which you are running

* Operating system/version: Fedora rawhide
* Computer hardware: i386 and armv7hl

-----------------------------

## Details of the problem

```
/bin/sh ../../../libtool  --tag=CC   --mode=link gcc  -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -finline-functions -fno-strict-aliasing -pthread  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -o opal_wrapper opal_wrapper.o ../../../opal/libopen-pal.la -lrt -lm -lutil   -lhwloc 
libtool: link: gcc -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -finline-functions -fno-strict-aliasing -pthread -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o .libs/opal_wrapper opal_wrapper.o  ../../../opal/.libs/libopen-pal.so -ldl -lrt -lm -lutil -lhwloc -pthread -Wl,-rpath -Wl,/usr/lib/openmpi/lib
../../../opal/.libs/libopen-pal.so: undefined reference to `__sync_add_and_fetch_4'
../../../opal/.libs/libopen-pal.so: undefined reference to `__sync_bool_compare_and_swap_4'
collect2: error: ld returned 1 exit status
```
It appears this started with an update of glibc from 2.25.90-5.fc27 to 2.25.90-6.fc27.  See https://apps.fedoraproject.org/koschei/package/openmpi?collection=f27

**Comment by ggouaillardet** [comment]
@opoplawski i checked the fedora logs and last build was successful. shall i consider the problem as solved ?
fwiw, i noted the successful build refers arch i686 whereas the failed one refers arch i386.

i also noted some errors in the logs caused by the missing ```hostname``` command.
i made #3691 to fix that, and for the time being, i suggest you update your ```openmpi.spec``` file and requires the ```hostname``` package.

**Comment by opoplawski** [comment]
Ah, looks like something got messed up with the Fedora build system for a bit then.  Sorry for the noise.

**Comment by ggouaillardet** [comment]
@opoplawski i was finally able to run into this issue with 32bits ```rawhide```
the issue can be evidenced with this simple program
```c
#include <sys/types.h>

int main(int argc, char *argv[]) {
    int32_t tmp;
    __sync_synchronize();
    __sync_bool_compare_and_swap(&tmp, 0, 1);
    __sync_add_and_fetch(&tmp, 1);
    return tmp;
}
```
because it has unresolved symbol.
note the issue only occurs with ```-march=i386```
(e.g. it is fine with ```-march=i686```)


i will improve atomic detection to trap this, but i am not sure how this will help you.
if you configure with ```--enable-builtin-atomics```, then ```configure``` will abort when ```CFLAGS=-m32 -march=i386``` unless an external library can be used to provide the unresolved symbols (and i am not aware of such a library).
that means that from a fedora point of view, you either have to
- __not__ use ```--enable-builtin-atomics``` on ```i386```
- build Open MPI only for ```i686```
- add the requested library (if any) to the ```LDFLAGS``` (or teach me what this library is, and i will try to autodetect it in ```configure```)

unless there is an external library that can be used, i am thinking this is really a ```gcc``` bug, it should not generate call to symbols that are known not to exist.

**Comment by ggouaillardet** [comment]
@opoplawski it turns out the fix was already available but not yet backported to the ```v2.0.x``` branch
this is now done in open-mpi/ompi#3758

**Comment by rhc54** [comment]
@opoplawski Quick question that isn't fully relevant here. I seem to recall you saying something about no longer packaging OMPI against the external libevent because the system libevent version had moved to 2.1.8, and there was some concern about OMPI being able to build/run against it. Is that an accurate memory?

I'm asking because I just tested OMPI against libevent 2.1.8 and it built/ran fine, so I'd like to understand if you encountered some other problem that I'm missing.

**Comment by opoplawski** [comment]
@rhc54 There were some run time issues with using the system libevent.  See https://bugzilla.redhat.com/show_bug.cgi?id=1235044 for one.

**Comment by rhc54** [comment]
I see - actually, that was due to an issue in our IO forwarding code that had nothing to do with libevent itself. We fixed the internal problem, so I expect this is no longer an issue.

**Comment by rhc54** [comment]
@opoplawski I know this is from long ago, but we were meeting this week and discussed the libevent situation. We concluded that we will upgrade internally to v2.1.8, and set our external minimal accepted level to the same. This won't take affect until v4.0.

However, we also checked OMPI v3.0 and v3.1, and both appear to build and work correctly against libevent v2.1.8.

HTH
