### ISSUE TITLE
Static linking on master broken on OS X

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#375]
If you `./configure --enable-static --disable-shared` on OS X, you get:

```sh
$ make
...snipped...
Making all in tools/wrappers
  CC       opal_wrapper.o
  SED      opal_wrapper.1
  CCLD     opal_wrapper
Undefined symbols for architecture x86_64:
  "_opal_pmix", referenced from:
      _opal_get_proc_hostname in libopen-pal.a(proc.o)
```

**Comment by jsquyres** [comment]
I found a fix, but I don't remember *why* this fixes it.  @goodell @hjelmn I seem to remember discussing a similar issue with at least one of you in the past...  Do you know why this works?

The issue in question is https://github.com/open-mpi/ompi/blob/master/opal/mca/pmix/base/pmix_base_frame.c#L29, which is:

```c
opal_pmix_base_module_t opal_pmix;
```

As you would expect, this is a struct of function pointers.  It's properly DECLSPEC'ed and extern'ed in pmix.h.

In pmix_base_frame.c, there is executable code in addition to this global declaration -- but all the functions are static, and referred to by another function table struct instance in the file (i.e., the framework instance).

I'm *guessing* that this is the same old problem we've seen before: when static linking, since OS X sees no public function symbols in this file, it doesn't actually make the `opal_pmix` globally available properly (I don't remember if it doesn't link in the symbol, or doesn't execute it during bootstrapping or what... but the end consequence is that linker errors like this occur).

So if I add a little "publicly executable code" in pmix_base_frame.c, it makes the link problem go away.  For example:

```c
opal_pmix_base_module_t opal_pmix = { 
    .init = (opal_pmix_base_module_init_fn_t) NULL
};
```

I.e., just do a meaningless initialization of one of the members of `opal_pmix`, and all is good -- the linker problems on OS X disappear.

_However_, I don't understand why this doesn't happen elsewhere.  For example, [btl_base_frame.c](https://github.com/open-mpi/ompi/blob/master/opal/mca/btl/base/btl_base_frame.c) has a very similar structure:

* Several global variables
* All functions in the file are static

But the global variables in btl_base_frame.c don't exhibit these same linking problems.

Why?

Is the "initialize a meaningless value in the `opal_pmix` struct" method the correct solution?  If so, what makes this different from the BTL base frame?  Is it perhaps because the BTL base frame globals are not structures, but rather intrinsic types (bools, char*s, etc.)?

**Comment by goodell** [comment]
I think `opal_pmix` is ending up as a common symbol when you don't initialize it and OS X doesn't treat common symbols the same way that Linux does.  The MPICH "style checker" actually has a check for this because it can be a problem in other situations.  What do you get back from `nm pmix_base_frame.o | grep opal_pmix` without your "publicly executable code" fix?

**Comment by jsquyres** [comment]
When I compile without the initialization, I get:

```sh
$ nm base/pmix_base_frame.o | grep 'opal_pmix$'
0000000000000098 C _opal_pmix
```

When I compile with the initialization, I get:

```
$ nm base/pmix_base_frame.o | grep 'opal_pmix$'
0000000000003cf8 S _opal_pmix
```

You're right -- C = "symbol in common section", and S = "symbol in other section than those listed above".

I don't know the implications of those two sections, other than "C = doesn't link properly, S = links properly."

Is the initialization the correct fix?

**Comment by goodell** [comment]
> Is the initialization the correct fix?

Yes.

When in doubt, avoid common symbols, especially on OS X.  Apple has some info about this (the link will surely become stale at some point, they always do that): https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/executing_files.html#//apple_ref/doc/uid/TP40001829-98432-TPXREF120

**Comment by rhc54** [comment]
Is there some easy-to-understand way to recognize that we created a
"common" symbol? This error seemed rather arcane as the difference is
really tiny and not obvious.

I suppose one option is to just say "always include an initialization for
every non-stack object"?

**Comment by goodell** [comment]
> Is there some easy-to-understand way to recognize that we created a
"common" symbol? This error seemed rather arcane as the difference is
really tiny and not obvious.

I agree this is surprising behavior to most C programmers, since the difference only crops up on certain platforms and then only when dealing with more complicated software projects.  However, there are easy source-level checks and object-level checks that we could add to our build process to help us catch these.

For GCC (and many other compilers) we can add `-fno-common` to the compiler flags.  This will prevent this behavior.  But I don't know if that flag is universally supported, so you could still end up with a case where you built with compiler that doesn't support said flag and the target platform's linker misbehaves in the presence of common symbols.  Not to mention we occasionally are required to emit common symbols so that we can interoperate with Fortran, which relies on common blocks because it's horrible.

> I suppose one option is to just say "always include an initialization for
every non-stack object"?

Yep, that's the MPICH policy.

**Comment by rhc54** [comment]
I can live with that as a policy. Might be interesting to see if we can
detect and add compiler-level help without fighting with fortran as we'll
inevitably forget again.

Thx!

**Comment by hzhou** [comment]
> > I suppose one option is to just say "always include an initialization for
> > every non-stack object"?
> 
> Yep, that's the MPICH policy.

(Revisiting this issue as it is still haunting us) I have to say, that is a HORRIBLE policy. I am more amenable to the `-fno-common` solution. If a compiler emits common symbols and mess up the linking and offers no flags to switch off, that is a bad compiler. Fortran compilers are exempt due to language design. C compilers have no excuse.
