### ISSUE TITLE
README: update to indicate aarch64 is not currently supported

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3855]
The Open MPI project currently lacks resources/interest to actively support aarch64.  This needs to be updated in the README.

**Comment by ggouaillardet** [comment]
@hppritcha fwiw, i build Open MPI on my raspberry pi 3 running Open SuSE Leap 42.2 once in a while, and so far, i have no issue with it (i test is very lightly though).
i am concerned stating bluntly "Open MPI does not support ARM 64bits" is both strong and could be misleading (some vendors have such plans, @kawashima-fj can you confirm post-K (Fujitsu/Riken co-designed ARM64 based processor) will use Open MPI ?)

**Comment by jsquyres** [comment]
https://github.com/open-mpi/ompi/issues/3697#issuecomment-312787357 is a good summary of the current status of ARM v8 support in OMPI v2.1.x (I assume it's similar in v2.0.x) and 3.0.0rc1.  The consensus in the room yesterday is that if ARM is going to move to be a supported platform, we *need* regular testing results in MTT.

**Comment by bwbarrett** [comment]
Yes, but @ggouaillardet raises a good point.  We don't actually document what's not supported.  We document what's supported and what's known not to work.  It's a subtle distinction, but one we should follow here.  aarch64 is already not listed as a supported platform.  What we need to do is document the known issues with the platform, so that others aren't surprised by them.

**Comment by shamisp** [comment]
Description in https://github.com/open-mpi/ompi/issues/2643#issuecomment-315060160 
is not accurate.

We have been responding on both issue (reflected in tickets). The issues are not easily reproducible since it depends on multiple factors, including ARMv8 implementation (multiple vendors), drivers, compiler, etc.  In some case we directly approached people for remote access, but we understand it is not always possible. 

Besides this, some of these problem not ARM specific and have been reported on other platforms, like PPC. Moreover neither of issue was reported as a blocker.

In terms of MTT - we are working to enable this and this takes time. In addition, we proactively added OMPI Jenkins build node with IB to HPCAC center for OpenMPI testing in public domain. As for now, it has some stability issues (related to OS) but we have been working to address this. 

More reasonable approach is to list some of the know issue in know bug section (including precise platform description, since there are multiple ARMv8 implementations).
