### ISSUE TITLE
configure yoinks in the presence of libfabrics

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3989]
As part of Paul's testing of 3.0.0rc2, he reports yoinks:
```
I have an x86 Linux system where configuring Open MPI 3.0.0rc2 yields:

configure: WARNING: lib fabric requires both libnl v1 and libnl v3 -- yoinks!
configure: WARNING: This is a configuration that is known to cause run-time crashes
configure: error: Cannot continue

I am happy to disable libfabric support to test this system.
However, if there is info somebody wants/needs to collect from this system let me know.
```
He reported this on the mail list:
https://www.mail-archive.com/devel@lists.open-mpi.org//msg20324.html

**Comment by jsquyres** [comment]
@hppritcha I'm not sure why you're assigning this to me -- this is a user error...?

**Comment by jsquyres** [comment]
@PHHargrove This error means that your libfabric is apparently dependent upon both libnl1 and libnl3, which means it will likely crash if you try to use it.  You can confirm/deny this by running `ldd` on your `libfabric.so` and see if it lists both libnl and libnl3 libraries.

**Comment by PHHargrove** [comment]
I can confirm what @jsquyres says:

```
$ ldd /usr/lib/libfabric.so
        linux-gate.so.1 =>  (0x0056f000)
        librdmacm.so.1 => /usr/lib/librdmacm.so.1 (0x00eae000)
        libibverbs.so.1 => /usr/lib/libibverbs.so.1 (0x00637000)
        libnl-3.so.200 => /usr/lib/libnl-3.so.200 (0x004bb000)
        libnl-route-3.so.200 => /usr/lib/libnl-route-3.so.200 (0x008b6000)
        librt.so.1 => /lib/librt.so.1 (0x00261000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x00a0e000)
        libdl.so.2 => /lib/libdl.so.2 (0x00419000)
        libc.so.6 => /lib/libc.so.6 (0x00649000)
        /lib/ld-linux.so.2 (0x00288000)
        libnl.so.1 => /lib/libnl.so.1 (0x00d09000)
        libm.so.6 => /lib/libm.so.6 (0x00cdf000)
```

This appears to be the latest for Scientific Linux 6.9 (RHEL clone similar to Centos 6.9)
```
$ rpm -qf /usr/lib/libfabric.so
libfabric-devel-1.1.0-1.el6.i686
```

**Comment by jsquyres** [comment]
In this case, I maintain that Open MPI did exactly what it was supposed to do: it told the user "this won't work -- barf!" (so that Open MPI won't get blamed for the error).

So I'm going to close this issue.

That being said, if Scientific Linux 6.9 is shipping a libfabric built that way, that's a bug in their distro.

**Comment by PHHargrove** [comment]
@jsquyres 

Wouldn't omitting libfabric support be a better behavior than stopping?

Alternatively, wouldn't "try again passing --without-libfabric" be a more useful message than "yoinks!"?

**Comment by jsquyres** [comment]
@PHHargrove What did you pass on your configure line?

**Comment by PHHargrove** [comment]
@jsquyres I passed only `--prefix=[...] --enable-debug`

**Comment by jsquyres** [comment]
@PHHargrove Ah, then *that* does sound like a bug.  Meaning: configure correctly determined that your libfabric is borked.  But if you didn't explicitly `--with-libfabric`, then configure should have just skipped libfabric support (like the way the rest of OMPI handles `--with-FOO` and `--without-FOO` things).  Oops.  I'll open a separate issue to handle that (so that we don't confuse it with what was perceived to be reported on this issue).
