### ISSUE TITLE
Uninitialized ROMIO error_code var in macro

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#404]
As reported by @siegmargross in http://www.open-mpi.org/community/lists/users/2015/02/26345.php, there's a possibility of an uninitialized variable in the ROMIO `MPIO_CHECK_DATATYPE` in adioi_error.h.

@roblatham00 Could you comment on this?

**Comment by ggouaillardet** [comment]
The problem comes from MPIO_DATATYPE_ISCOMMITTED (and is not visible in mpich ...)
```c
#ifdef ROMIO_INSIDE_MPICH
#else /* not ROMIO_INSIDE_MPICH */
/* Any MPI implementation that wishes to follow the thread-safety and
   error reporting features provided by MPICH must implement these 
   four functions.  Defining these as empty should not change the behavior 
   of correct programs */
#define MPIO_DATATYPE_ISCOMMITTED(dtype_, err_) do {} while (0)
#endif /* ROMIO_INSIDE_MPICH */
```
MPIO_DATATYPE_ISCOMMITTED should ideally be redefined by Open MPI
that being said, the default definition should be
```c
#define MPIO_DATATYPE_ISCOMMITTED(dtype_, err_) do { err_=0; } while (0)
```
so there is no use of uninitialized variables.

shall i fix it directly in Open MPI and/or open an issue on the mpich trac ?

**Comment by roblatham00** [comment]
Go ahead and fix in ompi and I'll cherry pick back into mpich. Thanks!

**Comment by hppritcha** [comment]
Gilles please do this commit as PR, I'd like to review it.

**Comment by ggouaillardet** [comment]
@hppritcha @roblatham00 sorry for the delay, the PR is open-mpi/ompi#430
