### ISSUE TITLE
MPI_Reduce() with NULL buffers and zero count

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#4135]
The second call to `MPI_Reduce()` in the snippet below currently errors in master. Maybe just overzealous error checking?

```c
#include <stdlib.h>
#include <mpi.h>

int main(int argc, char *argv[])
{
  int a=0,b;
  MPI_Init(&argc, &argv);
  MPI_Reduce(&a, &b, 0, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);
  MPI_Reduce(NULL, NULL, 0, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);
  MPI_Finalize();
  return 0;
}
```

**Comment by ggouaillardet** [comment]
that is an interesting one !
it fails because on the root rank, ```sendbuf == recvbuf```, and Open MPI would expect ```MPI_IN_PLACE``` here

fwiw, a similar test using ```MPI_Allreduce()``` passes the test because the argument check is
```c
if( (sendbuf == recvbuf) &&
    (MPI_BOTTOM != sendbuf) &&
    (count > 1) ) {
        return OMPI_ERRHANDLER_INVOKE(MPI_COMM_WORLD, MPI_ERR_BUFFER, FUNC_NAME);
}
```

fwiw, i think this test is incorrect
- we should test for both a non zero count, __and__ a non zero size datatype
- if there is data to be transmitted, i think ```MPI_IN_PLACE``` should be used instead of ```MPI_BOTTOM``` in both ```sendbuf``` and ```recvbuf```

@bosilca @jsquyres 
1. should we allow ```MPI_Reduce(NULL, NULL, 0, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);``` ?
2. can you please comment on the ```MPI_Allreduce()``` parameter checks

at least, there should be some consistency between ```MPI_Reduce()``` and ```MPI_Allreduce()``` with respect to this corner-case. but in which direction should we move from now ?

**Comment by bosilca** [comment]
@ggouaillardet I think the test with ```MPI_BOTTOM``` was to make sure that we are not using ```MPI_BOTTOM``` with a count larger than 1. I think the problem with the test is that the first ```&&``` should be a ```||```.

I am not a strong supporter of allowing zero-byte operations to check all possible combination of input arguments. But I have the impression that we had this discussion before and somehow we decided that it should as user-friendly as possible and support all possible combinations.

**Comment by dalcinl** [comment]
BTW, are the following lines in `MPI_Reduce` correct for the case of intercommunicators for processes passng `root = MPI_PROC_NULL`?
```c
    if (0 == count) {
        return MPI_SUCCESS;
    }
```

IMHO, the whole buf error checking is bad, it should be done differently for intra/inter communicators, ignoring the checks for inter with `MPI_PROC_NULL` , rather for all ranks as it is done now.

**Comment by dalcinl** [comment]
@jsquyres This issue is still there in master. IMHO, if count is zero, in any context, then you do not check the buffer address. Why? Because lots of third party code may use NULL pointers for zero-size arrays. Remember that `malloc(0)` may return NULL. Also remember that Open MPI special-case a `MPI_Alloc_mem(0, ...)` call to explicitly return NULL.
