### ISSUE TITLE
Absoft MTT 32 bit build failure on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4146]
Absoft's MTT is showing a 32 bit build failure on master -- linking `opal_wrapper` seems to be looking for a non-existent `opal_cmpset_64` symbol.

See https://mtt.open-mpi.org/index.php?do_redir=2478.

@cagoelz sent the attached full logs, but they apparently don't show much beyond what we see in MTT generated by:

```
$ ../openmpi-master-201708290239-a84af67/configure FC=af90 FCFLAGS=-Z790 "CFLAGS=-g -pipe" --enable-picky --enable-debug --enable-mpirun-prefix-by-default 2>&1 | tee config_output.txt
$ make 2>&1 | tee make_output.txt
```

[make_output.txt](https://github.com/open-mpi/ompi/files/1261112/make_output.txt)
[config_output.txt](https://github.com/open-mpi/ompi/files/1261111/config_output.txt)

**Comment by jsquyres** [comment]
From @cagoelz:

```
$ find . -name "*.o" -exec grep opal_atomic_cmpset_64 {} \;
Binary file ./class/.libs/opal_list.o matches
Binary file ./mca/mpool/hugepage/.libs/mpool_hugepage_module.o matches

$ nm ./class/.libs/opal_list.o | grep opal_atomic_cmpset_64
        U opal_atomic_cmpset_64

$ nm ./mca/mpool/hugepage/.libs/mpool_hugepage_module.o | grep opal_atomic_cmpset_64
        U opal_atomic_cmpset_64
```

**Comment by jsquyres** [comment]
@cagoelz Can we get the `config.log` file as well?  @hjelmn would like to see it.

**Comment by cagoelz** [comment]
Here it is. 
[config.log.zip](https://github.com/open-mpi/ompi/files/1261197/config.log.zip)

**Comment by hjelmn** [comment]
Hmm, seems this is a side-effect of deleting the old hand-coded ASM. This commit is why it is failing: open-mpi@b5ea5e09 . @bwbarrett Do you remember any of the details? I wonder if gcc still have the limitation.

**Comment by bwbarrett** [comment]
Wow; talk about bad flashbacks.  I love this part:
```
For the beta, just use the non-inline version
```
Apparently it took 12 years for the hack to catch up with us.

Shockingly, I do remember this one.  `cmpxchg8b ` requires `ebx` to be used, but some versions of gcc were throwing an error trying to protect `ebx`, because shared libraries totally break if you change `ebx` (which we handle by saving/restoring the register).  It was a hard compile-time error.  We should be able to try a couple modern versions of gcc and if they compile, we're good.

**Comment by hjelmn** [comment]
Should be fixed now. We will re-open if MTT continues to show failures.
