### ISSUE TITLE
LD_PRELOAD and errno not 0 at startup

### ISSUE THREAD

**Issue by mathog** [open-mpi/ompi#4255]
Thank you for taking the time to submit an issue!

## Background information
Centos 6.7,  with RPMS
openmpi-1.8-1.8.1-5.el6.x86_64
openmpi-1.8-devel-1.8.1-5.el6.x86_64

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
1.8

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
RPM using yum

### Please describe the system on which you are running

* Operating system/version:  Centos 6.7
* Computer hardware:  Big Dell server
* Network type:  it doesn't get that far

-----------------------------

## Details of the problem
If this is set
```
LD_PRELOAD=/usr/lib64/openmpi/lib/libmpi.so
```
then errno is not zero when execution enters user code.  Even and especially in programs
which do not do ANYTHING with MPI.

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

(Example previously posted to newsgroup comp.lang.c)

```
cat >bad.c <<'EOD'
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
int main(void){
// errno=0;  //uncomment this and the program works right
   fprintf(stderr,"Error text: %s\n",strerror(errno));
   exit(EXIT_SUCCESS);
}
EOD
gcc -o bad bad.c
#
# with LD_PRELOAD set
#
set | grep PRELOAD
LD_PRELOAD=/usr/lib64/openmpi/lib/libmpi.so
./bad
Error text: No such file or directory
ldd ./bad
        linux-vdso.so.1 =>  (0x00007fff3a386000)
        /usr/lib64/openmpi/lib/libmpi.so (0x0000003894a00000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003f8d200000)
        libopen-rte.so.7 => /usr/lib64/openmpi/lib/libopen-rte.so.7 (0x0000003893e00000)
        libopen-pal.so.6 => /usr/lib64/openmpi/lib/libopen-pal.so.6 (0x0000003894600000)
        libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x0000003fa4200000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003f8de00000)
        librt.so.1 => /lib64/librt.so.1 (0x0000003f8e600000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x0000003f9d200000)
        libutil.so.1 => /lib64/libutil.so.1 (0x0000003f9c200000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003f8d600000)
        libltdl.so.7 => /usr/lib64/libltdl.so.7 (0x0000003f9c600000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003f8da00000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003f8ce00000)
#
# with LD_PRELOAD not set
#
unset LD_PRELOAD
./bad
Error text: Success
ldd ./bad
        linux-vdso.so.1 =>  (0x00007ffd69369000)
        libc.so.6 => /lib64/libc.so.6 (0x000000313c200000)
        /lib64/ld-linux-x86-64.so.2 (0x000000313be00000)
```

LD_PRELOAD is set like this because a perl script which uses OpenMPI needs it.

gcc guarantees that errno is 0 when the program starts:

https://www.gnu.org/software/libc/manual/html_node/Checking-for-Errors.html

but linking in openMPI creates a program which breaks that guarantee.

**Comment by ggouaillardet** [comment]
> The initial value of errno at program startup is zero

imho, when ```LD_PRELOAD``` is used, ```program startup``` should be interpreted as when the (first) constructor of the LD_PRELOAD'ed library is invoked. Otherwise, and still imho, this behaviour should be seen as a bug of the GCC runtime.

Open MPI 1.8 is no more supported (you should use either the ```2.1``` or the newly released ```3.0``` series, try again and see how things go and we __might__ reset ```errno``` if we can reach a consensus.

At this stage, i believe your program makes incorrect asumption, and i do encourage you to fix your applications.

**Comment by mathog** [comment]
Yeah, I know 1.8 isn't supported anymore.   I don't have a test system to see if 2.1 does the same thing.  Why is OpenMPI setting errno before it enters main() on the test program?  The error message indicates that it went looking for some file or directory and did not find it.  What file/directoy might that have been?  I can fix my own code but not any other program that has a similar issue if only the binary is available.  If OpenMPI is looking for some configuration file, for instance, one workaround would be to create that file, thus suppressing the setting of errno.

**Comment by jsquyres** [comment]
Note that we never really designed Open MPI to be invoked pre-`main()`; there was no attempt to ensure `errno` was set to 0 before library constructors returned (not even in the newly-released v3.0.0).  The MPI specification gives a few functions that are supposed to be used to initialize MPI state (e.g., `MPI_Init()`).

Meaning: I really don't have any idea offhand as to what caused `errno` to be set to nonzero.  It may not even be directly in Open MPI itself -- it could have happened in a library constructor of a dependency.

Keep in mind that there are lots of things -- in Open MPI and in supporting libraries -- that can set `errno` to be nonzero but are not fatal errors (and aren't even worth printing to stderr).  Indeed, because of this issue alone, I think relying on `errno==0` at the beginning of `main()` is probably not a good assumption.  More specifically: `errno` not being 0 doesn't really mean anything unless you know the context in which that value was set.  What you're seeing -- `errno != 0` at the beginning of `main()` -- simply means that something caused `errno` to be nonzero, but assumedly that *something* also deemed whatever happened to be a non-fatal issue.  You really can't infer anything more than that.

Also, I note that the URL you cite says "The initial value of errno at program startup is zero".  "Program startup" is not the same thing as entering `main()`.  If I had to guess -- and I'm not an expert here -- I'd guess that "program startup" means that all the bootstrapping has been done to create the process and load the binary(ies).  I.e., `errno` is 0 when the first user code for the library executes (e.g., library constructors and/or `main()`).

That URL also cites several cases of needing to set `errno` to 0 before checking it (e.g., functions that succeed don't always set `errno` to 0).  Can you describe what you are hoping to do by checking `errno` before your code invokes any code that could set `errno`?

**Comment by mathog** [comment]
The test program was boiled down from a much larger program which checked errno after a call that could have set it to a nonzero value if an error was seen in that function (strtoull).    The original program was seen to exit at that point when LD_PRELOAD was set, even though it didn't do anything  with MPI itself.   Normally for strtoull() one checks for a return value of ULLONG_MAX before checking errno, but that doesn't help in this particular case, because the program in question is used to generate specific binary file contents, and unsigned long long with all bits set is a pretty common thing to output in that context, so it just checked errno.  So  even if it had waited for ULLONG_MAX the bug would still have been there and would have turned up at some later date when that value was used.  

Within the context of the original program there was never previously any reason to set errno to 0.  It would always be 0 when it started, and it would always exit if errno was checked and was not 0.  The program never called anything explicitly other than standard C functions.  However, with LD_PRELOAD set the initial assumption was not satisfied.  LD_PRELOAD was only being used because a Perl script (part of "Maker", a package for analyzing DNA sequence), needed it. That perl script builds some C code inline to access MPI and then applies some odd tricks to link it all together and run it, and it needs to use LD_PRELOAD.   It had been suggested that LD_PRELOAD be put into .bash_profile, so it affected all the other code run from that account.

Anyway, would it be reasonable to suggest that wherever the openMPI library calls a function and then finds that errno is neither 0 nor a fatal value that it then reset errno to 0 at that point?

**Comment by jsquyres** [comment]
@mathog Gotcha.  Sounds like you were getting lucky about no other library constructors setting `errno` to a nonzero value, but when your requirements changed, something (Open MPI or one of its dependent libraries) has a constructor that is setting `errno` to nonzero.

As for having Open MPI reset `errno` back to 0, there are likely literally hundreds of places where this can occur in the Open MPI code base.  The theme here is that -- in the grand scheme of things -- `errno != 0` is rarely a fatal issue.  For example, in many cases, it's a test result that indicates something about your system.

It would likely be far easier (and more portable) to reset `errno` to 0 before calling `strtoull()` in your code.  The GCC web page you cited seems to indicate that this is the Right Thing to do.

Indeed, changing Open MPI's behavior may fix the problem for you *today*, but you may run into the same problem again someday if you start using some other support library that exhibits similar behavior.

**Comment by jsquyres** [comment]
With no further traffic on this issue, I'm assuming that setting `errno` to 0 before calling `strtoull()` is a sufficient fix.

**Comment by mathog** [comment]
Not sure if "sufficient" is the word I would use, but certainly it is the only practical fix since the OpenMPI version in question is no longer supported.  

It is probably still worth finding out though if the current code sets errno the same way when it is pulled in with LD_PRELOAD for a program which otherwise makes no use of OpenMPI.  That is, it might actually be a bug that OpenMPI is setting this value when loaded in this manner.  The error is "No such file or directory" which is pretty strange given that ldd shows all the expected libraries in this state and all of them exist and are readable on the test system.  

My best guess was that this error referred to some configuration file describing nodes and processing capabilities that OpenMPI should use, ie, a default for -hostfile.   Apparently though that isn't the case, or at least explicitly specifying a host or a hostfile does not resolve the problem:

./bad
Error text: No such file or directory
/usr/lib64/openmpi/bin/mpiexec -host localhost ./bad
Error text: No such file or directory
cat >hostfile <<EOD
localhost  slots=1
EOD
/usr/lib64/openmpi/bin/mpiexec -host localhost ./bad
Error text: No such file or directory

**Comment by jsquyres** [comment]
To be clear: the GNU page you cited said that setting `errno` to 0 before calling `strtoull()` is the correct fix.  As described earlier on this issue, you cannot assume that `errno` is 0 before you set it to 0 -- even as the first executable statement in `main()`.

FWIW: setting `errno` to `ENOFILE` can happen for many different reasons, and most of them are just normal functions of Open MPI or dependent libraries (e.g., check to see if an optional file is there, and if so, process it).  If you can track down exactly why it is happening, great -- but it may not reveal anything useful / there may not be anything to fix.
