### ISSUE TITLE
Error: unknown option "-np"

### ISSUE THREAD

**Issue by amaslenn** [open-mpi/ompi#4557]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
OMPI `v3.1.0a1`
 
### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
It was built using from source using following cmd:
```sh
./autogen.sh
./configure --prefix=/path/ompi-v3.1.x
    --with-knem=<path-to-knem>
    --with-mxm=<path-to-mxm>
    --with-hcoll=<path-to-hcoll>
    --with-ucx=<path-to-ucx>
    --with-platform=contrib/platform/mellanox/optimized
    --with-slurm
    --with-pmi
```
 
### Please describe the system on which you are running
 
* Operating system/version: `RedHat 7.2`
* Computer hardware: `ConnectX-4 on x86 arch`
* Network type: `IB`
 
-----------------------------
 
## Details of the problem
I run tests with MTT and sometimes see a very strange error:
`$ /path/ompi-v3.1.x/bin/mpirun -np 3 --debug-daemons --display-map -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_4:1 -mca btl_openib_if_include mlx5_4:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -mca osc ucx -x UCX_TLS=rc,sm --map-by node test-app`
```sh
/path/ompi-v3.1.x/bin/mpirun: Error: unknown option "-np"
```
It is not reproducible manually, it happens with different test apps and options.
 
Maybe someone has a clue why it happens.

**Comment by amaslenn** [comment]
+ @miked @alinask

**Comment by rhc54** [comment]
Check your LD_LIBRARY_PATH and see if the mca_schizo_ompi.la library is present and is correctly being loaded.

**Comment by amaslenn** [comment]
@rhc54 thanks! Will check it.

**Comment by ezze** [comment]
@amaslenn, have you solved the issue?

**Comment by amaslenn** [comment]
No, not yet.

**Comment by hppritcha** [comment]
@amaslenn has someone from Mellanox helped you with this?

**Comment by amaslenn** [comment]
@hppritcha yes. I myself work for Mellanox :)

See the issue less often for OMPI@master.

**Comment by artpol84** [comment]
I have an issue with OMPI master.
@amaslenn have you figured out the way to solve this?

**Comment by artpol84** [comment]
In my case, it was a conflict of OMPI installation from modules and my own.

**Comment by amaslenn** [comment]
@artpol84 no, I didn't solve it yet. Happens rarely and not reproducible manually (I didn't succeed with it).
Do you have a manual reproduction?

**Comment by jsquyres** [comment]
FWIW, the only times I have seen this happen are:

1. You are accidentally not running the `mpirun` that you think you are.  I.e., you're running an `mpirun` that does not accept `-np`.  The message you sent *could* be an Open MPI error message, though, and I think Open MPI has always accepted `-np`, so if it's an Open MPI `mpirun`, this doesn't shed much light on what could be happening.
1. You accidentally use a `-` that is not the normal `-` (e.g., a non-ASCII long-dash or something).
1. There's an accidental non-shell invocation that includes spaces in tokens.  Doesn't look like this is the case here (because we would have seen a different error message), but I thought I'd list this for completeness.

**Comment by artpol84** [comment]
@amaslenn, as I reported in my case the issue was in the conflict of OMPI installations.

I was building my OMPI from sources while having a module with hpcx loaded. This caused schizo components to be linked with libopen-rte.so from modules.
@jsquyres @rhc54 is this an expected behavior?

schizo framework adjusts to the environment. In particular, if I understand correctly it has (directly or indirectly) a list of parameters that are supported by mpirun. 
Because of the linking conflict schizo component is unable to load thus only a few parameters are available and "-np" is not.
Actually, if you will take your original cmdline:
```
/path/ompi-v3.1.x/bin/mpirun -np 3 --debug-daemons --display-map -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_4:1 -mca btl_openib_if_include mlx5_4:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -mca osc ucx -x UCX_TLS=rc,sm --map-by node test-app
```

and switch `-np` and `--debug-daemons` (or any other option) you will get mpirun complaining about the very first one it sees. This is because non of them are known as the result of schizo component failure.

The problem is that mpirun is failing silently with schizo and it is very confusing.
We can have a call your evening if you want more details.

**Comment by jsquyres** [comment]
> I was building my OMPI from sources while having a module with hpcx loaded. This caused schizo components to be linked with libopen-rte.so from modules.

I'm not sure what this means -- what are HPCX modules?  What is the `libopen-rte.so` "from modules"?

**Comment by yosefe** [comment]
@artpol84 are you compiling OpenMPI master with ICC?

**Comment by artpol84** [comment]
First of all, to clarify - I solved my case.

@jsquyres 
> I'm not sure what this means -- what are HPCX modules? What is the libopen-rte.so "from modules"?
* Modules is a package to manage environment: http://modules.sourceforge.net/
* We have a pre-build HPCX (which is Mellanox HPC stack that includes pre-build Open MPI)
* "libopen-rte.s0" (sorry if I misspelled it) is an ORTE base library that is part of a pre-build HPCX installation available from modules.

> @artpol84 are you compiling OpenMPI master with ICC?
@yosefe yes this was my case.

**Comment by tranqv** [comment]
I got the same problem: the mpirun command produces the message 

Error: unknown option "-np"

In my system:
+ OpenMPI version 4.0.4.
+ gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

./configure \
   --prefix=/home/..../openmpi/gnu/4.0.4 \
   --enable-script-wrapper-compilers \
   --enable-mpi-fortran \
   CC=gcc  \
   CFLAGS=-O2 \
   FC=gfortran \
   FCFLAGS=-O2

Has the problem been solved ?

Thank you.

**Comment by rhc54** [comment]
This works fine on master and v5

**Comment by jrcalciano** [comment]
In case it helps anyone else, here's how I caused (and then solved) the problem.

First, I caused the problem by changing the target directory (i.e., the --prefix= directory) name after building and installing.
For example, I did:
`./configure --prefix=/opt/my_ompi_dir`
...then built and installed as usual.

Later, I changed the directory name:
`mv /opt/my_ompi_dir /opt/my_great_ompi_dir`
When I tried to run using the new directory name
`/opt/my_great_ompi_dir/bin/mpirun -np 2`
...that's when I saw the the error.
So I changed the directory name back to the original, and everything was fine again.

**Comment by awlauria** [comment]
@jrcalciano with your steps I can reproduce on v4.0.x with orted.

On v5.0.x I can't exactly reproduce with prrte, however I no longer get any output from mpirun:

```
[awlauria@f8n02 awlauria_ompi2]$ ./exports_great/bin/mpirun -np 2 hostname
[awlauria@f8n02 awlauria_ompi2]$ ./exports_great/bin/mpirun --help
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    prun:usage
But I couldn't open the help file:
    /smpi_dev/awlauria/ompi_builds/awlauria_ompi2/exports/share/prte/help-prun.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
[awlauria@f8n02 awlauria_ompi2]$ 
```

**Comment by rhc54** [comment]
IIRC, that is correct - you cannot just "move" the directory. There are portions of the system (e.g., the `installdirs`) that are hardwired by configure. Moving the installation therefore breaks all kinds of things. IIRC, you _can_ move things, but you then have to set something like `OPAL_DESTDIR` to help the system. Given we now have independent package installs on v5.0, you'd probably have to do a `PRRTE_DESTDIR` and `PMIX_DESTDIR` too.

**Comment by luoyu-intel** [comment]
For my case, `unset OPAL_PREFIX` solved my problem.
