### ISSUE TITLE
Prevent Clang/LLVM from inlining or removing MPIR_Breakpoint as dead function

### ISSUE THREAD

**Issue by kiranchandramohan** [open-mpi/ompi#4624]
Many parallel debuggers depend on the MPIR_Breakpoint function. Clang/LLVM can inline or remove MPIR_Breakpoint as dead function. Can the optnone attribute be added to the MPIR_Breakpoint function to prevent it from being optimized away ?

file : orte/orted/orted_submit.c
```
#ifdef __clang__
__attribute__((optnone))
#endif
ORTE_DECLSPEC void* MPIR_Breakpoint(void);
```

**Comment by kiranchandramohan** [comment]
Thanks Ralph.

**Comment by dirk-schubert-arm** [comment]
Thanks @rhc54 . If I understand the merge #4626 correctly this is only in [master](https://github.com/open-mpi/ompi/blob/master/orte/orted/orted_submit.c) so far, but not in [3.1.x](https://github.com/open-mpi/ompi/blob/v3.1.x/orte/orted/orted_submit.c) or [3.0.x](https://github.com/open-mpi/ompi/blob/v3.0.x/orte/orted/orted_submit.c). Any chance to backport this into 3.0.x and 3.1.x, as otherwise hitting MPIR_Breakpoint won't work in those versions when compiled with Clang/LLVM?

**Comment by rhc54** [comment]
Done: #4715 and #4716

**Comment by dirk-schubert-arm** [comment]
Thanks Ralph.
