### ISSUE TITLE
mpirun consumes stdin unecessarily

### ISSUE THREAD

**Issue by nasailja** [open-mpi/ompi#466]
With regular programs I can queue up several commands while previous ones are executing by just typing stuff or using up/down keys and enter but that doesn't work with mpirun as everything I type while mpirun is executing is consumed and ignored. For example if I run sleep 10 and while it's waiting type echo test I see test echoed on screen after sleep returns but when running sleep 10 via mpirun that doesn't work. This is what it looks like on my screen:
```
$ sleep 10
echo test
$ echo test
test
$ mpiexec -n 1 sleep 10
echo test
$ mpirun -n 1 sleep 10
echo test
```
I don't know if it's possible to make mpirun behave as normal programs in this respect but it sure would be nice.

**Comment by jsquyres** [comment]
FWIW, I've noticed this issue, too.  And you're right: it is annoying.  It would be a quite a bit of work to fix it, unfortunately.

A little background...

With a "normal" program (e.g., not mpirun), input is slurped off stdin when the process itself reads from stdin.  stdin usually defaults to line mode, so input is read a line at a time.  Hence, if you:

```sh
$ sleep 10
echo test
```

i.e., you type `echo test` while `sleep 10` is running, the `sleep` command never reads from stdin, so that `echo test` line stays buffered in stdin until the shell wakes up again and reads it.

With mpirun, we have to shuttle the stdin from mpirun to whichever mpirun-launched process(es) you have directed it (mpirun defaults to forwarding stdin to just the first launched process -- e.g., the one with MPI_COMM_WORLD rank 0).  As such, mpirun has a standing "is there anything to read on stdin?" operation always running.  Hence, when you type "echo test", mpirun reads it from stdin and then forwards that to the target MPI process(es).  In your example, that "echo test" input effectively gets discarded because the "sleep 10" process never reads it.

The catch is that mpirun is doing this slurp-from-stdin proactively -- not just when one or more mpirun-launched processes ask for stdin.  Hence, mpirun will always drain stdin if there is something to read, regardless of whether the target process(es) actually use that data or not.

More specifically, to fix this, I think we'd have to do something along these lines:

1. Monitor mpirun-launched processes that are the target of stdin forwarding for attempts to read stdin
1. De-duplicate stdin requests from multiple processes (...er... I don't really know how to do this... although it's not an issue when there's only a single mpirun-launched process consuming stdin)
1. Monitor mpirun-launched processes for changes to stdin buffering from line mode to byte mode (...er... I don't know how to do this, either...)
1. When a stdin-consumer process reads from stdin, send a control message back to mpirun telling it to activate the stdin-slurper for 1 line of input.
1. Have mpirun get that control message and queue up a request to read one line of input.
1. When mpirun eventually reads 1 line of input, forward it to the target process(es).
1. Rinse, repeat.

So other than the parts I don't really know how to do, it's *do-able*, but it's a bunch of work that I honestly don't know if anyone has the cycles to do.

**Comment by nasailja** [comment]
That does sound like too much work. I though it would be possible to connect or pass through stdin of mpirun to stdin of whichever single program is launched so that stdin reads of that program would be taken from mpirun's stdin. I couldn't find anything like this though. Or maybe in case of a single program one could replace mpirun's stdin with the one of the launched program? In that case mpirun couldn't read anything from stdin but it doesn't need to does it?

**Comment by jsquyres** [comment]
Unfortunately not.  One major complicating factor is that mpirun may not be running on the same server as the process(es) that receive the stdin forwarding.

**Comment by rhc54** [comment]
Or you could just tell mpirun not to slurp stdin by adding “—stdin none” to the cmd line

**Comment by rhc54** [comment]
As I said, this enhancement already exists via the "--stdin none" option
