### ISSUE TITLE
shmem_global_exit(0) does not terminate job using Slurm

### ISSUE THREAD

**Issue by nspark** [open-mpi/ompi#4803]
### What version of Open MPI are you using?

v1.8.8 and v2.1.2 (I _can_ test newer versions, though not as easily)

### Describe how Open MPI was installed

From Mellanox HPC-X Toolkit

### Please describe the system on which you are running

* Operating system/version:  RHEL 6.5
* Computer hardware: Intel Xeon
* Network type: Mellanox ConnectX-4 IB
* Scheduler/resource manager: Slurm + PMI2

-----------------------------

## Details of the problem

A simple SHMEM program that calls `shmem_global_exit(0)` does not terminate the job; instead, it hangs.

```c
#include <stdio.h>
#include <shmem.h>

int main (int argc, char *argv[])
{
  shmem_init();
  if (shmem_my_pe() == 0)
    shmem_global_exit(0);
  shmem_barrier_all();
  shmem_finalize();
  return 0;
}
```

**Edit** Clarifying note: If `shmem_global_exit()` is called with a non-zero status, the program's behavior is as expected and the application terminates, returning the non-zero status to the environment.

**Comment by jsquyres** [comment]
I'm not much of a shmem user, but is that a valid program?

I.e., how would the `shmem_barrier_all()` complete successfully if one of the processes has exited?

**Comment by nspark** [comment]
Yes, the `shmem_global_exit()` call is designed to terminate execution cleanly for all PEs in a SHMEM job by a call from only one PE. On PE 0, the call to `shmem_global_exit()` does not return; on non-zero PEs, the call to `shmem_barrier_all()` should block until the runtime causes those processes to terminate.

**Comment by jladd-mlnx** [comment]
Nick, how are you launching the job? With oshrun or srun?

**Comment by nspark** [comment]
@jladd-mlnx I'm launching the job with srun.

**Comment by jladd-mlnx** [comment]
@nspark which HPC-X version are you using? Which SPML?

**Comment by nspark** [comment]
HPC-X 1.4.355 for OSHMEM 1.8.8 and HPC-X 1.9.5 for OSHMEM 2.1.2

**Comment by jladd-mlnx** [comment]
@karasevb Can you see if the reproduces with the latest HPC-X and PMIx?

**Comment by karasevb** [comment]
@jladd-mlnx 
Launching by srun hangs for HPC-X 2.0 and 2.1. While oshrun launching works well.
I'll investigate.

**Comment by karasevb** [comment]
Nick, please try using `pmix` instead of `pmi2` to srun launching.

`shmem_global_exit` in eventually leads to call PMI_abort. 
There are two different behavior for PMIx and PMI2:
- The described behavior above is not a bug for **PMI2** - this is expected and this is defined in Slurm [PMI2_Abort](https://github.com/SchedMD/slurm/blob/slurm-17.11/contribs/pmi2/pmi2.h#L280-L284):
```C
  PMI2_Abort - abort the process group associated with this process
  
  Input Parameters:
  + flag - non-zero if all processes in this job should abort, zero otherwise
```
That is, if `PMI2_Abort` is called with a non-zero status then only the called process will aborted. [Here](https://github.com/SchedMD/slurm/blob/slurm-17.11/src/plugins/mpi/pmi2/pmi2.c#L179-L193) is the callback implementation of abort. May see that Slurm will kill all processes ([`slurm_kill_job_step`](https://github.com/SchedMD/slurm/blob/slurm-17.11/src/plugins/mpi/pmi2/pmi2.c#L189-L191))  only when flag is non-zero.
 Also `PMI2_Abort` describes here: https://wiki.mpich.org/mpich/index.php/PMI_v2_API#Initializing.2C_Finalizing.2C_and_Aborting_PMI

- **PMIx_Abort** uses another way, that kills all processes for any statuses. [Here ](https://github.com/SchedMD/slurm/blob/slurm-17.11/src/plugins/mpi/pmix/pmixp_client_v2.c#L84-L97)is `PMIx_Abort` callback implementation.

**Comment by artpol84** [comment]
@nspark Note that you will need pmix plugin available in Slurm. trace

**Comment by artpol84** [comment]
@nspark @jsquyres can this be closed?

**Comment by nspark** [comment]
:+1: I'm okay with that
