### ISSUE TITLE
support for share physical memory between processes?

### ISSUE THREAD

**Issue by redirus** [open-mpi/ompi#4865]
Thank you for taking the time to submit an issue!
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
V3.0

## Details of the problem

Each process has to read same data from memory, however, the physical memory is not big enough to support 8 copies of the data but 1 copy of the data. So is there any support for sharing the same memory for the 8 processes in open-mpi?
Thanks

**Comment by bwbarrett** [comment]
If you're just looking for a portable way of allocating shared memory across ranks on the same node, MPI_WIN_ALLOCATE_SHARED might be what you're looking for (http://mpi-forum.org/docs/mpi-3.1/mpi31-report/node263.htm#Node263).  It was added as part of MPI-3, and is supported in Open MPI 3.0.0.  The user is still responsible for handling memory consistency issues between the processes (although you can use the MPI one-sided access and synchronization primitives as portable ways of handling memory consistency), so some application work may be required.  But if the data you're concerned with is read-only, it can be a relatively easy way of reducing total memory footprint.

**Comment by redirus** [comment]
Yeah It is read-only. Could I put some data structure like unordered_map into the shared memory using MPI_WIN_ALLOCATE_SHARED?

**Comment by jsquyres** [comment]
Shared memory can be a little more complicated than that -- since each process may have a different virtual address space, the values of pointers may be different in each process.  Google around and look up some tutorials on shared memory.  Also be wary of Brian's warning about memory consistency -- that's another pitfall of shared memory that can be tricky to get just right.  If you're writing to shared memory once and then every other process is just reading it after that, it's a little easier, but you still need to do proper memory consistency for that first round of data.  This is a bit outside of MPI's scope.

**Comment by jsquyres** [comment]
Heh.  I was *gently reminded* off-list that my last comment ("This is a bit outside of MPI's scope") wasn't quite correct.

It would probably be more correct to say: MPI provides mechanisms for ensuring memory consistency, but the user is responsible for properly using those mechanisms.

Those mechanisms are:

1. Using the MPI window / one-sided APIs.  Be sure you *carefully* read the MPI one-sided chapter; this stuff is subtle and complicated.  The MPI text is quite specific, but if you're just starting out with this stuff, you should be quite careful.
1. Using MPI_WIN_ALLOCATE_SHARED.  In this case, MPI will allocate shared memory for you (contrary to what I said above, because I had totally forgotten about MPI_WIN_ALLOCATE_SHARED -- thanks to @bwbarrett for keeping me honest!), but then all memory consistency issues are up to you.  I.e., MPI gives you shared memory and says "here you go; good luck" and does not apply any of the memory consistency mechanisms that are provided with the MPI one-sided APIs.  Which is perfect for people who know what they're doing (and precisely why MPI_WIN_ALLOCATE_SHARED was added to the MPI standard).
