### ISSUE TITLE
opal/util/info.c can write keys that are too long

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4959]
In 482d84b6e54, `opal/util/info.c` was heavily revamped.  Part of its commit message says:

> Inside info_subscribe_subscribe() the specified callback() is called with whatever matching k/v is in the object's info, or with the default. The return string from the callback goes into the new k/v stored in info, and the input k/v is saved as `__IN_<key>/<val>`. It's saved the same way whether the input came from info or whether it was a default. A null return from the callback indicates an ignored key/val, and no k/v is stored for  it, but an `__IN_<key>/<val>` is still kept so we still have access to the original.

However, when compiling this code with a modern gcc (e.g., v7.3.0), one gets the following warning message:

```
info.c: In function ‘opal_info_dup_mode’:
info.c:209:42: warning: ‘%s’ directive writing up to 36 bytes into a region of size 31 [-Wformat-overflow=]
                  sprintf(savedkey, "__IN_%s", iterator->ie_key);
                                          ^~
info.c:209:18: note: ‘sprintf’ output between 6 and 42 bytes into a destination of size 36
                  sprintf(savedkey, "__IN_%s", iterator->ie_key);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

A few things:

1. We should be using `snprintf()`, not `sprintf()`.
1. The keys are strings of fixed length OPAL_MAX_INFO_KEY.  If you prepend `__IN_`, you're potentially writing up to 5 characters past the end of the array (i.e., if the key length is already >= OPAL_MAX_INFO_KEY-strlen("__IN_")).  The code needs to be adjusted to either take this additional prefix into account or have an additional attribute stashed somewhere that indicates that it's one of these special "in" keys.

**Comment by jsquyres** [comment]
This was just noted again by @rhc54 in https://www.mail-archive.com/devel@lists.open-mpi.org/msg20587.html.

@markalle Can you please adjust the code?

**Comment by markalle** [comment]
It's already protected by a check to make sure the length won't overflow:
```
             if (strlen(iterator->ie_key) + 5 < OPAL_MAX_INFO_KEY) {
                 sprintf(savedkey, "__IN_%s", iterator->ie_key);
```
And the code would be silently inactive if a large key happened to come in. The __IN_* keys should only matter for internal keys though that have callbacks registered via opal_infosubscribe_subscribe(), not user-keys, so we have control over those lengths.

It's true this code comes with a small limitation on what keys we can put those callbacks on. So how about this: I'll put a warning to stderr in opal_infosubscribe_subscribe() if somebody puts an internal key there that's too big, and change to snprintf() and otherwise change whatever the compiler needs to not get a compiler warning. But still leave the limitation that the internal keys we register callbacks on would still be limited to MPI_MAX_INFO_KEY-5. Sound okay?

**Comment by jsquyres** [comment]
That sounds good to me.  Should we also put a check in that no keys ever come in with a prefix of `__IN_`?

**Comment by markalle** [comment]
Yeah, I seem to remember considering whether to do a fancier encoding that would avoid such conflicts but I don't see any code for that so this is indeed relying on "__IN_" as a special prefix. And that part isn't strictly an internal-only concern. A user could set the key "__IN_foo" and cause confusion to a get_info call that asked what "foo" had been set to.
