### ISSUE TITLE
Use rpath/runpath linking whenever possible

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5145]
Per discussion on 5124, it was discovered that Open MPI (i.e., Libtool) uses rpath/runpath linking when linking against 3rd party library `.la` files.  But if a 3rd party library does *not* have a `.la` file, Open MPI does not use rpath/runpath linking.  This means that a user experiences different default behavior depending on whether the 3rd party provides a `.la` file or not -- i.e., they may need to set `LD_LIBRARY_PATH` if the 3rd party does not provide a `.la` file.

It would be nice if Open MPI consistently use rpath/runpath linking when linking against 3rd party libraries, even if a `.la` file is not present.

That's actually somewhat tricky: since we don't have visibility into Libtool's individual linker commands, we'll have to examine each library in relevant `LIBS` to see if it has a `.la` file, and if not, add appropriate rpath/runpath CLI options. I can't think of a good central place to do that offhand. Suggestions / pull requests would be welcome here.

Note that we already have `--enable-wrapper-rpath` and `--enable-wrapper-runpath` CLI switches to `configure` -- not sure how they will play into this scheme, but it might be relevant to have those be related to this scheme somehow...?

FYI @lipixx

**Comment by bwbarrett** [comment]
If we do this (and I don't think we should), it should not be the default.  `.la` files have enough path information that they're essentially unrelocatable.  Moving them will break many things.  So it's safe to use rpaths, because if you move the libraries, you're going to have a bad day already.

Most unix libraries *are* relocatable.  You can move them and then use LD_LIBRARY_PATH or your system dynamic linker paths and everything will still "just work".  But if we start adding un-requested rpaths, we'll break that.

--enable-wrapper-rpath/runpath adds our install prefix (or what we detected as the current install path at runtime) to the rpath/runpath of the generated executable, so that people didn't have to modify their LD_LIBRARY_PATH for an Open MPI install that wasn't in the standard prefix.  It won't solve (and has nothing to do with) the general problem of libraries Open MPI depends upon that are installed in other locations.

**Comment by jsquyres** [comment]
@bwbarrett Fair points; I hadn't thought through the relocatable issues.  That certainly is a strong argument for not making this the default behavior.

Regarding the `--enable-wrapper-r*path` flags, I don't think I was clear: what I meant was more along the lines of "we already have some rpath/runpath CLI flags -- if we're adding more rpath/runpath behavior for which we want users to be able enable/disable (for a different case than what already exists), exactly what CLI flags should we be adding?"  E.g.:

1. Do we need `--enable-ompi-r*path` to enable rpath/runpath for just OMPI tools (vs. user executables)?
    * This is for the case where you want rpath/runpath behavior for OMPI tools and *not* for user executables.
1. Do we need `--enable-r*path` to enable rpath/runpath for *both* OMPI tools *and* user executables?
    * I.e., `--enable-r*path` is a synonym for `--enable-ompi-r*path --enable-wrapper-r*path`.

@lipixx With all this being said, I'm still not quite sure how this would be implemented.

**Comment by lipixx** [comment]
I have been also looking for alternatives in our side.

I think the best one that would work for both of us would be to remove the .la files on our side thus making OMPI not link against the inter-dependencies of our libraries, and then, because the OMPI configure line includes something like:

../../git/ompi/configure ...... --with-pmi=/home/lipi/slurm/17.11/llagosti .......

one would assume that the rpath would be set. I think that the --with-pmi lose it sense if you explicitly specify the path to the pmi library and then you are forced to set LD_LIBRARY_PATH.

I will continue digging into that but I think this is the approach that makes more sense to me, to set the rpath whenever you specify the --with-xxx option and .la is not found.

What do you think?

**Comment by lipixx** [comment]
Hi,
We've changed the linking of Slurm's libpmi to libslurmfull, which is unversioned. libslurm.so had a version number and caused this issue. This workarounds the issue the customer has despite being a hack. If at some time the signatures of libslurmfull changes, there can still be problems on an upgrade. It is not ideal solution but it works for the customer. Moreover we usually encourage users to use pmi2/pmix instead of pmi, which would make this less critical.

For me you can close this issue.

Thanks for your time, I really appreciate it.

**Comment by jsquyres** [comment]
Ok.  I'll close this issue, then.

I do agree with you: delivering an unversioned library is asking for trouble.  It solves a problem today, but it may cause you greater problems tomorrow.
