### ISSUE TITLE
Important warning when compiling with `g++ -Wall -Wextra` for function internal cast

### ISSUE THREAD

**Issue by correaa** [open-mpi/ompi#5157]
When I upgraded to Fedora 28 I start receiving a compilation warning that may point to a bug, in which function pointers are casted between different types.

### Please describe the system on which you are running

Version      : 2.1.1
Release      : 9.fc28
Arch         : i686
Size         : 2.7 M
Source       : openmpi-2.1.1-9.fc28.src.rpm (f
Repo         : fedora

-----------------------------

## Details of the problem

Warning when compiling with `g++ -Wall -Wextra`

```
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘virtual void MPI::Op::Init(void (*)(const void*, void*, int, const MPI::Datatype&), bool)’:
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:121:46: warning: cast between incompatible function types from ‘void (*)(void*, void*, int*, ompi_datatype_t**, void (*)(void*, void*, int*, ompi_datatype_t**))’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Wcast-function-type]
     (void)MPI_Op_create((MPI_User_function*) ompi_mpi_cxx_op_intercept,
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:123:59: warning: cast between incompatible function types from ‘void (*)(const void*, void*, int, const MPI::Datatype&)’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Wcast-function-type]
     ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) func);
```

**Comment by jsquyres** [comment]
Believe it or not, this is intentional.  See the lengthy comment explaining what is happening here: https://github.com/open-mpi/ompi/blob/master/ompi/mpi/cxx/intercepts.cc#L133-L242

IIRC, this is because the C++ bindings were originally designed to be agnostic to the underlying MPI library.  Hence, they could only invoke `MPI_*` calls for the underlying MPI functionality.  When we pulled them in to Open MPI, we probably *could* have created an OMPI-ized / internal `ompi_op_create_for_cxx(...)` that took a "safe" last argument.  ...but I'm not even sure that would work nicely, because by our design, `libmpi` contains no C++ code.  So we couldn't pass a compatible function pointer (that contains an argument with a C++ type) down to the main Op-handling engine inside `libmpi`.  Hence, the workaround that is described in the lengthy comment.  It's gross, it's a hack, but it's actually safe.

Just curious: are you using the C++ bindings?  I ask because they're not built by default; you must have passed `--enable-mpi-cxx` to see that warning.

**Comment by correaa** [comment]
I am not using the c++ bindings. But only compiling a c++ source that
includes mpl.h.
This didn't happen in an earlier version.

**Comment by jsquyres** [comment]
FWIW, you probably don't need to `--enable-mpi-cxx`, then -- all that does is enable the MPI C++ bindings (there's no special sauce for using the C bindings from C++).

We haven't changed the C++ bindings in quite a few years (they were actually removed from the MPI standard in v3.0).  Indeed, the Open MPI community is internally debating whether to actually remove the MPI C++ bindings in v4.0.0 (i.e., out next major release -- probably next year).

FWIW: `git blame` shows that this `MPI::Op` functionality dates back to 2005: https://github.com/open-mpi/ompi/commit/5f96a74e338.  I don't know offhand what the first released version was that contained that commit.

**Comment by correaa** [comment]
I am using the fedora packages. I have no control on how the library is
compiled.
And I am not using the C++ bindings, just compiling from C++. There must be
a way to avoid compiling the warning code in the first place.

**Comment by jsquyres** [comment]
Ohhh... you're compiling your user application with `mpicxx` and seeing this warning; you're not seeing this warning *when compiling and installing Open MPI*.  That wasn't clear.

There is a hack that you can do that's gross but safe:

```c
#define OMPI_SKIP_MPICXX 1
#include <mpi.h>
```

This will tell Open MPI's `<mpi.h>` to not include all the C++ support.  I don't believe that we documented that macro anywhere, but a) it hasn't changed in years, and b) it won't change in years (because we're likely to remove the C++ bindings in the not-distant future, meaning that there won't be any further development in this area).

**Comment by correaa** [comment]
Ok, that silenced the warning, but it is ugly. I still wonder why it didn't
occur before (I just upgraded from Fedora 27 to Fedora 28).

Some options: There was some change in openmpi (mpi.h), or -Wextra became
more picky in gcc 8.

​At the end, the combination works `-Wextra -DOMPI_SKIP_MPICXX`​
​Another option ​is `-Wextra -Wno-cast-function-type` or disable `-Wextra`
all together.

​Thanks,
A​

**Comment by jsquyres** [comment]
I'd guess that gcc 8 became more picky.  Glad it works for you.

**Comment by correaa** [comment]
The situation is now more serious because in gcc 8.1.1 this is not a warning anymore but a hard error.

test.cpp:
```
$ cat test.cpp
#include<mpi.h>
int main(int argc, char* argv[]){
    MPI_Init(&argc,&argv);
    MPI_Finalize();
    return 0; 
}
$ module load mpi/openmpi-x86_64
$ mpic++ test.cpp
In file included from /usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/mpicxx.h:283,
                 from /usr/include/openmpi-x86_64/mpi.h:2704,
                 from testompi.cpp:1:
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘virtual void MPI::Op::Init(void (*)(const void*, void*, int, const MPI::Datatype&), bool)’:
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:123:38: error: invalid conversion from ‘void*’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-fpermissive]
     ompi_op_set_cxx_callback(mpi_op, reinterpret_cast<void*>(func));
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:113:53: note:   initializing argument 2 of ‘void ompi_op_set_cxx_callback(MPI_Op, void (*)(void*, void*, int*, ompi_datatype_t**))’
 extern "C" void ompi_op_set_cxx_callback(MPI_Op op, MPI_User_function*);
```

Of course the workaround `#define OMPI_SKIP_MPICXX 1` still works but I think this should be inside OpenMPI when c++bindings are not used.

**Comment by abrikos110** [comment]
you can add additional cast to `(intptr_t)` to avoid warning, please add this

**Comment by ggouaillardet** [comment]
@abrikos110 would you mind elaborating?

**Comment by abrikos110** [comment]
@ggouaillardet I added intermediate cast to `intptr_t` on my local `op_inln.h` file and compiler warning disappeared.
I replaced
```
inline void
MPI::Op::Init(MPI::User_function *func, bool commute)
{
    (void)MPI_Op_create((MPI_User_function*) ompi_mpi_cxx_op_intercept,
                        (int) commute, &mpi_op);
    ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) func);
}
```

with this:

```
#include <stdint.h>
inline void
MPI::Op::Init(MPI::User_function *func, bool commute)
{
    (void)MPI_Op_create((MPI_User_function*) (intptr_t) ompi_mpi_cxx_op_intercept,
                        (int) commute, &mpi_op);
    ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) (intptr_t) func);
}
```

After this addition warning disappeared. I think than it is correct addition because `intptr_t` should be able to handle all pointers ( https://en.cppreference.com/w/c/types/integer ). But cppreference says "This type need not be available", so it may not work in some cases.

**Comment by abrikos110** [comment]
I checked `void *` instead of `intptr_t`, it works too. So `intptr_t` is not needed

**Comment by ggouaillardet** [comment]
Thanks, I will have a look.

That being said, please keep in mind that the MPI C++ bindings were **removed** from the MPI standard more than a decade ago. They are no more built by default since Open MPI 4 and will be simply removed from the upcoming Open MPI 5, so your best bet is to modernize your code to avoid using them.

**Comment by abrikos110** [comment]
Oh, thank you. I don't use C++ bindings, but this file is somehow included (i was just annoyed by warning). I will check it, thanks.
