### ISSUE TITLE
ARM v8 CI minor issues

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5278]
In looking at a random CI run on ARMv8 on juno1 (https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/2953/Platform=ARMv8/consoleFull), I see several minor issues:

1. In running autogen.pl (I think this failure is in running the embedded PMIx's autogen):
```
sh: 1: config/pmix_check_cython.py: not found
```
2. In building the examples, UCX components are having symbol failures (which I think is https://github.com/open-mpi/ompi/issues/3224):
```
[juno001:06035] mca_base_component_repository_open: unable to open mca_atomic_ucx: /var/lib/jenkins/ompi-master/workspace/open-mpi.build.platforms@2/Platform/ARMv8/install/lib/openmpi/mca_atomic_ucx.so: undefined symbol: mca_spml_ucx (ignored)
```
3. Running the examples, it fails because oob/ud fails to create a CQ.  This seems to happen randomly -- the failure doesn't seem to be consistent across all CI runs on ARMv8:
```
--> running examples
--> mpirun version: 4.0
--> Running example: hello_c
--------------------------------------------------------------------------
Failed to create a completion queue (CQ):

Hostname: juno001
Requested CQE: 16384
Error:    Cannot allocate memory

Check the CQE attribute.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Open MPI has detected that there are UD-capable Verbs devices on your
system, but none of them were able to be setup properly.  This may
indicate a problem on this system.

You job will continue, but Open MPI will ignore the "ud" oob component
in this run.

Hostname: juno001
--------------------------------------------------------------------------
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
[juno001:06042] 1 more process has sent help message help-oob-ud.txt / create-cq-failed
```

The first and third may be real bugs or they may be local / config issues.  But I wanted to bring them up in a real issue so that these issues don't go unnoticed.

I'm assigning @shamisp since he's our ARM rep -- but I don't know who owns the `juno1` CI machine.

**Comment by rhc54** [comment]
The cython message is from the test that checks for it - it just means that cython isn't found.

The oob/ud output isn't a fatal error - it is a warning that the CQ can't be created on the node where mpirun is executing and so the oob/ud component disqualifies itself. It has been there for a very long time because nobody seems to care about fixing the darn thing.

The true failure is the vsetenv call. This isn't something in our code base. It is coming from the ```execv``` call when we fork/exec the application process and is totally outside of our control.

**Comment by jsquyres** [comment]
The cython test shouldn't emit an error like that, though.

I mention the oob/ud warning because it also shouldn't be happening (at least, not in CI).  Why is it happening?

You're probably right that the only *error* occurring is the vsetenv thing.

**Comment by rhc54** [comment]
Remember, the Cython test is running a small python script that attempts to import Cython. The error message is what we expect and we haven't found a way to suppress it because it comes directly from Python. That said, the test shouldn't be running since the PMIx code wasn't asked to generate the Python bindings. I'll investigate.

The oob/ud warning comes because the component built when it found the required libraries - it doesn't check for the presence of a device. It just attempts to create a CQ pair as its "probe" and then outputs that message. Been complaining about it for a long time.

**Comment by rhc54** [comment]
I fixed the vsetenv error by simply removing the opal_setenv that was trying to set that envar. No idea why ARM had an issue with it. Turned out it was stale anyway - we no longer used it, so removing it causes no harm.

Now we are stuck in a hang - no idea why or where.

**Comment by rhc54** [comment]
Looks like it was an atomics issue - I updated them from OPAL and the test passed. I'll leave this issue open, though, due to the oob/ud warning.

**Comment by shamisp** [comment]
Ralph - thanks for fixing this !
I didn't have a chance to look at it but my theory was that somehow the
variable is uninitialized and we end up runnier of the limit for the size
of variable.

**Comment by jsquyres** [comment]
Per 2018-06-19 webex, we plan to remove the oob/ud component for v4.0, so this issue will likely become moot.

**Comment by jsquyres** [comment]
Looks like this was resolved long ago.
