### ISSUE TITLE
OpenMPI install error:`Lhwloc1' is already defined.

### ISSUE THREAD

**Issue by astrung** [open-mpi/ompi#543]
i have downloaded openMPI 1.8.4,and i get this error:
: Assembler messages:
/home/as/openmpi-1.8.4/opal/mca/hwloc/hwloc191/hwloc/include/private/cpuid-x86.h:40: Error: symbol `Lhwloc1' is already defined.
Config:
./configure --prefix=/usr/local
make all install
So what is my wrong??

**Comment by jsquyres** [comment]
The problem is a bug in the embedded copy of hwloc that is inside Open MPI.

Can you try Open MPI v1.8.5rc1 (or rc2, which should be out in the next day or two)?  We updated the embedded hwloc to fix the bug:

    http://www.open-mpi.org/software/ompi/v1.8/

If you prefer to stay on a public release, you can install hwloc externally (e.g., download hwloc from  http://www.open-mpi.org/projects/hwloc/), install it somewhere, and then configure Open MPI 1.8.4 to use that external copy of hwloc instead of its internal/embedded copy with the `--with-hwloc=/path/to/hwloc/installation` command line switch to Open MPI's `configure` script.

Let us know how this works out for you.

**Comment by jsquyres** [comment]
I haven't heard back from you, so I'm going to close this issue.  Let us know if we need to re-open it.
