### ISSUE TITLE
Cross numa or not communication has  same latency

### ISSUE THREAD

**Issue by DensenLiu** [open-mpi/ompi#5490]
My OMPI version is 3.0.1,and use the OMB benchmark to test the performance.
My OS is  CentOS  7.5.
My cpu model is Intel(R) Xeon(R) CPU E5-2699 v3.

I want to test the different between Cross numa communication or not. According to the architecture of the cpu, i think it should takes longer to communicate across numa, but i cant get  the expected results, can some one tell me why.

Here is my test result.
in the same numa.

```
mpirun --allow-run-as-root -np 2 --bind-to core --map-by core --report-bindings osu_latency
MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
MCW rank 1 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
Size Latency (us)
0 0.52
1 0.60
2 0.60
4 0.64
8 0.63
16 0.69
32 0.70
64 0.70
128 0.79
256 0.84
512 1.04
1024 1.21
2048 1.43
4096 2.70
8192 2.97
16384 4.00
32768 5.34
65536 8.33
131072 15.98
262144 35.74
524288 70.56
1048576 139.44
2097152 286.12
4194304 572.76
```

in different numa 

```
mpirun --allow-run-as-root -np 2 --bind-to core --map-by numa --report-bindings osu_latency
MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../..]
MCW rank 1 bound to socket 1[core 18[hwt 0-1]]: [../../../../../../../../../../../../../../../../../..][BB/../../../../../../../../../../../../../../../../..]
Size Latency (us)
0 0.72
1 0.78
2 0.77
4 0.90
8 0.90
16 1.08
32 1.11
64 1.07
128 1.33
256 1.38
512 1.64
1024 2.08
2048 2.46
4096 4.20
8192 4.16
16384 4.72
32768 6.09
65536 9.23
131072 16.60
262144 36.51
524288 70.26
1048576 136.71
2097152 281.61
4194304 570.64
```

**Comment by DensenLiu** [comment]
thanks for your answer.
it may not be  my expected.
when my OS is redhat 6.6 at the same hardware and OMPI version, 30% gap in latency at 4194304 bytes，both small and large message.
I also install mpich in the same node, there are 100% gap in latency at small message and 20% gap at large message.
so i think my test result must be wrong.Crossing numa and not across numa should be different in latency with centos7.5 and OMPI 3.0.1.
i just install OMPI with command:
$./configure --prefix=$myprefix --enable-debug 
$make all
$make install

**Comment by rhc54** [comment]
You should have seen a big warning message at the end of configure about doing performance testing with ```--enable-debug```. One possibility is that the inefficiencies of the debug code is masking the differences you are trying to measure.

**Comment by DensenLiu** [comment]
when i don`t use --enable-debug,the latency is smaller,but the conclusion is not change.There is no significant gap between different numa and same numa.

**Comment by jsquyres** [comment]
Just to emphasize what @rhc54 said: it is *critical* to not use `--enable-debug` for performance timings with Open MPI.  `--enable-debug` adds a LOT of extra code in performance-critical code paths *for the purpose of debugging* -- making it unsuitable for performance testing.

------

200ns is a significant gap for the short messages.

The difference for large message sizes is not nearly as noticeable (percentage-wise) because the lower bound on the time necessary to transfer that much data dwarfs the performance penalty imposed by the choice of destination.  Put differently, the 200ns performance difference you see for short messages does not scale linearly with message size (that would be a horrid performance characteristic!).

I can't comment on what MPICH is doing and why you are seeing such huge performance differences there; you'll need to ask them.
