### ISSUE TITLE
Cannot run /bin/mpirun

### ISSUE THREAD

**Issue by cbordage** [open-mpi/ompi#5613]
When I run `/bin/mpirun`, I get the following error
```
A prefix was supplied to mpirun that only contained slashes.
```

But if I run `mpirun`, it works.

On my distribution (archlinux), `which mpirun` returns `/bin/mpirun` (_/bin_ is a symbolic link to _/usr/bin_).

**Comment by jsquyres** [comment]
What version of Open MPI are you using?

**Comment by bgoglin** [comment]
He was using 3.1.1 but the relevant code seemed identical in master.

**Comment by jsquyres** [comment]
This is likely a simple string parsing problem.  Any chance you can look into it?

**Comment by rhc54** [comment]
I think the prefix would have to be ```/``` and we shouldn't abort. This assumes that the libraries will be under ```/lib``` or ```/lib64``` etc. I'm not sure what to do if they were put somewhere else - in this case, there is a symlink used to point at the real location in /usr, so it is possible the corresponding symlinksfor libraries wasn't made. Suspect we'd just have to declare that a busted environment.

**Comment by jsquyres** [comment]
Yeah, I'm not really sure why we have that error (i.e., that there's a prefix that is only `/`).  That might just be over-zealous...?

**Comment by AntoineMazuyer** [comment]
Hi all,

I also have the same issue using Manjaro (arch based) distribution. I am not sure a busted environment is to blame.

**Comment by lahwaacz** [comment]
The `/bin -> /usr/bin` symlink in Arch provides compatibility for things which hardcode paths through `/bin`. The `which` tool is not such thing - if `which mpirun` produces `/bin/mpirun`, it's because you have `/bin` in your `$PATH`. If you remove it, then `which mpirun` produces `/usr/bin/mpirun`. Also note that the default `$PATH` in Arch is just `/usr/local/sbin:/usr/local/bin:/usr/bin`.
