### ISSUE TITLE
ompi is failing netcdf-fortran tests

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#571]
Per 's @opoplawski post (http://www.open-mpi.org/community/lists/devel/2015/05/17383.php), it looks like OMPIO is failing netcdf-fortran testing.

@edgargabriel Can you have a look?

**Comment by edgargabriel** [comment]
ok, I can but I am shocked to see that ompio in 1.8.5 is the default? 
THat was not the plan, that should be ROMIO. THere are a *huge* number 
of fixes on master that we can not backport to 1.8 series (since it 
involves interface changes of the frameworks), so by all means, ROMIO 
should be the default in 1.8 series...

THanks
Edgr

On 5/5/2015 10:12 AM, Jeff Squyres wrote:
> Per 's @opoplawski <https://github.com/opoplawski> post
> (http://www.open-mpi.org/community/lists/devel/2015/05/17383.php), it
> looks like OMPIO is failing netcdf-fortran testing.
>
> @edgargabriel <https://github.com/edgargabriel> Can you have a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/ompi/issues/571>.
>

-- 
Edgar Gabriel
Associate Professor
Parallel Software Technologies Lab      http://pstl.cs.uh.edu
Department of Computer Science          University of Houston
Philip G. Hoffman Hall, Room 524        Houston, TX-77204, USA
Tel: +1 (713) 743-3857                  Fax: +1 (713) 743-3335
--

**Comment by rhc54** [comment]
I fixed it

**Comment by jsquyres** [comment]
Slightly less terse than @rhc54: it was an accident that OMPIO was the default on v1.8.  It was fixed in 02bdb63a27c039028922dff70547e6d22547055a.  :-)

**Comment by edgargabriel** [comment]
thanks! I will still have a look at it, since there is always a chance that people might use it accidentally, e.g. if they configure without profiling interface, ROMIO can not be used and it will default to omio.If it is something that can be fixed without the changes in master, I am happy to provide a patch.

**Comment by jsquyres** [comment]
@edgargabriel Question: do the netcdf-Fortran tests pass on master with OMPIO?

**Comment by edgargabriel** [comment]
honestly I have not tried them, that's another reason to look into that

**Comment by rhc54** [comment]
@edgargabriel sorry for that terse reply - I was just buried in meetings yesterday, didn't have time to say a lot, but also didn't want you chasing something that I'd already fixed.

**Comment by edgargabriel** [comment]
no worries :-) even if it doesn't make it into the 1.8 series, I would still like to understand what is causing the problem

**Comment by edgargabriel** [comment]
even with the options mentioned on the mailing list, I can not reproduce the problem :-( I will continue to look into it next week, but both, the C and Fortran tests of netcdf pass for me on the 1.8 series as well as master.

**Comment by jsquyres** [comment]
@edgargabriel Any further progress on this?  If not, I guess we should close the issue...?

**Comment by edgargabriel** [comment]
We should probably just close this ticket, this is from 2015
