### ISSUE TITLE
`pshmem.h` now not usable without `shmem.h`

### ISSUE THREAD

**Issue by bertwesarg** [open-mpi/ompi#6093]
The new ctx API introduced in Open MPI 4.0.0 of SHMEM now requires to include `shmem.h` before `pshmem.h`, because of the `shmem_ctx_t` type.

### `pshmem.h`

```c
OSHMEM_DECLSPEC int pshmem_ctx_create(long options, shmem_ctx_t *ctx);
OSHMEM_DECLSPEC void pshmem_ctx_destroy(shmem_ctx_t ctx);
```

### `shmem.h`

```c
typedef struct { int dummy; } * shmem_ctx_t;

#define SHMEM_CTX_DEFAULT oshmem_ctx_default;

OSHMEM_DECLSPEC int shmem_ctx_create(long options, shmem_ctx_t *ctx);
OSHMEM_DECLSPEC void shmem_ctx_destroy(shmem_ctx_t ctx);
```

I'm not sure, if this is an issue at all, but maybe this change was unintended.

**Comment by jsquyres** [comment]
@xinzhao3 Is this a bug, or is it per the OSHMEM spec?

**Comment by hoopoepg** [comment]
pshmem is profiled interface for shmem, isn't it?
and there are set of defines (like version) in shmem.h which not defined in pshmem

I believe pshmem could not be used without shmem (or pshmem should include shmem.h)

**Comment by bertwesarg** [comment]
The standard does not mention the profiling interface at all.

**Comment by manjugv** [comment]
@bertwesarg OpenSHMEM does not specify the profiling interface, yet. However, there is a discussion in the working group to specify the profiling interface [1]. 

[1] https://github.com/openshmem-org/specification/pull/254

**Comment by bertwesarg** [comment]
> [1] [openshmem-org/specification#254](https://github.com/openshmem-org/specification/pull/254)

Thanks. In the [draft](https://github.com/openshmem-org/specification/files/2550022/main_spec.pdf) on page 112 is an example, which begins with:

```c
#include <stdio.h>
#include <sys/time.h>
#include <pshmem.h>
```

Thus I conclude that `pshmem.h` should be able to be included without prio inclusion of `shmem.h`.

**Comment by manjugv** [comment]
No. This is not ratified, so you should not draw any conclusions. We are only at the discussion stage now. However, your comment is useful for us, when we discuss this in the WG.

**Comment by ax3l** [comment]
Sounds like a typical case of ["include what you use"](https://include-what-you-use.org/) to me. If the `pshmem.h` header uses defines from `shmem.h`, it should include it.

**Comment by jdinan** [comment]
I think this issue was always there, since you use the constants defined in `shmem.h` (e.g. collectives constants) with the `pshmem` interfaces.  In this case, including only `pshmem.h` wasn't causing a build error in the SHMEM library, but it would have caused a build failure in application code that used the constants.

**Comment by ax3l** [comment]
I think a separate header makes sense, you don't want to declare symbols you don't use in regular/unprofiled code. This all adds to compile time and symbol clutter.

Nevertheless, if `pshmem.h` needs symbols from `shmem.h` then it needs to include it or alternatively, include just a few selected declarations it needs already. But this detail is opaque to the user, since the "official" *facade* headers are what a user interacts with. Internal organization of declarations and include names can change.

**Comment by jsquyres** [comment]
@ax3l I agree -- I'm not really part of the SHMEM community / don't really care, but to my untrained / outsider eye, a user should either:

```c
#include <shmem.h>
```

or

```c
#include <pshmem.h>
```

If the spec isn't clear on this point (or doesn't define `<pshmem.h>` at all [yet]), then my vote is to do the Simple Thing for users: have them just include a single header file.

**Comment by jdinan** [comment]
I think the choices in front of the committee are roughly what @ax3l described:

1. pshmem.h ensures that any types and constants needed to use the pshmem interfaces are defined
2. pshmem.h ensures that all shmem API symbols, types, and constants are defined
3. profiling interfaces are defined in shmem.h (there is no pshmem.h)

Options 3 needlessly includes hundreds of function prototypes, which may slow down compilers. Option 2 is easy and may be what users of pshmem do anyway.  I think I prefer 1, but my concern is specifying 1 and having 2 become the de facto standard because of assumptions made in user code.

**Comment by wrrobin** [comment]
@jdinan For Option 1, are we allowing the tool developers to include both the headers (pshmem.h and shemem.h) if they want/need to? Or are we going to treat that as a wrong use-case and report error?

**Comment by ax3l** [comment]
@wrrobin yes, that should be possible as well since `shemem.h` might have additional functionality.

**Comment by bertwesarg** [comment]
Looks like this missed the 4.0.1c1. Is it too late again?

**Comment by bertwesarg** [comment]
Please note, that Open MPI is en route with the upcoming profiling interface specification of OpenSHMEM here: https://github.com/openshmem-org/specification/pull/254/commits/53d9a4c33bfc23f1d40f9eee4173a24f6e9086a2

**Comment by bertwesarg** [comment]
This is now in master (#6132 and #6183) and in v4.0.x (#6465). And the profiling interface is alo in the OpenSHMEM specification now (openshmem-org/specification#254). Thus this can be closed now.
