### ISSUE TITLE
"Logically concurrent" -- isn't

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6150]
@dholmes-epcc-ed-ac-uk and I were talking about an issue last night at dinner, and I wanted to record it because it's a serious issue that needs to get fixed.

MPI-3.1 section 3.5 p41:10-17 states:

> If a process has a single thread of execution, then any two communications executed by this process are ordered. On the other hand, if the process is multithreaded, then the semantics of thread execution may not define a relative order between two send operations executed by two distinct threads. The operations are logically concurrent, even if one physically precedes the other. In such a case, the two messages sent can be received in any order. Similarly, if two receive operations that are logically concurrent receive two successively sent messages, then the two messages can match the two receives in either order.

This definition for "logically concurrent" is -- at best -- outdated.  These days, there are absolutely ways to ensure that MPI sends -- even those on the same communicator to the same peer on the same tag -- are ordered, even when executed from distinct threads.  Particularly if the thread level is FUNNELED or SERIALIZED (but yes, even for MULTIPLE, too!).

**Comment by bwbarrett** [comment]
Why is this an Open MPI issue?

But even then, I don't think that the text is at all outdated.  I'm not sure how to define it better, but the issue is two threads, each in MPI_SEND for some overlapping period of time.  There's no guarantee that the one who "called" MPI_SEND first will have its message sent first, without a global lock (and even then, i'm not sure you can guarantee in many cases with NUMA impacts and the like).  Without some type of locally returned counter, there's no way for the sender in this situation to know the order the receiver will receive the messages, even today.

**Comment by jsquyres** [comment]
Sigh.  I filed this in the wrong repo.  I'll explain further when I re-file this on the correct MPI Forum repo...
