### ISSUE TITLE
Does the UCX PML support multirail?

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6255]
I got a random question (off-list) from a user: does the UCX PML support multirail?

https://www.open-mpi.org/faq/?category=openfabrics#run-ucx suggests that it does not, but I figured I'd ask to be sure.

The question was asked in the context of v4.0.0, but I assume the answer is the same for all release branches...?

**Comment by yosefe** [comment]
@jsquyres UCX does support multi-rail. In order to enable it, need to set the following env vars:
* UCX_MAX_EAGER_RAILS=[number of rails to use for eager protocol]
* UCX_MAX_RNDV_RAILS=[number of rails to use for rendezvous protocol]
* UCX_NET_DEVICES=[comma-separated list of network devices to use, syntax device:port]

Example:
`mpirun -x UCX_MAX_EAGER_RAILS=2 -x UCX_MAX_RNDV_RAILS=3 -x UCX_NET_DEVICES=mlx5_0:1,mlx5_1:1 ...`

**Comment by jsquyres** [comment]
Cool.  Can you guys add something like this to the ompi-www FAQ?  Seeing this answer in an Open MPI context is quite valuable.
