### ISSUE TITLE
Crossover from ORTE to PRRTE

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#6317]
I'm creating this ticket to track the crossover from ORTE to PRRTE, just to ensure that future developers can access the conversation and hopefully understand why things were done a certain way.

**Comment by rhc54** [comment]
In prior discussions, we had agreed to:

[ ] embed a copy of PRRTE into OMPI as a top-level project - i.e., we will create a "prrte" directory at the top source dir of the OMPI repo. We may also allow linkage against an external copy of PRRTE, though that might be a follow-on "nice to have".

[ ] move whatever ORTE-level tools we want to retain into the PRRTE tools directory

[ ] completely delete the ORTE directory tree

[ ] add PMIx to the top of the OPAL directory tree. I have already done this in PRRTE and have the necessary configure logic to support it. I'll need to update that logic to allow for an embedded version of PMIx - at the moment, PRRTE requires an external version be provided

[ ] replace all calls to PMIx-related functions with direct use of PMIx, thereby eliminating the opal/pmix framework.

Please edit this list so we have one place where the plan of action is kept! We can have discussion below, but once a decision is made, let's track the plan in this comment so people don't have to read a thousand comments to try and figure out what we are doing.

**Comment by rhc54** [comment]
@hppritcha Does the above plan fit with what you are doing? Since we cannot bring PRRTE into OMPI until we resolve the OPAL duplication problem, I was going to basically copy PRRTE's ORTE onto the OMPI ORTE tree as a starting point. This would allow us to shake out the problems in the interim. Once we know what we are doing with OPAL, all we'd have to do is bring in PRRTE and "rm -rf" the orte tree.

**Comment by ggouaillardet** [comment]
@rhc54 what I have in mind is to move one step at a time.
A first step I can help with is to add a `--prrte-only` option to `ompi` `configure` (or even `autogen.pl`) in order to build `ompi` that only works with an external `prrte`. The idea is to start trimming `orte` without removing files. Obviously, these files will be removed once `--prrte-only` is the only option, and that will be a relatively easy step.

Once this option is implemented, `prrte` can be embedded  as a convenience for the user but will be at first a distinct project, so there is no possibility of mixing both OPAL.

Let me know if you see any value in a `--prrte-only` option I can help with
(since it does not require `prrte` to be embedded, this is indeed independent of OPAL being duplicated or unified)

**Comment by rhc54** [comment]
Sure - that sounds fine with me. Give it a try!

As for mpirun: the MPI standard requires it to be there, so we'll need to at least symlink it to prun. The idea was to hide the prte boot phase by having prun test for a server it can use to launch the specified job - pretty much as it does today. However, if it doesn't find one, then instead of error'ing out like it currently does, it should boot prte instead and then connect to it.

Hope that makes sense.

**Comment by ggouaillardet** [comment]
got it ! I'll give the `--prrte-only` option a try

**Comment by rhc54** [comment]
It isn't absolutely necessary, but I would recommend it. The problem we are going to have to address is all this embedding silliness (IMO) - we're going to wind up having to embed a copy of PRRTE, PMIx, libevent, and hwloc - yet not bury them behind abstractions while still allowing you to substitute an external version of any of them. 🤷‍♂️  😿

**Comment by ggouaillardet** [comment]
can't we basically embeed `pmix`, `libevent` and `hwloc` in sub directories of `contrib`, unconditionally `configure` them (like we currently do in ompi),  and then have ompi treat the embedded components like an external one ?

**Comment by jsquyres** [comment]
@ggouaillardet Be aware that @bwbarrett has promised a document / writeup on a proposal on how to handle all of these things -- not just for PRRTE, but for libevent, hwloc, how we need to formalize the ABI for OPAL, ...etc.  He should be publishing that doc Any Day Now(tm).

**Comment by ggouaillardet** [comment]
`--enable-mpirun-prefix-by-default` is an _alias_ to `--enable-orterun-prefix-by-default` that is defined in `ORTE_CONFIGURE_OPTION` from `config/orte_configure_options.m4`.
So if I simply remove `orte` or does not invoke `ORTE_CONFIGURE_OPTION`, then the option is gone.
Simple reminder to myself : take care of that :-)

**Comment by ggouaillardet** [comment]
@rhc54 I continued the proof-of-concept at https://github.com/ggouaillardet/ompi/tree/poc/noorte.

I implemented the bare minimum so we can `prun` 2 MPI tasks with an ORTE-less Open MPI.
(the implementation is really at proof-of-concept level, some functions are not implemented and shortcuts were taken)

I updated the travis config in order to test with various pmix releases, and it evidenced several issues (see https://travis-ci.com/ggouaillardet/ompi/builds/99536423)

 - `prrte` does not support PMIx < 2, so I guess Open MPI 5 won't either and we simply have to document it
- `prrte` and `ompi` have some compilation issues with PMIx v2 (use of various undefined macros).
  can you confirm `prrte` is supposed to work with PMIx v2 ? If yes, this is likely something I can take care of. Once fixed, shall I update the `prrte` travis config to test with various PMIx releases and/or branches ?
- `prun` hangs with `pmix v3.0` and more than 1 MPI task. I did not investigate yet the root cause. can you confirm there are no known issues with `prrte` and `pmix v3.0` ?

Good news is I was able to make a basic proof-of-concept(ORTE-less Open MPI with - external - libevent, hwloc and pmix as first class citizens), and did not find any blocker.
I will wait for Brian's document before moving forward with respect to OMPI. Meanwhile, I'll be happy to help with `prrte` fixes/improvements.

**Comment by rhc54** [comment]
> prrte does not support PMIx < 2, so I guess Open MPI 5 won't either and we simply have to document it

Correct

> prrte and ompi have some compilation issues with PMIx v2 (use of various undefined macros).
can you confirm prrte is supposed to work with PMIx v2 ? If yes, this is likely something I can take care of. Once fixed, shall I update the prrte travis config to test with various PMIx releases and/or branches ?

It should - we likely are missing some "ifdef" protections for the older versions.

> prun hangs with pmix v3.0 and more than 1 MPI task. I did not investigate yet the root cause. can you confirm there are no known issues with prrte and pmix v3.0 ?

I haven't been testing MPI tasks recently - I also haven't tested against pmix v3.0.  I've been focusing my attention on pmix v3.1, which (last I checked) was working fine with prrte.

**Comment by ggouaillardet** [comment]
thanks, I will take care of the missing ifdef for PMIx v2 support

**Comment by ggouaillardet** [comment]
@rhc54 I updated my branches 
 - https://github.com/ggouaillardet/ompi/tree/poc/noorte
 - https://github.com/ggouaillardet/prrte/tree/topic/pmix2

and got both `prrte` and ORTE-less Open MPI build with the three PMIx `v2` series (well, the latest checkouts from github)

I found :
 - a bunch of PMIx keys are missing in `v2.0` (I did "backport" them via some more `#ifndef` in `opal/pmix/pmix-internal.h`)
 - `PMIX_POINTER` is not correctly handled (or the semantic is not a fit for `prrte`) in `v2.0` and `v2.1`. I guess a workaround is to store pointer as a long, so this is unlikely a blocker.
 - I/O forwarding is not working with all the `v2` branches. `prrte` only relies in `PMIx` I/O forwarding, but this is only available from the `v3` releases and IIRC, the `iof` framework has been removed from `prrte`.


do we still plan to have `prrte` (and hence upcoming Open MPI 5) support __all__ the `v2` series ? If so, some extra effort is required. If not, what should be the new requirement ? `v3.0` ? `v2.2` ? other ?

**Comment by rhc54** [comment]
Please see my comments on your PRRTE branch. The IOF framework has definitely not been removed from PRRTE. However, PRRTE does not support non-PMIx-based tools and so any tool must meet that criterion. It should still include PMIx v2.2, so please let me know if that version isn't working.

It was my intention that PRRTE itself require PMIx v2.2 or above. Note that this doesn't mean a client program cannot be running PMIx v2.0 or 2.1...or even 1.2.5. It just means that PRRTE itself must be built against PMIx v2.2 or above. I'd stick with that plan.

**Comment by ggouaillardet** [comment]
I updated https://github.com/ggouaillardet/prrte/tree/topic/pmix2 based on your comments.
since only PMIx >= v2.2 is supported, the required modifications to support PMIx v2.2 are pretty small.

IOF is still not working with PMIx v2.2.
Since PMIx v2.2 has no IOF features, `prte` relies on `rml` to forward I/O to/from the tool and `rml` relies in turn on `oob/tcp` to do the forwarding, As far as I understand, the tool does not even try to open the `oob` framework, so no `oob/tcp` connection can be established between `prun` and `prte` and the I/O ends up in a black hole.

Is this something you can take care of ?

**Comment by ggouaillardet** [comment]
That will make things way easier !

But if for some reasons we do want pmix 2.2, couldn't we have `prun` establish an `oob/tcp` connection with `prte` for IOF ?

**Comment by rhc54** [comment]
The problem with doing so is that prun would then have to call ```orte_init``` and become an ORTE process - which kinda defeats the purpose. I had thought there was some level of IOF support in PMIx 2, but apparently I remembered incorrectly (too many versions in my head). I would just stick with the v3 minimum requirement. Should probably update configure to enforce it.

**Comment by gpaulsen** [comment]
Closing as resolved in master and v5.0.x
