### ISSUE TITLE
undefined reference, underlinking, -Wl,--no-undefined

### ISSUE THREAD

**Issue by nschloe** [open-mpi/ompi#648]
When linking Open MPI with `-Wl,--no-undefined`, I'm getting errors of the kind
```
/«PKGBUILDDIR»/opal/mca/compress/gzip/compress_gzip_component.c:121: undefined reference to `opal_compress_base_framework'
/«PKGBUILDDIR»/opal/mca/compress/gzip/compress_gzip_component.c:127: undefined reference to `opal_output_verbose'
/«PKGBUILDDIR»/opal/mca/compress/gzip/compress_gzip_component.c:129: undefined reference to `opal_output_verbose'
/«PKGBUILDDIR»/opal/mca/compress/gzip/compress_gzip_component.c:132: undefined reference to `opal_output_verbose'
/«PKGBUILDDIR»/opal/mca/compress/gzip/compress_gzip_component.c:117: undefined reference to `opal_output_open'
/«PKGBUILDDIR»/opal/mca/compress/gzip/compress_gzip_component.c:118: undefined reference to `opal_output_set_verbosity'
```
This is from [a launchpad build](https://launchpadlibrarian.net/209451020/buildlog_ubuntu-wily-amd64.openmpi_1.8.6~201506182208-wily1_BUILDING.txt.gz). These errors indicate that some libraries (in this case `libs/mca_compress_gzip.so`) are not properly linked.

**Comment by rhc54** [comment]
What version of OMPI?

**Comment by jsquyres** [comment]
Thanks for reporting.  A few notes:

1. I see that you're running `autogen.sh` in the build process of a 1.8.6 tarball.  This shouldn't be necessary; we don't advise it unless you really want/need to.  The normal `configure ...; make install` process should work without re-bootstrapping the GNU Autotools.
1. You're seeing underlinking of a plugin (i.e., the `compress_gzip` plugin).  It's linked against all of its external dependent libraries (i.e., `-lz`), but it's intentionally *not* linked against the rest of the Open MPI code base (i.e., where symbols like `opal_output_open` and friends live).  The reason is because plugins like this are dlopen'ed into the process scope where these symbols will be resolved because the rest of the Open MPI library symbols will already be in the process.  If we link our plugins against the main Open MPI library, Bad Things happen in corner cases (e.g., when plugins are included in static libraries, or users dlopen the main Open MPI library, etc.).

My advice would be to turn off the -Wl,--no-undefined check in for the Open MPI build.

**Comment by nschloe** [comment]
Thanks for the comments.
I now deactivated `-Wl,-no-undefined` (although I don't yet fully understand the reasoning behind). Anyhow, the reason why I started this in the first place were other undefined references, see [this build log](https://launchpadlibrarian.net/209458132/buildlog_ubuntu-wily-amd64.openmpi_1.8.6~201506182340-wily1_BUILDING.txt.gz).
```
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:35: undefined reference to `opal_dl_open'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:37: undefined reference to `opal_dl_close'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:45: undefined reference to `opal_dl_open'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:47: undefined reference to `opal_dl_close'
```
Any idea what might be going wrong?

**Comment by jsquyres** [comment]
I'm still digging into this, but I have some more questions:

* I notice that you're supplying `--with-devel-headers` on your `dh_auto_configure` line. Are you doing that for a reason?  That option should only be necessary for Open MPI plugin developers -- it's not necessary for MPI application developers.  Specifically: without this option, Open MPI will still install `mpi.h` and whatever other headers MPI app developers need to compile MPI programs.
* Unless you have a strong reason to, you *really* shouldn't be running `autogen.pl`.  The Open MPI release tarballs are bootstrapped properly back at the factory.  I mention this because the `configure` script you run emits a troubling warning:

```
configure: WARNING: unrecognized options: --disable-maintainer-mode, --with-threads, --disable-vt
```

Specifically: the `--with-threads` and `--disable-vt` options are valid with Open MPI's stock `configure` script; you should *not* be getting warnings that they do not exist.  Additionally, you're passing `--disable-silent-rules`, but only *some* of the silent rules appear to be disabled during your build.  These two things together means that your invocation of `autogen.pl` has significantly altered Open MPI's configure in ways that we did not intend.  This is a big red flag.

* All that being said, I see that the failure is occurring during `make check` (inserted line breaks below for readability):

```
libtool: link: gcc -std=gnu99 -DNDEBUG -fstack-protector-strong -Wformat 
-Werror=format-security -fno-strict-aliasing -pthread -g 
-Wl,-Bsymbolic-functions -Wl,-z -Wl,relro 
-o .libs/dlopen_test dlopen_test.o  
-L/usr//lib ../../ompi/.libs/libmpi.so 
-lrt -lm -lutil -lhwloc -pthread 
-Wl,-rpath -Wl,/usr/lib/openmpi/lib
dlopen_test.o: In function `try_open':
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:35: undefined reference to `opal_dl_open'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:37: undefined reference to `opal_dl_close'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:45: undefined reference to `opal_dl_open'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:47: undefined reference to `opal_dl_close'
dlopen_test.o: In function `main':
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:133: undefined reference to `opal_init'
/«PKGBUILDDIR»/ompi/debuggers/dlopen_test.c:135: undefined reference to `opal_finalize'
collect2: error: ld returned 1 exit status
```

That test is (correctly) linking in `libmpi.la`.  `libmpi.la` is linked against `libopen-rte.la`, which is, in turn, linked against `libopen-pal.la`.  Hence, the test linking in `libmpi.la` should implicitly pull in `libopen-pal.la`, which contains those symbols.

In the output above, you can see that Libtool is correctly translating `libmpi.la` into `../../ompi/.libs/libmpi.so`.  If you run `ldd` on this file, it should show a dependency on `libopen-rte.so`, and if you run `ldd` on *that* file, it should show a dependency on `libopen-pal.so`.  That's how the `opal_*` symbols are supposed to get resolved.

As to why that is happening, I'm not sure.  Can you try again without re-running `autogen.pl`?  Perhaps it's your local versions of the GNU Autotools that are misbehaving...?

**Comment by nschloe** [comment]
Thanks Jeff for the feedback!

The reason why I'm digging into this is that I'd like to bring the Debian Open MPI package up to speed (it's still at 1.6 for all releases). I'm picking up where the last dev has left, so possibly the build file will include stuff that's not really necessary like

> I notice that you're supplying `--with-devel-headers`

I've removed that.

> Unless you have a strong reason to, you really shouldn't be running `autogen.pl`.

I'm building Open MPI master, so I'll have to run `autogen.pl` there. The plan is that once the build consolidates, I'll run this on the Open MPI release and remove the call to `autogen.pl`. Now that you mention that this might be the cause for the trouble, I'll try with the release straight away.

**Comment by jsquyres** [comment]
@nschloe Ok, sweet.  By "master", I assume you mean "a git checkout of the v1.8 tag on the ompi-release repo", right?  If so, can you try with an Open MPI 1.8.6 tarball?  (I think that that is what you were saying you were going to do, but I just want to make sure :smile: )

**Comment by nschloe** [comment]
Indeed. [Running right now](https://launchpad.net/~nschloe/+archive/ubuntu/openmpi-nightly/+build/7561249).

**Comment by jsquyres** [comment]
@nschloe Looks like that build succeeded in all the ways that it failed before, but then failed because the ompi-iof executable wasn't found.  We haven't included ompi-iof in quite a while -- is this some kind of specific artifact in your build process, perchance?

**Comment by nschloe** [comment]
Indeed. I was now able to complete [a successful built](https://launchpadlibrarian.net/209773976/buildlog_ubuntu-wily-amd64.openmpi_1.8.6~201506231003-wily1_BUILDING.txt.gz), too. There are probably a bunch of things that need to improve, but we'll come back to that later.

Now, I'm still wondering why the build from [master](https://github.com/open-mpi/ompi) doesn't go through in the same way.

**Comment by jsquyres** [comment]
Ok.

Do you need any help with master?  Or should we close this issue?

**Comment by jsquyres** [comment]
I'll close the issue -- feel free to open a new issue if something comes up.
