### ISSUE TITLE
Cannot build libmpi_usempif08.so.0 and libmpi_usempi_ignore_tkr.so.0

### ISSUE THREAD

**Issue by kim0** [open-mpi/ompi#649]
Hi,

Sorry if this is not really a bug, but perhaps a config error. I am building openmpi 1.8.3 and 1.8.6 and passing --enable-mpi-fortran=all .. But I am unable to locate the following 2 libs:

libmpi_usempi_ignore_tkr.so.0
libmpi_usempif08.so.0   

which are needed by a commercial application I'm trying to get running. Any hint please why doesn't make generate these 2 so's .. Thanks!

**Comment by jsquyres** [comment]
You must use a "recent enough" Fortran compiler to get support for these two libraries.  If you're using an older Fortran compiler (e.g., gfortran <4.9), you'll be forced into a legacy implementation of the `use mpi` Fortran bindings, and the `mpi_f08` bindings won't be built at all.

See https://github.com/open-mpi/ompi/blob/master/README#L357-L400 for the full story.

Is there a reason you're looking for the specific libraries?  You should be able to `use mpi`, regardless of whether you have the new or legacy implementation of the `mpi` module and the back-end library name will be different (although, as stated above, the `mpi_f08` bindings won't be there if you use an older compiler).

I ask because we usually try to hide the specific library names from applications -- we strongly recommend that you use the `mpifort` wrapper compiler to link in all the relevant libraries for you (or use `mpifort --showme:FOO` to extract relevant flags).

**Comment by kim0** [comment]
Thanks a lot for the help! I'm trying to install a commercial app (lsdyna) that links against those 2 specific libraries (see below). Although the file name specifically mentions ompi183 .. It also mentions ifort so not sure if that's a cause of the problem .. Let me know your thoughts.. Thanks

ldd ./ls-dyna_mpp_d_r8_0_0_95359_x64_redhat54_ifort131_avx2_openmpi183
        linux-vdso.so.1 =>  (0x00007fff5cbff000)
        librt.so.1 => /lib64/librt.so.1 (0x0000003eab000000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00000030a7800000)
        libmpi_usempif08.so.0 => not found
        libmpi_usempi_ignore_tkr.so.0 => not found
        libmpi_mpifh.so.2 => /usr/lib64/libmpi_mpifh.so.2 (0x00007f74ce1b1000)
        libmpi.so.1 => /usr/lib64/libmpi.so.1 (0x00007f74cdeda000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003eaa000000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003eaa400000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003eaa800000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003ea9c00000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003ea9800000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00000030a6c00000)
        libopen-rte.so.7 => /usr/lib64/libopen-rte.so.7 (0x00007f74cdc60000)
        libopen-pal.so.6 => /usr/lib64/libopen-pal.so.6 (0x00007f74cd990000)
        libutil.so.1 => /lib64/libutil.so.1 (0x0000003eb5800000)

**Comment by ggouaillardet** [comment]
@kim0 please be aware there is no binary compatibility between gfortran (gnu) and ifort (intel)

so if ls-dyna was built with ifort, it was also built vs openmpi built with ifort.

bottom line, you should build openmpi with ifort to get the desired results
( you can use ompi 1.8.3 or 1.8.6 since they are binary compatible)

**Comment by kim0** [comment]
@ggouaillardet @jsquyres .. Thanks a lot folks, your help is most appreciated. I think this can be marked resolved now. Thanks a lot
