### ISSUE TITLE
MPI_File_set_view lacking "external32" and "internal" representation support in ompio

### ISSUE THREAD

**Issue by cniethammer** [open-mpi/ompi#6558]
### What version of Open MPI are you using?

Open MPI 4.0.1

## Details of the problem

MPI_File_set_view from the default ompio io module does not support the "external32" and "internal" data representation. See implementation in *io/ompio/io_ompio_file_set_view.c*.
However, this problem shows only up on NFS file systems for me with the attached test program.

```c
#include <mpi.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  MPI_Init(&argc, &argv);

  MPI_Comm comm = MPI_COMM_WORLD;
  int amode = MPI_MODE_CREATE | MPI_MODE_RDWR;
  char filename[] = "test.dat";
  MPI_Info info = MPI_INFO_NULL;
  MPI_File fh;
  MPI_File_open(comm, filename, amode, info, &fh);
  MPI_Offset disp = 0;
  MPI_Datatype etype = MPI_CHAR;
  MPI_Datatype filetype = MPI_CHAR;
  char datarep_external32[] = "external32";
  int ret = MPI_File_set_view(fh, disp, etype, filetype, datarep_external32, info);
  printf("Set view %s returend %d\n", datarep_external32, ret);
  char datarep_internal[] = "internal";
  ret = MPI_File_set_view(fh, disp, etype, filetype, datarep_internal, info);
  printf("Set view %s returend %d\n", datarep_internal, ret);
  printf("MPI_ERR_UNSUPPORTED_DATAREP = %d\n", MPI_ERR_UNSUPPORTED_DATAREP);
  MPI_File_close(&fh);
  MPI_Finalize();
  return 0;
}
```

**Comment by edgargabriel** [comment]
Hi Christoph, I can confirm that external32 is not supported at this point in time in ompio, this is however also described in the FAQ as a current limitation of ompio along with switching the atomicity level of operations. It is on my to-do list for quite a while, but since it is a truly rarely used feature, I have a hard time justifying investing the time and efforts for this. (To give an idea on how rarely this is used, this is the 2nd time it is being mentioned on the mailing list in ~10 years). 

In addition, ROMIO does support this, so in theory we (i.e. Open MPI ) has a solution for this scenario by simply using the romio  component.

**Comment by edgargabriel** [comment]
@cniethammer : I wanted to give an update on this item, and also use this opportunity to document the current status. I committed yesterday support for the external32 representation for ompio into master, so it should be available in the next major release of Open MPI (v.5.0  most likely).

As a sideeffect of this work, I did also develop and run numerous tests with external32 with both ompio and romio321, and what I found with romio is, that (at least with the Open MPI version) they do support external32 but only for blocking operations. All of the tests that I ran using non-blocking MPI File I/O using the external32 representation and romio321 failed.

For ompio, I do have support for external32 for blocking and non-blocking individual I/O, shared file pointers, and blocking collective I/O. The only item that is not implemented is non-blocking collective I/O (including split-collectives). which is surprisingly tricky especially for read operations.
