### ISSUE TITLE
how to use mpirun in multiple servers with different ports?

### ISSUE THREAD

**Issue by gdfishhannah** [open-mpi/ompi#6586]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
openmpi-4.0.0
### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Installed by dafault of horovod Docker file

### Please describe the system on which you are running

* Operating system/version: 
ubuntu16.04
* Computer hardware: 
V100GPU+
* Network type: 
docker host network
-----------------------------

## Details of the problem

I am trying to run horovod in multiple containers on multiple servers throught different ports, but I can only find the way to run through one port.

I run this in the first container.
horovodrun -np 16 -H localhost:8,host01:8 python keras_mnist_advanced.py
or
mpirun --allow-run-as-root -np 4 -H host01:2,host02:2 --mca plm_rsh_args "-p 22339" --mca btl_tcp_if_include ens10f1 -x LD_LIBRARY_PATH python keras_mnist_advanced.py

Is there any way to assign different port to host01 and host02?

**Comment by rhc54** [comment]
I'm afraid I don't know of any way to accomplish this.

**Comment by gpaulsen** [comment]
@gdfishhannah, Thanks for submitting your question.

  I'm sorry the functionality you're looking has never been implemented in *orte*.  We're not opposed to such a new feature, but we just don't currently have that today.

**Comment by jjhursey** [comment]
Just to clarify one point in the issue description:
Do you just need a different rsh/ssh port per server for your use case (in order to facilitate orted launch across the containers)? Are there any firewall restrictions in place between containers that would further restrict point-to-point communication over dynamic ports between processes in different containers?

The OOB/TCP and BTL/TCP components (which handle point-to-point communication once the orted's are launched) do have support for a single fixed port or a range of ports to use for communication. If you need this to also be unique per host then there is additional work here as well.

If you are looking to explore an implementation of this feature the `orte/mca/plm/rsh` component would be where the `plm_rsh_args` option is being processed. The `orte/mca/oob/tcp` and `opal/mca/btl/tcp` would handle the point-to-point communication for the daemons and MPI processes, respectively.

**Comment by gdfishhannah** [comment]
@jjhursey Is there any more information about the orte/mca/oob/tcp and opal/mca/btl/tcp? How should I add args?

**Comment by jsquyres** [comment]
Can you explain further what you're trying to do?  We're clearly confused by what you're asking.

As Josh explained, Open MPI uses several channels for network communication between hosts.  It is not possible to only allow a single port between hosts; you will need multiple.  This is why @rhc54 and @gpaulsen said that we do not have the feature that you are looking for.  But based on your limited reply to @jjhursey, it seems like you are looking for something different.  Can you describe in more detail what you are trying to do?
