### ISSUE TITLE
srun no longer support --cpu_bind in 19.05

### ISSUE THREAD

**Issue by mdong** [open-mpi/ompi#6743]
Hi, 

Slurm 19.05.0 no longer support --cpu_bind, it only support --cpu-bind now:
```
$ srun --version
slurm 19.05.0
$ srun --cpu_bind=none
srun: unrecognized option '--cpu_bind=none'
srun: unrecognized option '--cpu_bind=none'
Try "srun --help" for more information
```

It is still supported on 18:

```
$ srun --version
slurm 18.08.1
$ srun --cpu_bind none
srun: fatal: No command given to execute.
```

This change cause mpirun with slurm to error out with:
```
[wahab-01:73173] mca:base:select: Auto-selecting plm components
[wahab-01:73173] mca:base:select:(  plm) Querying component [isolated]
[wahab-01:73173] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[wahab-01:73173] mca:base:select:(  plm) Querying component [rsh]
[wahab-01:73173] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[wahab-01:73173] mca:base:select:(  plm) Querying component [slurm]
[wahab-01:73173] mca:base:select:(  plm) Query of component [slurm] set priority to 75
[wahab-01:73173] mca:base:select:(  plm) Selected component [slurm]
[wahab-01:73173] mca: base: close: component isolated closed
[wahab-01:73173] mca: base: close: unloading component isolated
[wahab-01:73173] mca: base: close: component rsh closed
[wahab-01:73173] mca: base: close: unloading component rsh
srun: unrecognized option '--cpu_bind=none'
srun: unrecognized option '--cpu_bind=none'
Try "srun --help" for more information
--------------------------------------------------------------------------
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
[wahab-01:73173] mca: base: close: component slurm closed
[wahab-01:73173] mca: base: close: unloading component slurm
```

This breaks mpirun under Slurm 19+ while execute with srun directly would still work, could you please update following line? Thanks for all the good work.  

https://github.com/open-mpi/ompi/blob/98afc838aa53da88cba339f6dcbab256806a5745/orte/mca/plm/slurm/plm_slurm_module.c#L281

**Comment by jsquyres** [comment]
Greetings @mdong; thanks for reporting the issue.

This was actually previously reported and fixed in our code base (in master and the v3.0.x, v3.1.x, and v4.0.x release branches).  None of these branches have had a release yet that includes the fixes; the next release on all of these branches will include the fix.  In the meantime, nightly snapshot tarballs of each of them are available on the Open MPI web site:

* https://www.open-mpi.org/software/ompi/v4.0/ and
* https://www.open-mpi.org/software/ompi/v3.1/ and
* https://www.open-mpi.org/software/ompi/v3.0/ , respectively

I'm going to close this issue as a duplicate (originally reported here: https://github.com/open-mpi/ompi/pull/6654); but thank you for running down the issue and reporting it in detail!
