### ISSUE TITLE
Question about assumed-rank assumed-type

### ISSUE THREAD

**Issue by wangzpgi** [open-mpi/ompi#6788]
I have a question about how assumed rank array and assumed type is being used in OpenMPI. I am building openmpi 3.1.3, and I can see that in the configuration step, it checks whether the compiler being used supports `dimension(..), type(*)`, however once it's verified, I don't see this syntax being used anywhere in the source code. Only one place mentions about assumed-rank is "gen-mpi-sizeof.pl" where it does not use this syntax after all. Could you please let me know why this syntax needs to be checked in the configuration step? Thanks.

**Comment by jsquyres** [comment]
The `gen-mpi-sizeof.pl` script is used to generate the relevant Fortran bindings for MPI_SIZEOF.  The only place that `TYPE(*), DIMENSION(..)` is mentioned in there is in the comments (saying that if all compilers supported `TYPE(*), DIMENSION(..)`, this script wouldn't be necessary 😄).

Open MPI currently uses "ignore TKR"-style directives for choice buffers, not 'TYPE(*), DIMENSION(..)'.

It's on the to-do/someday list to add real support for 'TYPE(*), DIMENSION(..)`.

I think we added that configure check when we had an active Fortran person working on the code, and the thought was that `TYPE(*),DIMENSION(..)` support could have been added in that timeframe.  Unfortunately, it didn't happen back then, and has kinda fallen lower on the priority list since then.

**Comment by wangzpgi** [comment]
Thank you very much for your explanation. Now it makes sense.

**Comment by jsquyres** [comment]
@wangzpgi Actually, @ggouaillardet literally just updated an old PR as a first foray into supporting this kind of stuff.  If you're interested, have a look at https://github.com/open-mpi/ompi/pull/6569.

I would imagine that this stuff would be destined for Open MPI v5.0.x at the earliest -- not the v4.0.x series.

**Comment by wangzpgi** [comment]
@jsquyres Thanks for your updated information!
