### ISSUE TITLE
Promised environment variables not set without ORTE

### ISSUE THREAD

**Issue by krempel-pt** [open-mpi/ompi#6875]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using?
4.0.1

### Describe how Open MPI was installed
installed from source tarball
configured with --enable-debug --with-pmix=[...]/pmix-3.1.4rc2/install --with-libevent=/usr --with-ompi-pmix-rte --with-orte=no

### Please describe the system on which you are running

* Operating system/version: Fedora release 29
* Computer hardware: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
* Network type: not used

-----------------------------

## Details of the problem
In the FAQ it is promised, that the following environment variables will be defined on every MPI process:
* OMPI_COMM_WORLD_SIZE
* OMPI_COMM_WORLD_RANK
* OMPI_COMM_WORLD_LOCAL_RANK
* OMPI_UNIVERSE_SIZE
* OMPI_COMM_WORLD_LOCAL_SIZE
* OMPI_COMM_WORLD_NODE_RANK

With ORTE this seems to be correct, but without it is not. I think these variables should be set by MPI_Init and not by the RTE, so their existence would be independent of the used RTE.

**Comment by rhc54** [comment]
I'm afraid doing as you suggest would somewhat defeat the purpose of those envars. They were created in response to user requests for access to that information _prior_ to calling `MPI_Init`, and hence are set by the RTE prior to exec of the binary. On the plus side, any RTE can set them if they so choose - because they are prefixed with `OMPI_` they should not interfere with non-OMPI applications.

If the FAQ doesn't explain that, then someone from OMPI (@jsquyres perhaps?) should update the FAQ.

**Comment by ggouaillardet** [comment]
Ralph,

Should Open MPI documents the PMIx environment variables instead?
This is more likely what end-users are looking for, and they are also set by PMIx enabled resource managers that features direct launch (such as srun under SLURM)

Cheers,

Gilles

On August 8, 2019, at 11:35 PM, Ralph Castain <notifications@github.com> wrote:

I'm afraid doing as you suggest would somewhat defeat the purpose of those envars. They were created in response to user requests for access to that information prior to calling MPI_Init, and hence are set by the RTE prior to exec of the binary. On the plus side, any RTE can set them if they so choose - because they are prefixed with OMPI_ they should not interfere with non-OMPI applications.

If the FAQ doesn't explain that, then someone from OMPI (@jsquyres perhaps?) should update the FAQ.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/open-mpi/ompi/issues/6875?email_source=notifications">https://github.com/open-mpi/ompi/issues/6875?email_source=notifications</a>\u0026email_token=ABXF52ZKYK4CIKJ37JU2W3TQDQVL3A5CNFSM4IKA6FKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD332HCA#issuecomment-519545736", "url": "<a href="https://github.com/open-mpi/ompi/issues/6875?email_source=notifications">https://github.com/open-mpi/ompi/issues/6875?email_source=notifications</a>\u0026email_token=ABXF52ZKYK4CIKJ37JU2W3TQDQVL3A5CNFSM4IKA6FKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD332HCA#issuecomment-519545736", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by rhc54** [comment]
I don't believe PMIx sets envars corresponding to those values - we only set the minimum required for connection purposes. AFAIK, it consists of the server URI, plus the nspace/rank of the process - only covers one of the OMPI-related envars.

**Comment by rhc54** [comment]
If you are asking if we should document those, then I guess we could - just not sure what a user would do with that info.

**Comment by rhc54** [comment]
> In fact I would feel much more comfortable with a solution like @ggouaillardet proposed, setting PMIX_ envars with information a user might what to know before MPI_Init, like the size of the universe, the number of lokal processes and so on.

But that is precisely what is being done. MPI_COMM_WORLD is precisely defined by the MPI Standard - thus, the RTE knows exactly what the assigned values will be within that application. Yes, the app may define other communicators which will have their own values, but that is beside the point.

Note that PMIx has no better info available to it than the RTE when it comes to these matters - we get our info directly from the RTE (e.g., the "rank" is what the RTE tells us it is). We don't have any concept of MPI in PMIx.

> First I cannot imagine any reason why not to call MPI_Init at the very beginning when writing an MPI program. 

I guess others disagree as we encounter it pretty often 😄 Calling MPI_Init at the beginning isn't required and often isn't done until one gets to the MPI portion of the application.

> Can you point me to the request after that this variables have been introduced, just for a better understanding?

Those variables were introduced nearly 15 years ago now - I honestly have no idea how to point you to the original request.

**Comment by rhc54** [comment]
I should say that if the OMPI team wants PMIx to provide those envars, we certainly can do so - at least in the reference implementation, there is no restriction that would prevent it. They would simply need to contribute an appropriate plugin for that purpose. However, we can do no better than the RTE in setting them - they would get set for every application (OMPI or not) based on the info provided by the RTE.

I suppose the only benefit would be that any PMIx-enabled RTE would then provide those envars without having to write that code themselves.

**Comment by krempel-pt** [comment]
> But that is precisely what is being done. MPI_COMM_WORLD is precisely defined by the MPI Standard - thus, the RTE knows exactly what the assigned values will be within that application. Yes, the app may define other communicators which will have their own values, but that is beside the point.
> 
> Note that PMIx has no better info available to it than the RTE when it comes to these matters - we get our info directly from the RTE (e.g., the "rank" is what the RTE tells us it is). We don't have any concept of MPI in PMIx.

Yes, that's clear to me, and the reason why I would say you cannot provide OMPI_ variables there at all, you can only provide PMIX_ variables indicating that this is the knowledge of PMIx. But of cause, this makes is slightly more complicated from the users point of view.

> > First I cannot imagine any reason why not to call MPI_Init at the very beginning when writing an MPI program.
> 
> I guess others disagree as we encounter it pretty often  Calling MPI_Init at the beginning isn't required and often isn't done until one gets to the MPI portion of the application.

In fact, as I read the MPI standard, it is required if you need information about MPI communicator size, your rank and so on, because those information are available via function calls that require MPI_Init to be called first. :sunglasses: 

> 
> > Can you point me to the request after that this variables have been introduced, just for a better understanding?
> 
> Those variables were introduced nearly 15 years ago now - I honestly have no idea how to point you to the original request.

Ok, thanks.
