### ISSUE TITLE
Implement regx/zlib component

### ISSUE THREAD

**Issue by sam6258** [open-mpi/ompi#6936]
Create a new, non-default regx component in the v4.0.x and v3.1.x branches that compresses the node/vpid string using zlib and communicates the compressed string all of the time (doesn't send over command line).

Motivation for this component is a functional path where fwd, reverse regx components fail. See discussion on https://github.com/open-mpi/ompi/pull/6915 for more info.

**Comment by gpaulsen** [comment]
I'm not sure we'd want to change a framework API on a release branch.
If that's true, and since this isn't needed on master, I think the only other possibility would be to somehow engineer this new proposed component in a way that it can keep with the existing regex framework on v3.x and v4.x.
That might be possible if we use zlib to compress the data, and then use an encoding / decoding phase to wrap the compressed data.  But at that point, it seems like this might be to risky to add to a release branch.
Lets keep this issue open in case someone else can come up with a good design.

**Comment by hppritcha** [comment]
We don't plan to implement this in the v4.0.x and older series.

**Comment by jsquyres** [comment]
Would this be a PRTE issue now (and not an Open MPI issue)?

**Comment by jjhursey** [comment]
AFAIK PRRTE already uses zlib (where available) to compress this information. If zlib is not available then it is sent in an uncompressed form. There is no custom regex parser any longer.
