### ISSUE TITLE
mpijavac command not found

### ISSUE THREAD

**Issue by sap9433** [open-mpi/ompi#7098]
Thank you for taking the time to submit an issue!

## Background information
I wonder why people put so much effort to write complex technologies, and then have such a vague readme file that undermines their effort and acts as such a huge barrier for mass adaptation.

Its java readme says - if you do following then you can compile using `mpijavac`. But wait ? where do I get `mpijavac` from, it gives you `command not found: mpijavac`. Waste of time.
- brew install Automake
- ./autogen.pl
- ./configure --enable-mpi-java

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

```
mpirun (Open MPI) 4.0.1

Report bugs to http://www.open-mpi.org/community/help/
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

`brew install open-mpi`

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------
MACOS Catalina

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by jsquyres** [comment]
That's a pretty rude comment.

You didn't even fill out all the information that we ask for, so I don't know what version you're reporting about, how you installed Open MPI, ...etc.

We're always happy to receive suggestions and bug reports, but snippy comments without any substantive detail for us to replicate the potential problem aren't helpful.  I'm actually not even sure: are you asking for help, or just letting us know that you tried to use mpiJava and failed?  ☹️

**Comment by ggouaillardet** [comment]
@sap9433 If you had read and understood the `README.JAVA.txt` you would have noted

> The Java bindings will build only
if --enable-mpi-java is specified, and a JDK is found in a typical
system default location.

or at least noticed the `--enable-mpi-java` option (there is an occurence only 8 lines before `mpijavac` is mentioned).

I do not think only a genius can figure out `mpijavac` won't be built unless the the Java bindings are built.



> [...] and acts as such a huge barrier for mass adaptation

You obviously did not get it, and once again, `README.JAVA.txt` is self explanatory on that point.

**Comment by jsquyres** [comment]
@sap9433 Ah, you went back and edited the initial description and added more information (Github doesn't notify us when you do that; I only just happened to notice it when I logged in this morning).

I'm confused about how you installed Open MPI.  You mention two different ways with no additional detail:

1. `./configure --enable-mpi-java` (this is how Open MPI was configured, but not how it was built or installed)
2. `brew install open-mpi`

If you installed Open MPI via Homebrew, then the issue is going to be related to however Homebrew chose to package Open MPI (e.g., whether they chose to `--enable-mpi-java` or not).  That's a downstream decision from us; we do not have control over that.

Can you clarify your question please?

* Are you asking for assistance on how to get the MPI Java bindings installed?
* Are you asking us to fix something in our documentation?
* ...something else?
