### ISSUE TITLE
Truckloads of OPAL atomic warnings with icc 2019

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7223]
When compiling the Open MPI master with icc 2019.4.227, I get truckloads of warnings like this (for just about every file in the OMPI tree -- I picked a random file's warnings to show below):

```
In file included from ../../opal/class/opal_object.h(126),
                 from ../../opal/util/output.h(75),
                 from path.c(76):
../../opal/threads/thread_usage.h(156): warning #2330: argument of type "opal_atomic_int32_t={_Atomic(int32_t={int})} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OPAL_THREAD_DEFINE_ATOMIC_COMPARE_EXCHANGE(int32_t, int32_t, 32)
  ^

In file included from ../../opal/class/opal_object.h(126),
                 from ../../opal/util/output.h(75),
                 from path.c(76):
../../opal/threads/thread_usage.h(157): warning #2330: argument of type "opal_atomic_intptr_t={_Atomic(intptr_t={long})} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OPAL_THREAD_DEFINE_ATOMIC_COMPARE_EXCHANGE(intptr_t, intptr_t, ptr)
  ^

In file included from ../../opal/class/opal_object.h(126),
                 from ../../opal/util/output.h(75),
                 from path.c(76):
../../opal/threads/thread_usage.h(158): warning #2330: argument of type "_Atomic(unsigned int) *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OPAL_THREAD_DEFINE_ATOMIC_SWAP(int32_t, int32_t, 32)
  ^

In file included from ../../opal/class/opal_object.h(126),
                 from ../../opal/util/output.h(75),
                 from path.c(76):
../../opal/threads/thread_usage.h(159): warning #2330: argument of type "_Atomic(unsigned long) *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OPAL_THREAD_DEFINE_ATOMIC_SWAP(intptr_t, intptr_t, ptr)
  ^

In file included from ../../opal/class/opal_object.h(126),
                 from ../../opal/util/output.h(75),
                 from path.c(76):
../../opal/threads/thread_usage.h(217): warning #2330: argument of type "opal_atomic_int64_t={_Atomic(int64_t={long})} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OPAL_THREAD_DEFINE_ATOMIC_COMPARE_EXCHANGE(int64_t, int64_t, 64)
  ^

In file included from ../../opal/class/opal_object.h(126),
                 from ../../opal/util/output.h(75),
                 from path.c(76):
../../opal/threads/thread_usage.h(218): warning #2330: argument of type "_Atomic(unsigned long) *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OPAL_THREAD_DEFINE_ATOMIC_SWAP(int64_t, int64_t, 64)
  ^
```

There's a few layers of macros and standard C++ functions here that I don't quite grok -- can someone look into this and see what the issue is?

**Comment by jsquyres** [comment]
This came up in another context in June of 2020.

Given the sheer volume of warning messages when compiling with the Intel compiler, this should be fixed before v5.0.

**Comment by hjelmn** [comment]
Will take a look.

**Comment by hjelmn** [comment]
Looking at the code I don't see how this is possible. The only way we could have something that is volatile in the atomic path is if C11 is not available. In that case all the atomic types are ```volatile whatever```. There must be some header order which breaks things. Will log onto a LANL system and see what the issue is.

**Comment by jsquyres** [comment]
Thanks @hjelmn!

@bosilca suggested to me in Slack that this might be the fix -- I'm testing now:

```patch
diff --git a/ompi/request/request.h b/ompi/request/request.h
index c0a94a7925..bafdc9c8dd 100644
--- a/ompi/request/request.h
+++ b/ompi/request/request.h
@@ -126,7 +126,7 @@ struct ompi_request_t {
     opal_free_list_item_t super;                /**< Base type */
     ompi_request_type_t req_type;               /**< Enum indicating the type of the request */
     ompi_status_public_t req_status;            /**< Completion status */
-    volatile void *req_complete;                /**< Flag indicating wether request has completed */
+    opal_atomic_intptr_t req_complete;          /**< Flag indicating if therequest has completed */
     volatile ompi_request_state_t req_state;    /**< enum indicate state of the request */
     bool req_persistent;                        /**< flag indicating if the this is a persistent request */
     int req_f_to_c_index;                       /**< Index in Fortran <-> C translation array */

**Comment by hjelmn** [comment]
That definitely fixes an issue but the warning above looks like an error in the actual definition of the opal_thread functions. Maybe that is fixed? If not I can try icc in a bit. Not a compiler I use ever as gcc and clang are better (for my definition of better).

**Comment by bosilca** [comment]
I could reproduce on one of my systems. I'll take a look.

**Comment by hjelmn** [comment]
Alright, thank you George. Seems like something specific to icc and how we detect the C11 atomics since this doesn't happen with compilers that are not icc. They were one of the last to actually support C11 atomics as defined in the standard. Though they did for awhile set the defines as if they were correctly implemented when they were not.

**Comment by bosilca** [comment]
After spending few hours trying to understand what is going on, I have to say I'm still mitigated on what is the correct approach and how to fix it. The rest of this discussion applies only when using C11 atomic support.

We make a strong assumption that [_Atomic](https://en.cppreference.com/w/c/language/atomic) implies [volatile](https://en.cppreference.com/w/c/language/volatile). As an example, all types used in any atomic operations are declared with the _Atomic qualifier. That would be fine, if we used the _Atomic aspect of it (such as using operations that would be converted by the compiler into their atomic counterpart, aka ++ into atomic inc), but we don't. Instead, we manipulate these variables via atomic operations, which in C11 [do not require the _Atomic qualifier](https://en.cppreference.com/w/c/atomic) on their argument, but volatile. We get a free pass on most compilers, except Intel where _Atomic and volatile are somewhat conflicting qualifiers (as the warning indicates type "opal_atomic_int32_t={_Atomic(int32_t={int})} *" is incompatible with parameter of type "volatile int32_t={int} *"

I mussed with few solutions, none of them clear and nice.
1. We can redefine our atomic types to be volatile (by replacing the _Atomic qualifier with volatile. This is incorrect because I think we are taking advantage of automatic atomic operations on these variables (++ translate into an atomic inc).
1. Disable the 2330 warning if we detect the intel compiler. Unfortunately if we could do it in a single file, this could have been a reasonable solution, but out macros are scattered across the code base, and we would need to pollute a lot of files.
1. Leave it as is and cope with the warning. As far as I see the generated code is correct. If we can deal with the visual annoyance, this is the easiest solution (and the code is correct).
1. Something in the direction of #7914.

**Comment by hjelmn** [comment]
Just to update. @bosilca, @jsquyres, and myself discussed this issue today. What came out of it is that the icc warning is clearly wrong. The C11 atomic functions are defined to be of the form:

```c
atomic_operation(volatile A* address, ...)
```

Where A is any of the atomic C types (```_Atomic```). What Intel appears to be doing is using gcc as a frontend to support C11 but emitting an incorrect warning when it sees the ```_Atomic``` qualifier. This is because gcc (after preprocessing) emits a series of operations using the builtin ```__atomic_``` functions. These functions all take ```volatile void *``` as their first argument. gcc does not warn about this conversion because it is part of their C11 implementation.

Intel needs to fix their icc bug. In the meantime we can either 1) do nothing (since this conversion is harmless anyway), 2) try to squash the warnings by hacking something up, or 3) disable C11 atomics with icc until Intel brings their C11 support in compliance with ISO/IEC 9899:2011 (I mean, seriously, C11 has already superseded by ISO/IEC 9899:2018 and we are still looking for icc C11 compliance). The later is the preferred approach but is nothing more than a bandaid until icc is compliant.

I have opened a forum post on Intel's developer's forum to see if we can get the issue fixed once and for all.

**Comment by hjelmn** [comment]
Worth giving a simple reproducer where icc emits a warning for correct C11 code:

```c
#include <stdatomic.h>
int main (int argc, char *argv[]) {
 _Atomic int foo = 0;
 atomic_exchange (&foo, 1);
 return 0;
}
```

This warns about converting from ```_Atomic int *``` to ```volatile void *``` even though C11 guarantees (using generics) that the function:

````c
atomic_exchange(volatile _Atomic int *, int);
```

Is defined and should be used here.

**Comment by bosilca** [comment]
We decided to move away from what was proposed in #7914, and instead to completely disable C11 atomics for _Atomic types in OMPI if we detect an Intel compiler. #7915 provides a first step toward this. As far as I can see it passes cleanly a debug compile with Intel (20200310) and gcc 9.2.

**Comment by jsquyres** [comment]
This was fixed long ago.
