### ISSUE TITLE
Issue with libtool / openmpi4 interaction

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#7331]
Hi We have a strange interaction issue with openmpi4 and libtool in Debian.

The libtool implementation of dlopen, etc. breaks with openmpi 4.0.2 ; it works fine with openmpi 3.1.3. The same version of libtool (2.4.6) in both cases.

Further Details are here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947148

What has changed in OpenMPI 4.0 that would be relevant ?

**Comment by jsquyres** [comment]
@amckinstry Can you post the `configure` line for how Open MPI was built in this case?

**Comment by jsquyres** [comment]
Can you also send the output of `ompi_info | grep dl`?  I ask because Open MPI v4.0.x doesn't use `libltdl` (by default) any more -- it just calls `dlopen()` directly.  Specifically: `libltdl` is only used as a fallback on platforms where `dlopen()` doesn't work.

From `configure` output of the v4.0.x branch on a RHEL 6 system:

```
1208 +++ Configuring MCA framework dl
1209 checking for no configure components in framework dl...
1210 checking for m4 configure components in framework dl... dlopen, libltdl
1211 
1212 --- MCA component dl:dlopen (m4 configuration macro, priority 80)
1213 checking for MCA component dl:dlopen compile mode... static
1214 checking dlfcn.h usability... yes
1215 checking dlfcn.h presence... yes
1216 checking for dlfcn.h... yes
1217 looking for library without search path
1218 checking for library containing dlopen... -ldl
1219 checking if libdl requires libnl v1 or v3...
1220 checking if MCA component dl:dlopen can compile... yes
1221 
1222 --- MCA component dl:libltdl (m4 configuration macro, priority 50)
1223 checking for MCA component dl:libltdl compile mode... static
1224 checking --with-libltdl value... simple ok (unspecified value)
1225 checking --with-libltdl-libdir value... simple ok (unspecified value)
1226 checking for libltdl dir... compiler default
1227 checking for libltdl library dir... linker default
1228 checking ltdl.h usability... yes
1229 checking ltdl.h presence... yes
1230 checking for ltdl.h... yes
1231 looking for library without search path
1232 checking for library containing lt_dlopen... -lltdl
1233 checking if libltdl requires libnl v1 or v3...
1234 checking for lt_dladvise_init... yes
1235 checking if MCA component dl:libltdl can compile... no
```

From `ompi_info` output -- the `ltdl` component isn't present:

```
$ ompi_info | grep dl
              dl support: yes
                  MCA dl: dlopen (MCA v2.1.0, API v1.0.0, Component v4.0.3)
                MCA odls: default (MCA v2.1.0, API v2.0.0, Component v4.0.3)
                MCA odls: pspawn (MCA v2.1.0, API v2.0.0, Component v4.0.3)
```

And nothing in my build is even linked against `libltdl`:

```sh
# ~/bogus is the installation prefix
$ ldd ~/bogus/lib/lib*so ~/bogus/lib/openmpi/mca*so | grep ltdl
```

**Comment by amckinstry** [comment]
The configure line is :
```
                --disable-silent-rules \
                --disable-wrapper-runpath \
                --with-package-string="Debian OpenMPI" \
                $(VERBS) $(FABRIC) $(PSM) $(PSM2) $(CMA) \
                $(ATOMICS) \
                $(JAVA) \
                $(STATIC_CONFIG_PARAMS) \
                $(BTL_TESTS) \
                --with-libevent=external \
                --with-pmix=$(LIBDIR)/pmix \
                --disable-silent-rules \
                --enable-mpi-cxx \
                --with-hwloc=/usr  \
                --with-libltdl \
                --with-devel-headers \
                --with-slurm \
                --with-sge \
                --without-tm \
                --sysconfdir=/etc/openmpi               \
                --libdir=\$${prefix}/lib/${DEB_HOST_MULTIARCH}/openmpi/lib      \
                --includedir=\$${prefix}/lib/${DEB_HOST_MULTIARCH}/openmpi/include
```

```
alastair@debian:~$ ompi_info | grep dl
  Configure command line: '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-silent-rules' '--disable-wrapper-runpath' '--with-package-string=Debian OpenMPI' '--with-verbs' '--with-libfabric' '--with-psm2' '--with-jdk-dir=/usr/lib/jvm/default-java' '--enable-mpi-java' '--enable-opal-btl-usnic-unit-tests' '--with-libevent=external' '--with-pmix=/usr/lib/x86_64-linux-gnu/pmix' '--disable-silent-rules' '--enable-mpi-cxx' '--with-hwloc=/usr' '--with-libltdl' '--with-devel-headers' '--with-slurm' '--with-sge' '--without-tm' '--sysconfdir=/etc/openmpi' '--libdir=${prefix}/lib/x86_64-linux-gnu/openmpi/lib' '--includedir=${prefix}/lib/x86_64-linux-gnu/openmpi/include'
              dl support: yes
                  MCA dl: dlopen (MCA v2.1.0, API v1.0.0, Component v4.0.2)
                MCA odls: pspawn (MCA v2.1.0, API v2.0.0, Component v4.0.2)
                MCA odls: default (MCA v2.1.0, API v2.0.0, Component v4.0.2)
```

`--with-ltdl` was set in 3.0.x and hasn't changed. I can do test builds without ltdl for 4.0.x

**Comment by amckinstry** [comment]
The problem occurs when openmpi is built _without_  libltdl, but the test case is linked with ltdl:
```
// mpicc -o test_lt_dlopen test_lt_dlopen.c -lltdl

#include <stdio.h>
#include <ltdl.h>
#include <mpi.h>

int main(int argc, char **argv)
{
        MPI_Init(&argc, &argv);
        lt_dlinit();
        lt_dlhandle handle = lt_dlopen ("./foo.so");
        const char * dl_error = lt_dlerror ();
        printf("%p %s\n", handle, dl_error ? dl_error : "(null)");
}
$ ./test_lt_dlopen
0x560bf50c96e0 can't close resident module

```

**Comment by jsquyres** [comment]
I'm not sure about that test: if you get a valid `handle` value back from `lt_dlopen()`, is the value from `lt_dlerror()` relevant?  I.e., is the `handle` value you're getting back from `lt_dlopen()` invalid?  All we can tell from this test is that it's not NULL.

**Comment by amckinstry** [comment]
I can find no docs for `lt_dlerror()` but `dlerror()` returns NULL with no previous error.

The version of the code with simple dlopen() works with no error, and the test case works (no error) with openmpi3.
So I think the test case is ok (its a cut down case as you can see from the URL at the top of the PR).

**Comment by jsquyres** [comment]
From https://www.gnu.org/software/libtool/manual/libtool.html:

```
Function: const char * lt_dlerror (void)
Return a human readable string describing the most recent error that occurred
from any of libltdl’s functions. Return NULL if no errors have occurred since
initialization or since it was last called.
```

It does not guarantee that the error returned is from the _last_ invocation of an `lt_FOO()` call.

More specifically, the documentation for `lt_dlopen()` on the same page says:

```
If lt_dlopen fails for any reason, it returns NULL.
```

Since `lt_dlopen()` didn't return NULL, it didn't fail, and therefore I think that the return from `lt_dlerror()` is returning something unrelated to `lt_dlopen()`.

**Comment by jsquyres** [comment]
Just to be 100% clear: I think it needs to be proved that this test is valid.  For example: what happens if you use the non-NULL handle that was returned from `lt_dlopen()`?  I'll bet you a beer it works fine -- i.e., there was no error.  Granted, you'll have to meet me in person to collect -- but if it ever happens, I'll pay up!  😄 

I see I also forgot to directly answer the question: why is `lt_dlerror()` returning a non-NULL value with Open MPI 4, when it didn't with Open MPI 3?

I think that might be an irrelevant question, for the reasons I cited above.  Specifically: I do not think that `lt_dlerror()` returning non-NULL means that the last-invoked `lt_FOO()` function had an error.  (that being said, I didn't check the libltdl source code -- someone should check this to be sure)

Regardless:
* Don't forget: the way you configured/built Open MPI, Open MPI 4 is not using libltdl itself.
* I'm guessing that one of the libraries Open MPI v4 is using (e.g., Libfabric? UCX?) is using libltdl.  They are doing some things during their bootstrapping that is causing the spurious value to be returned from `lt_dlerrror()`.
* But I am not sure that that matters, because it sounds like the user is using the non-NULL return value from `lt_dlerror()` to indicate that the previous `lt_FOO()` invocation experienced an error.  I'm not sure that this is correct.

**Comment by amckinstry** [comment]
Ok, tested it and I agree. I owe you a beer sometime :-) 

In the upstream bug report they had a larger test case, test_mpi_ocl.c related to the original problem. Unfortunately I get "success" from that test case, so the original bug has gone
into hiding.

Contacted the upstream reporter. I will close this issue in a week unless there are developments.

**Comment by gpaulsen** [comment]
@amckinstry & @jsquyres, thanks for looking into this.  I'm removing the v4.0.3 milestone for this issue.  If it persists we can add it to v4.0.4.

**Comment by jsquyres** [comment]
@amckinstry closed the upstream bug as NOTABUG.  Closing this issue to match.

Thanks for reporting the issue!  Glad we could track it down / resolve the issue.
