### ISSUE TITLE
Alternative Argobots installation path?

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#7578]
I am trying to give the Argobots integration (#6578) a shot but I am having trouble with the configuration process. I have installed Argobots through BOLT, say in `$BOLTROOT` in a subdirectory of `$HOME`). I configure the current Open MPI `master` using `--with-threads=argobots`. My first attempt failed because `abt.h` was not found. So I set `C_INCLUDE_PATH=$BOLTROOT/include` which gets me past that point but then fails with 
```
checking for ABT_init in -labt... no
```

What is the recommended way to announce an alternative installation path for Argobots to Open MPI? I don't see anything helpful coming from `configure --help`. Maybe I'm missing the obvious?

**Comment by jsquyres** [comment]
It would seem like there should be a `--with-argobots=DIR` kind of option, similar to other optional packages.

FYI @hppritcha @shintaro-iwasaki @npe9

**Comment by hppritcha** [comment]
That will come as a follow-on PR.
@devreal thanks for the interest in using argobots, but you may want to wait a while.  There will need to be a libevent that is argobots aware before you can actually use argobots with Open MPI.  The decision was made to go that direction rather than try to support libevent in open mpi by features in the argobot component in the original PR.
