### ISSUE TITLE
--map-by with PE=n not working

### ISSUE THREAD

**Issue by cniethammer** [open-mpi/ompi#7717]
I see this issue with Open MPI 4.0.3 installed with pure `./configure --prefix=... --enable-shared --enable-static` under Centos 8 running on a dual socket  AMD EPYC 7742 64-Core Processor or single CPU Intel I5-8350U system.

The logic of `--map-by`, `PE=n`, and `--bind-to` does not work as intended.

The `man mpirun` example for the usage of `--map-by`includes the following:
```
 % mpirun ... --map-by core:PE=2 --bind-to core
[...] ... binding child [...,0] to cpus 0003
[...] ... binding child [...,1] to cpus 000c
[...] ... binding child [...,2] to cpus 0030
[...] ... binding child [...,3] to cpus 00c0
```

However running this I get:
```
$ mpirun -np 2 --report-bindings --map-by core:PE=2 --bind-to core /bin/true
--------------------------------------------------------------------------
A request for multiple cpus-per-proc was given, but a directive
was also give to map to an object level that cannot support that
directive.

Please specify a mapping level that has more than one cpu, or
else let us define a default mapping that will allow multiple
cpus-per-proc.
--------------------------------------------------------------------------
```

**Comment by cniethammer** [comment]
A quick test with latest master (0a21a58f08196bc9e2717bbac33f10aedaca41bd) shows the same problem.

**Comment by rhc54** [comment]
I believe I explained this elsewhere, but I'll do so again here. That message is not an error - it is telling you precisely the correct thing. You cannot map-by core and bind the result to two cores as that is logically impossible to do. You are telling us to assign a process to a single core, and then bind it to two cores.

What you really want is to `map-by slot:pe=2` so that we will map processes sequentially within the socket, binding each proc to two cores. This can logically work as a "slot" has no defined number of cores in it.

**Comment by rhc54** [comment]
In other words, the example in the man page is wrong, not the code implementing the mapping.

**Comment by jsquyres** [comment]
@cniethammer I've opened PRs for v4.0.x and v4.1.x with new wording.

Did you want to have a look?  Check out #8099 (v4.0.x) and #8192 (a straight cherry-pick of #8099 for v4.1.x).

**Comment by cniethammer** [comment]
The man page fixes are fine. closing this
