### ISSUE TITLE
Configure support for Torque _and_ PBSPro

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#7903]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source tarball

### Please describe the system on which you are running

* Operating system/version: various Linux distributions
* Computer hardware: various
* Network type: various

-----------------------------

## Details of the problem

We are cross-compiling Open MPI to be used on various clusters with various schedulers. We are currently enabling Torque support using the `--with-tm` configuration flag pointing to a local Torque installation. This results in the corresponding MCA components (`mca_ras_tm` et al.) to link against `libtorque.so`. 
Now, we would like to add support for PBSPro (`libpbs.so`) in addition to Torque. It seems like this requires the same configuration flag, so the support for Torque/PBSPro might be mutually exclusive.

Is there any way to configure our Open MPI distribution to support both Torque **and** PBSPro?

**Comment by rhc54** [comment]
Torque and PBSPro are the same thing as far as OMPI is concerned. The two options exist solely because some installations of PBSPro don't install the separate Torque library, instead installing only the combined PBS one.

There isn't a way to specify both as that would cause symbol conflicts. If you are installing the combined PBS library on some machines, then your best bet would be to simply create a symlink from it to `libtorque.so` on those machines so that OMPI will pick it up.

**Comment by mkre** [comment]
Thanks @rhc54. That explains everything and creating a symlink from `libpbs.so` to `libtorque.so` works.
