### ISSUE TITLE
Questions - RMA performance

### ISSUE THREAD

**Issue by thomasgillis** [open-mpi/ompi#7966]
Hi OpenMPI community,
I have 2 questions related to the performance of the implementation of RMA windows.
I tried the book "Using advanced MPI" but couldn't really find a clear answer. I hope this is the best place to ask them, if not please let me know.

#### Q1 - does the allocated memory size of the window influences somehow the performance/memory allocated for the window?

If I need to get/put only discontinuous chunks of a local memory array (e.g. l know that only 20% of my local array will be involved in RMA calls), should I try to restrict to the minimum the memory associated to the window or can I easily overshoot and associate memory and afterward use datatypes to exchange only the minimum memory possible?

In other words, is the total memory associated to a window important to improve performances or is the actually used amount the main factor? 

#### Q2 - dynamic vs regular windows performances
Somehow related, I have a local memory which is split into many discontinuous blocks. For this example, let's imagine that I have 2 large blocks of memory but of the same size. I need to perform RMA accesses in turn: block 1 - block 2 - block1 - ... etc.
What is the best approach to improving performance? Should I attach/detach block 1, then block 2, then block 1, etc, given that I need to exchange the displacements all the time or should I allocate one fix memory window and copy/paste block 1 to it, then block 2, etc?

Thank you very much for your time and your help in understanding the OpenMPI implementation of RMAs!

**Comment by devreal** [comment]
> Q1 - does the allocated memory size of the window influences somehow the performance/memory allocated for the window?

The allocated memory size should not directly impact the performance, at least as far as I can see. That is, as long as your machine has sufficient memory to support the allocation without impacting the rest of your application of course. On many high performance networks, the memory backing the window will be pinned, i.e., /all/ the pages will have to be allocated and remain in memory regardless of whether you are actually touching them or not. The kernel will not be able to move these pages. (note that this may cause NUMA issues with multi-threading because the first touch always happens during window allocation)


> Q2 - dynamic vs regular windows performances
>
> Somehow related, I have a local memory which is split into many discontinuous blocks. For this example, let's imagine that I have 2 large blocks of memory but of the same size. I need to perform RMA accesses in turn: block 1 - block 2 - block1 - ... etc.
What is the best approach to improving performance? Should I attach/detach block 1, then block 2, then block 1, etc, given that I need to exchange the displacements all the time or should I allocate one fix memory window and copy/paste block 1 to it, then block 2, etc?


In my experience, dynamic windows almost always perform worse than regular windows because it is harder (or impossible) for the MPI implementation to use the network's RDMA capabilities, forcing it to fall back to some two-sided communication internally. If you only have two blocks to swap, you could also allocate them both as windows and then switch between them to avoid copying in and out of the window memory. I guess that depends on your use-case though.

**Comment by thomasgillis** [comment]
Awesome, thx @devreal for your answers!
