### ISSUE TITLE
What's the legit method to get PCI busid for each OMPI process?

### ISSUE THREAD

**Issue by jli111** [open-mpi/ompi#7980]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
OMPI 4.1
ucx 1.6.1
internal hwloc

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
../configure --prefix=build/install --with-cuda --with-ucx --enable-orterun-prefix-by-default

----------------------------

## Details of the problem
I am trying to get PCI bus information of each OMPI processes, based on their bound cpusets. For instance, if I map 4 OMPI ranks on 2 sockets, each socket may have multiple available pci devices, seems like the nearest pci device will be selected for each cpuset. I'd like to know are any 2 OMPI processes on same socket using the same pci dev or not, what is the bound pci bus id, etc.

I did some attempts, unfortunately, none of them worked. My first try is through `get_pci_busid_cpuset()`, but I had trouble with getting hwloc backend from opal_hwloc_topology. I checked that it's a global variable and filled already, in type of renamed hwloc_topology_t, while I've seen error message:

`
error: dereferencing pointer to incomplete type ‘struct opal_hwloc2_hwloc_topology’
struct hwloc_backend *backend =opal_hwloc_topology->get_pci_busid_cpuset_backend;
`

I don't understand why it's renamed to opal_hwloc2_hwloc_topology instead of hwloc_topology. Seems like this may be related to build/opal/mca/hwloc/hwloc2/hwloc/include/private/autogen/config.h :line 618, so I included build/opal/mca/hwloc/hwloc2/hwloc/include/hwloc/autogen/config.h instead. Didn't solve the issue.

Therefore, I moved to my second try, here is the corresponding code snippet of my program:
    
    bool first = true;  
    int i, num_cores, num_pus, num_pcis;
     
    char tmp[BUFSIZ];
    const int stmp = sizeof(tmp) - 1;
    hwloc_obj_t socket, core, c2, pcidev;

     str[0] = '\0';
     for (socket = hwloc_get_obj_by_type(opal_hwloc_topology,
                                         HWLOC_OBJ_SOCKET, 0);
          NULL != socket; socket = socket->next_cousin) {
         /* If this isn't the first socket, add a delimiter */
         if (!first) {
             strncat(str, "; ", OMPI_AFFINITY_STRING_MAX - strlen(str));
         }
         first = false;

         snprintf(tmp, stmp, "socket %d has ", socket->os_index);
         strncat(str, tmp, OMPI_AFFINITY_STRING_MAX - strlen(str));

         hwloc_topology_set_io_types_filter(opal_hwloc_topology, HWLOC_TYPE_FILTER_KEEP_ALL);         
         num_pcis = hwloc_get_nbobjs_inside_cpuset_by_type(opal_hwloc_topology, socket->cpuset, HWLOC_OBJ_PCI_DEVICE);
      ...
      }

While I received segfault:

`
[a07:27784:0:27784] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)
==== backtrace (tid:  27784) ====
 0 0x00000000000be880 opal_hwloc2_hwloc_bitmap_isset()  ???:0
 1 0x0000000000400d47 opal_hwloc2_hwloc_get_nbobjs_inside_cpuset_by_depth()  /home/jli111/Modules/ompi/opal/mca/hwloc/hwloc2/hwloc/include/hwloc/helper.h:193
 2 0x0000000000400ddc opal_hwloc2_hwloc_get_nbobjs_inside_cpuset_by_type()  /home/jli111/Modules/ompi/opal/mca/hwloc/hwloc2/hwloc/include/hwloc/helper.h:224
 3 0x0000000000400f45 getexist()  /home/jli111/research_git/work/persistent_coll/mpi_affinity.c:45
 4 0x000000000040136d main()  /home/jli111/research_git/work/persistent_coll/mpi_affinity.c:142
 5 0x00000000000223d5 __libc_start_main()  ???:0
 6 0x0000000000400b49 _start()  ???:0
`

Saw the same segfault even with different hwloc_obj_type_t, like HWLOC_OBJ_OS_DEVICE. Feel like this isn't the correct method to get the pci dev information. Now I am stuck, can anyone please give me some clews about this?

Any advice would be really appreciated!

**Comment by bgoglin** [comment]
I/O devices don't have a CPU set in hwloc, that's why hwloc_get_nbobjs_inside_cpuset_by_type() is documented as not working for these types. The way to check whether a PCI device (or OS device) is near a socket (not sure Socket is what you want since some PCI buses are attached to only part of a socket) is to compare socket->cpuset with hwloc_get_non_io_ancestor_obj(topology, pci_obj)->cpuset using hwloc_bitmap_intersects() or hwloc_bitmap_is_included().

That said, which PCI devices do you care about? There are many PCI devices in current machines, and all sockets have some, but most of them are uninteresting and/or virtual devices for processor configuration, etc. So you should likely rather look at "OS devices" (for instance OS devices of type "Network") that are inside PCI devices.
This discussion should likely rather be on the hwloc devel mailing list or as a open-mpi/hwloc github issues.

**Comment by jsquyres** [comment]
I had a similar reaction to @bgoglin -- an MPI process is not specifically bound to any given PCI device, nor does any one PCI device uniquely identify a specific MPI process (not even networking PCI devices).

What exactly are you trying to do?

**Comment by jli111** [comment]
I don't have too much understanding about this topic and wasn't sure where exactly should I post my question, apologize for any inconvenience. 

In my imagination, I would like to know how many MPI processes are sharing the same switch, even more detailed, how many transmissions are going through the same bus, which I guess can be identified by unique PCI bus ids, etc. What I am trying to do is more like getting full information from "PMIX_SWITCH_PEERS", but I also failed with either PMIx_Get() or  OPAL_MODEX_RECV_VALUE() routines. 

This's the origin of all these questions. Currently, I am able to get the affinity information of individual MPI process, but still not able to let it know who to share the network resources with.

**Comment by jsquyres** [comment]
> I don't have too much understanding about this topic and wasn't sure where exactly should I post my question, apologize for any inconvenience.

No need to apologize.  Questions lead to understanding.  😄 

> In my imagination, I would like to know how many MPI processes are sharing the same switch, even more detailed, how many transmissions are going through the same bus, which I guess can be identified by unique PCI bus ids, etc. What I am trying to do is more like getting full information from "PMIX_SWITCH_PEERS", but I also failed with either PMIx_Get() or OPAL_MODEX_RECV_VALUE() routines.

You still don't have some information, such as: which network interface(s) is(are) a given MPI process using?  Remember that an Open MPI process may be using multiple network interfaces simultaneously.  Those network interfaces may be on the same PCI buss or multiple different PCI busses.  They may go to the same network switch or multiple different network switches.  The data path through the network may be (largely) the same or may be entirely different (e.g., different, air-gapped networks).

**Comment by rhc54** [comment]
PMIX_SWITCH_PEERS will eventually tell you which ranks share a given switch, but support for that attribute hasn't been implemented yet and will ultimately depend on the fabric vendor providing the necessary PMIx integration to support it.

**Comment by jli111** [comment]
> You still don't have some information, such as: which network interface(s) is(are) a given MPI process using? Remember that an Open MPI process may be using multiple network interfaces simultaneously. Those network interfaces may be on the same PCI buss or multiple different PCI busses. They may go to the same network switch or multiple different network switches. The data path through the network may be (largely) the same or may be entirely different (e.g., different, air-gapped networks).

Ah, now I see this is more complex than nicely fetching data from one API as I thought. I assumed there is a rule to always select the nearest network device to one CPU set that an MPI process bound to,  and it's possible to know which device is the closest one to that CPU set, so the usage of network devices is kinda unchanged in the rest of communication. While I didn't realize that there is a chance of using multiple network resources at the same time, I think this explains your first answer "an MPI process is not specifically bound to any given PCI device".

> PMIX_SWITCH_PEERS will eventually tell you which ranks share a given switch, but support for that attribute hasn't been implemented yet and will ultimately depend on the fabric vendor providing the necessary PMIx integration to support it.

May I ask a stupid question: regarding to @jsquyres 's above reply, 

> They may go to the same network switch or multiple different network switches

In this case, let's assume this feature exists now, will the list of PMIX_SWITCH_PEERS be fixed? Or updated every time different switches are involved in the communication?

**Comment by rhc54** [comment]
The easiest way to think about PMIX_SWITCH_PEERS is to start from the switch and trace the wire connected to each port back to the node to which it attaches. If you do that for every port, then the peer processes on the resulting collection of nodes are what you get in PMIX_SWITCH_PEERS.

Thus, the list in PMIX_SWITCH_PEERS is fixed since it only reflects the wiring (which shouldn't be changing during an execution) and the placement of processes on nodes. It has nothing to do with your communication pattern.

If you want to create a hierarchical collective, you would start by collecting the contributions from all procs on a node, aggregating them to a "node leader". Each node leader would then look at its list of PMIX_SWITCH_PEERS to find the lowest ranked participant in the collective - this would become the "switch leader", and you would have it aggregate the payload from every node leader in that list of PMIX_SWITCH_PEERS.

If your nodes have multiple NICs, or NICs with multiple ports that are connected to different switches, then you will have multiple lists of PMIX_SWITCH_PEERS. You will then need some common algorithm by which the various node leaders can determine which switch to aggregate across so you can guarantee they all make the same decision.

**Comment by jli111** [comment]
Thanks so much for your patience and answers, my questions are all clear now!
