### ISSUE TITLE
OFI BTL and FI_DELIVERY_COMPLETE

### ISSUE THREAD

**Issue by rajachan** [open-mpi/ompi#7982]
Starting an issue so we can discuss the FI_DELIVERY_COMPLETE requirements of the OFI BTL and the state of the world with the various libfabric providers that claim support for it today. 

No currently existing hardware can provide the FI_DELIVERY_COMPLETE semantic.  The semantic is that when local completion has occurred at the initiator, “a completion guarantees that the result of the operation is available”, which is impossible to guarantee at the remote application layer when you’re sitting on the PCIe bus.  However, the guarantee that hardware supporting FI_DELIVERY_COMPLETE actually provides could be read more as “the remote NIC has initiated the transaction to target memory”, which is a looser semantic but also exactly the semantic needed by upper layer protocols which require FI_DELIVER_COMPLETE.  

A number of libfabric providers using bounce buffers for communication operations, especially RDMA operations, provide a FI_DELIVERY_COMPLETE semantic significantly looser than that promised by hardware.  This list apparently includes RxD, EFA, and likely others.  In this case, we’re seeing that the erroneous FI_DELIVERY_COMPLETE support is causing failures in Open MPI.

Creating this issue to use as a reference during the dev meeting on 8/4. Will update with more information and references.

**Comment by shefty** [comment]
FI_DELIVERY_COMPLETE typically requires a software based ACK.  FI_TRANSMIT_COMPLETE allows for a hardware ACK.  However, that only guarantees that the message has been received and processed by the target NIC.

The latter can provide some ordering guarantees when subsequent transfers flow through the same endpoint on the same NIC.  However, if transfers can use different NICs or endpoints, you need delivery complete semantics to guarantee ordering.

I'm not even sure RxM meets FI_DELIVERY_COMPLETE requirements for RMA operations, since those could map directly over hardware based RDMA.

**Comment by rwespetal** [comment]
Thanks for the followup, Sean. Does RxD provide a correct implementation of FI_DELIVERY_COMPLETE for RMA operations? From our quick review it looks like the protocol to handle re-transmissions will provide a software ACK.

**Comment by shefty** [comment]
Yes, I believe rxd is compliant.

**Comment by bwbarrett** [comment]
Change merged in both 4.1 and master.  Closing.
