### ISSUE TITLE
Make F90 MPI_IN_PLACE, MPI_ARGVS_NULL, and MPI_STATUSES_IGNORE be uniqe types

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#8]
Per an e-mail exchange with Michael Kluskens, there appears to be benefit from making several of the MPI constants in F90 be unique types so that we can have unique interfaces that match just that senteniel.  Specifically:
- We can disallow using those constants where they are not allowed
- We can prevent accidental bad arguments to functions (E.g., MPI_ARGVS_NULL is currently a double precision -- so someone could accidentally pass a double precision into MPI_COMM_SPAWN_MULTIPLE.  Unlikely, but still possible -- a unique type for MPI_ARGVS_NULL would prevent this possibility)

See http://www.open-mpi.org/community/lists/users/2006/11/2115.php.

**Comment by jsquyres** [comment]
Turns out that you're not allowed to do that (by the MPI spec), because if you do, then 3rd party PMPI-using libraries won't know the function/subroutine signatures to override.  Hence, `MPI_IN_PLACE`, `MPI_ARGVS_NULL`, and `MPI_STATUSES_IGNORE` (sadly) need to be the same types as their peers, and therefore we must check for those sentinel values.
