### ISSUE TITLE
Memory corruption in PML OB1 iprobe

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#800]
Coverity CID 710549  detected memory corruption in `mca_pml_ob1_iprobe`.  At `mca_pml_ob1_iprobe.c:39`:

```c
    MCA_PML_OB1_RECV_REQUEST_INIT(&recvreq, NULL, 0, &ompi_mpi_char.dt, src, tag, comm, true);
```

but then further down in the same function, we call

```c
    MCA_PML_BASE_RECV_REQUEST_FINI( &recvreq.req_recv );
```

which calls `OBJ_RELEASE()` on the request datatype, which was defined to be `&ompi_mpi_char.dt`.

It looks like the same thing happens in v1.10 and v2.x.

@hjelmn @bosilca Can you suggest a fix?

**Comment by bosilca** [comment]
The datatype is retained in MCA_PML_BASE_RECV_REQUEST_INIT in pml_base_recvreq.h:55 without taking in account if the datatype is predefined or not (by design to remove a branch in the critical path). So as long as we increase the refcount as many times as we decrease it there should be no problem.

Do you have an example that show this as being an issue?

**Comment by jsquyres** [comment]
No, it was just flagged in Coverity.  If it's not a problem because we artificially OBJ_REQUIRE the type, then all is cool -- this is a false positive by Coverity.
