### ISSUE TITLE
How to improve orted wireup and connection

### ISSUE THREAD

**Issue by fm-dewal** [open-mpi/ompi#8282]
## Background information
During a performance analysis, it is observed that orted processes take ~30 seconds from time of creation to establishing connectivity with the mpirun process.

Setup: Cluster of 1024 docker hosts with OpenMPI installed, launched on 13 physical servers.

### What version of Open MPI are you using? Describe how Open MPI was installed 
I have Open MPI version 4.0.5 installed in my docker images.
Installation done using the openmpi-4-0-5.tar.gz tarball.
Release date: Aug 26, 2020

### Please describe the system on which you are running
* Operating system/version:
Native: centos:7 with 3.10.0-957.el7.x86_64 kernel version
Docker: 19.03.9, build 9d988398e7
* Computer hardware: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70 Ghz
* Network type: Docker Swarm - User-defined Overlay
-----------------------------

## Details of the problem

We are using the following MCA parameters to improve the launch time and optimize connection handling
```
mpirun -n 131072
--hostfile ./hostfile
--mca fwd_mpirun_port true
--mca mpi_yield_when_idle 1
--mca hwloc_base_binding_policy none
--mca mpi_oversubscribe true
--mca btl tcp,self,vader
--mca btl_tcp_if_include x.x.0.0/16
--mca oob_tcp_if_include x.x.0.0/16
--mca opal_net_private_ipv4 x.x.0.0/16
--mca orte_tmpdir_base /openmpi/tmp
--mca opal_event_include epoll
--mca event_libevent2022_event_include epoll
--mca opal_set_max_sys_limits 1
--mca oob_tcp_listen_mode listen_thread
--mca pmix_base_async_modex true
--mca orte_keep_fqdn_hostnames true
--mca orte_hostname_cutoff 2000
--mca orte_enable_recovery true
/opt/exec/hello_c.o
````

Please help identify any parameters/ environment variables that could be explored further to improve the performance for orted launch and connectivity with mpirun process.

I would be happy to provide any further information as required.

Thank you

**Comment by jsquyres** [comment]
Also see the discussion on #8278.

**Comment by rhc54** [comment]
Few thoughts here:

* fwd_mpirun_port really isn't going to do any good here as you are using ssh to start the various daemons. Best to take that off
* orte_enable_recovery does nothing at this time
* should add pmix_base_collect_data false

You may be running up against the limits of what you can do with Docker - you are starting a fair number of containers on each node, and there is overhead due to the virtual network. I'm playing with a new routing module specifically for this use-case as it is becoming a little more common in the "cloud" environment that I think will improve the speed, but it isn't ready yet for testing.

If you were looking for "instant on" behavior - it hasn't yet been enabled in OMPI. Should be coming at some point in the OMPI v5 series.

**Comment by jsquyres** [comment]
Also take note of how much oversubscription you're doing: you mention 1024 docker hosts on 13 physical servers.  That's 78.7 dockers per host (this issue doesn't specify how many MPI procs you're starting in each docker instance), and unless you have giant machines, you must be oversubscribing.  With all the virtual networking and context switching due to oversubscription, 30 seconds might not be that bad, actually...

**Comment by fm-dewal** [comment]
Hi Raplh,
Could you provide some pointers on how to optimize launching of daemons using the fwd_mpirun_port?
Is there an RPC which could experience enchanced performance when using this functionality?
https://www.open-mpi.org/faq/?category=all#reducing-startup-time

Thank you for the suggestions.

**Comment by fm-dewal** [comment]
Hi Jeff,
Yes, acknowledged. There is a significant amount of over-subscription going on. 
Good to know.

**Comment by rhc54** [comment]
> how to optimize launching of daemons using the fwd_mpirun_port

It is only of help when launching in managed environments such as Slurm or ALPS. When launching via ssh/rsh, we use a tree-based spawning pattern and the messages all flow along the tree, so no benefit from forwarding the mpirun port.

**Comment by jsquyres** [comment]
If you care, I wrote a pair of blog articles about this several years ago:

* https://blogs.cisco.com/performance/tree-based-launch-in-open-mpi
* https://blogs.cisco.com/performance/tree-based-launch-in-open-mpi-part-2

**Comment by rhc54** [comment]
Please reopen if that didn't answer your questions.
