### ISSUE TITLE
libtreematch.la is getting put in wrapper "libs_static"

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#8724]
Working with head of OMPI master branch as of Fri afternoon (hash 8f19f0f01a1837b2a048b94bec9b89541ea42617) on CentOS7. This is with a fresh clone of the repo. I am able to build the branch, but cannot compile any application programs due to the following:
```
$ make add_host
mpicc -g --openmpi:linkall    add_host.c   -o add_host
/opt/hpc/build/ompi/3rd-party/treematch/libtreematch.la: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [add_host] Error 1
```
Any ideas out there would be appreciated.

**Comment by jsquyres** [comment]
I can confirm that this is happening, but only when you try to link statically with the wrapper compilers.  Specifically, this line is ending up in the `mpicc-wrapper-data.txt` file for my build:

```
libs_static=-lmpi -lopen-pal -ldl /home/jsquyres/git/o4/build/3rd-party/treematch/libtreematch.la -lutil -lm -lrt
```

There are two things wrong here:

1. `libtreematch.la` is being added, instead of the actual back-end libtree library (either .so or .a).
2. The path used for `libtreematch.la` is in my build tree, not in the install tree.

**Comment by bosilca** [comment]
Why is this treematch linked independently instead of being part of the topo object (either statically or dynamically linked) ?

**Comment by jsquyres** [comment]
@bosilca I do not know; I didn't have the time to investigate how this is happening -- I just confirmed that it *is* happening.

**Comment by bwbarrett** [comment]
wow, this is old voodoo.  And more broken static component issues :).  I can replicate this on my Mac.  It's an issue whenever linking static (or specifying openmpi:linkall).

Core issue is that we never expected a component's configure.m4 to set `<framework>_<component>_LIBS` to include a .la file.  If a component does not set `<framework>_<component>_WRAPPER_EXTRA_LIBS` and is building as part of the base library, then `<framework>_<component>_LIBS` is copied into `<framework>_<component>_WRAPPER_EXTRA_LIBS`.  This is so that things like `-lfabric` are including in the link line if linking static libraries.  Well, we sucked in the `treematch.la` because that's what LIBS was set to (because it's internal).

I think the simple solution is to have `OPAL_FLAGS_APPEND_UNIQ` filter out `.la` files in LIBS.  The only reason that they'd be there is internal libraries like this.  Unfortunately, I'm out of time tonight.  I'll work on it in the morning and post a patch.

**Comment by bwbarrett** [comment]
While trying to figure this code out, I noticed an error in `MCA_PROCESS_COMPONENT`.  There is an asymmetry in how we deal with the LDFLAGS and LIBS if the component name is known at autogen time vs. configure time (which is esoteric drop in configure-based modules stuff no one does).  The code starting on line 823 could be written significantly better, but at least needs to check if the wrapper flag is set in both cases.  Leaving this as a note to myself to fix tomorrow as well.
