### ISSUE TITLE
v5.0.x/master: Nightly tarball builds fail due to missing file

### ISSUE THREAD

**Issue by awlauria** [open-mpi/ompi#8786]
It seems that that ompi nightly tarball is missing the following file:

```
atomic_gcc_builtin.h
```

That should be located in:
`3rd-party/openpmix/src/atomics/sys`

This was reproduced with the most recent master and v5.0.x tarballs. Not sure if this is the right spot for this issue, it could be an issue in the openpmix repo. 

In any case this is causing some mtt build failures with xl compilers, since it needs that file.

**Comment by bwbarrett** [comment]
Why is this an OMPI issues, when the problem is in openpmix?

**Comment by jjhursey** [comment]
It looks like that file is present in openpmix:
 * master: https://github.com/openpmix/openpmix/tree/master/src/atomics/sys
 * v4.0: https://github.com/openpmix/openpmix/tree/v4.0/src/atomics/sys

So maybe this is something in how OMPI is generating their tarball?

**Comment by bwbarrett** [comment]
@jjhursey I moved that file recently as part of the great atomics cleanup of 2021...  Austin is saying that the file doesn't end up in a dist tarball, which is probably just me being stupid.  It's on my todo list to look into this week.

My maybe too snarky comment above, though, was that we need to get better at filling issues in PMIx/PRRTE (as well as OMPI, and hopefully cross-referencing), so that the owners of the problem see them.

**Comment by awlauria** [comment]
Fixed by https://github.com/open-mpi/ompi/pull/8812. Closing.
