### ISSUE TITLE
mpirun prepends its libraries path to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#8801]
I have been surprised to see that Open MPI master prepends the path to the installation's libraries to `LD_LIBRARY_PATH`. This has bitten me multiple times when trying to run with different configuration of Open MPI, each installed in a different location. This is a change in behavior after 4.1 where it was possible to prepend the path to the OMPI libraries to use and run the application again with the different configuration without problem. On current master, `LD_LIBRARY_PATH` seems to be modified on all but the head node, which has lead to plenty of confusion and frustration.

To show what's happening:

```
$ mpirun -n 2 bash ./test_env_vars.sh 
0: /opt/hlrs/non-spack/compiler/gcc/10.2.0/lib64:/opt/hlrs/non-spack/development/binutils/2.35/lib
1: /path/to/current/mpirun/base/dir/lib:/opt/hlrs/non-spack/compiler/gcc/10.2.0/lib64:/opt/hlrs/non-spack/development/binutils/2.35/lib
```
`test_env_vars.sh` simply does `echo ${OMPI_COMM_WORLD_RANK}:$LD_LIBRARY_PATH`. Note that the variable is not the same on each node.

Is this change in behavior wanted and documented?

**Comment by bosilca** [comment]
A while back one needed to add `mpirun-prefix-by-default` to get this behavior. Now that the option is on PRRTE and it is enabled by default, you don't have to do anything to get this behavior. It basically mirror the path to your mpirun with the backend libraries (assuming shared file system), which is the expected behavior for most people. Instead of changing the `LD_LIBRARY_PATH` on the shell resource file for the compute nodes, you can simply change it in the shell running the mpirun, a much more convenient solution.

**Comment by jsquyres** [comment]
> A while back one needed to add `mpirun-prefix-by-default` to get this behavior. 

To clarify: in the past, you could get this behavior via:

1. Specify `--enable-mpirun-prefix-by-default` to Open MPI's `configure`
2. Specify `--prefix` option to `mpirun`
3. Invoke `mpirun` via an absolute path name (e.g., `/path/to/mpirun`)

There may have been an env variable option, too; I don't remember offhand.

**Comment by devreal** [comment]
There are two issues here then:

1) It's consistent between nodes (the first node has the original path), which leads to confusing behavior if the `LD_LIBRARY_PATH` on the head node is not the library path `mpirun` will append.
2) I'm not sure I understand your last sentence correctly but I think this is what I am doing: setting `LD_LIBRARY_PATH` once on the node that runs `mpirun` and not in any shell file that runs on the compute nodes. Up to 4.1, it appears that `mpirun` simply mirrors the `LD_LIBRARY_PATH` on the head node to the compute nodes, which IMO is the correct behavior.

**Comment by bwbarrett** [comment]
And further clarification, you can get the old behavior by specifying `--disable-mpirun-prefix-by-default`.  If you build PRRTE independently of Open MPI, you'll need a different option.

**Comment by devreal** [comment]
Looking at the configure documentation:
```
  --enable-prte-prefix-by-default
                          Make "mpirun ..." behave exactly the same as "mpirun
                          --prefix \$prefix", where \$prefix is the value
                          given to --prefix in configure (default:enabled)
```
Not very helpful. `mpirun --help` says:
```
   --prefix <arg0>                   Prefix to be used to look for RTE executables
```

It's absolutely not clear that this flag alters the `LD_LIBRARY_PATH` :/

**Comment by rhc54** [comment]
There are probably a couple of things combining here. First, we have always prepended the `LD_LIBRARY_PATH` when "prefix-by-default" is enabled - I'm not sure how else one would implement that feature. Just prepending the prefix to the binary isn't sufficient as we still have to locate the dynamic plugins. I guess we are now doing this by default, but I'm open to changing that if people prefer we don't. The consistency issue is a bug that needs to be fixed.

Second, there is a possibly unnecessary cross-over between PRRTE and OMPI here. Now that the MPI apps no longer link against the RTE, it is possible for us to set a prefix to ensure PRRTE finds the appropriate bins/libs while not impacting the choice of OMPI libs. For example, we could set the PRRTE prefix during install to be `<OMPI-PREFIX>/prrte`, thereby allowing someone to point `LD_LIBRARY_PATH` at a different OMPI installation while still using this PRRTE install.

Of course, this is only an issue when using the internal PRRTE. Otherwise, it's not a problem.

**Comment by awlauria** [comment]
Will this require a pmix pointer update for v5.0.x?

**Comment by rhc54** [comment]
When PRRTE is updated, yes
