### ISSUE TITLE
Rename persistent collectives from MPIX_* to MPI_*

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi#9061]
@kawashima-fj @jsquyres 

MPI 4.0 has been released!

That means (among so many other things) that non blocking collectives are now part of the standard, and have hence to be
moved from `mpiext` to `mpi` and renamed from `MPIX_*` to `MPI_*`.

Unless someone has already started this effort, this is something I can start by the middle of this week.

**Comment by kawashima-fj** [comment]
@ggouaillardet I've been thinking about that since last week but I don't have enough time to work now. If you have time, I leave it for you.

A question to the community:
Persistent collectives are included in Open MPI 4.0.x and 4.1.x with the `MPIX_` prefix. Should we keep them for compatibility?

p.s. I guess you mean persistent collectives, not non-blocking collectives. I changed the issue title.

**Comment by ggouaillardet** [comment]
@kawashima-fj Thanks for correcting the wording.

OK, I will do that sometimes this week

I initially did not plan to backport the changes to the v4 series, and since v5 will break ABI (at least this is what I understand), I would not worry about compatibility.
This is not a strong opinion though.

**Comment by kawashima-fj** [comment]
@ggouaillardet I don't mean backporting `MPI_*` to v4 series. I wondered we should keep `MPIX_*` in `master` (and v5 series) with `__attribute__((deprecated))` or not. I don't have an opinion for it. Just a question.

**Comment by jsquyres** [comment]
First: woo hoo!!  Thanks for taking this up, @ggouaillardet 

I wouldn't worry about keeping the old MPIX symbols.  We have not done that in the past.

@kawashima-fj That being said, do you have any customers who would prefer to have the MPIX symbols available for a release or two in order to help transition to the new symbol names?

**Comment by kawashima-fj** [comment]
@jsquyres No, I don't have (know) any specific customers who prefer to keep `MPIX`. So let's drop `MPIX` unless other people complain.

**Comment by ggouaillardet** [comment]
I might have found one: our very own ibm test suite (!)

that being said, we can do something cheap like `#include MPIX_Bcast_init MPI_Bcast_init` in `mpi-ext.h`and/or implementing wrappers `int MPIX_Bcast_init(...) { return MPI_Bcast_init(...);}` that will be trivial to remove when we decide to stop testing persistent collective on the v4 series.

**Comment by kawashima-fj** [comment]
Fixed by #9065 (master) and #9456 (v5.0.x).
