### ISSUE TITLE
Inconsistent setting of mpi_assert_allow_overtaking leads to deadlock

### ISSUE THREAD

**Issue by devreal** [open-mpi/ompi#9846]
This is a dedicated issue for a problem reported in https://github.com/open-mpi/ompi/pull/9843. The fix there likely isn't what we want so I create a separate issue.

Setting the `mpi_assert_allow_overtaking` info key can happen in a way that creates inconsistencies between MPI processes. Processes with different `mpi_assert_allow_overtaking` info values exchanging messages will cause errors or deadlock. 

Here is a minimal reproducer for the problem:

```C
#include <unistd.h>
#include <mpi.h>

int main(int argc, char **argv)
{
  int rank, value;
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  MPI_Comm comm;

  MPI_Comm_dup(MPI_COMM_WORLD, &comm);

  MPI_Info no_order;
  MPI_Info_create(&no_order);
  MPI_Info_set(no_order, "mpi_assert_allow_overtaking", "true");

  if (rank == 0) {
    MPI_Send(&value, 1, MPI_INT, 1, 100, comm);
    MPI_Comm_set_info(comm, no_order);
    MPI_Send(&value, 1, MPI_INT, 1, 100, comm);
  } else {
    sleep(5); // increase the window of opportunity
    MPI_Recv(&value, 1, MPI_INT, 0, 100, comm, MPI_STATUS_IGNORE);
    MPI_Comm_set_info(comm, no_order);
    MPI_Recv(&value, 1, MPI_INT, 0, 100, comm, MPI_STATUS_IGNORE);
  }

  MPI_Info_free(&no_order);
  MPI_Finalize();
  return 0;
}
```

Process 1 will hang in the second receive because the second message will be encountered before the info key is set (thanks to eager sending). Based on a discussion with @bosilca, my understanding is that the second message is put into a queue from which it is not taken after the info key is set (I'm on very thin ice when it comes to ob1, sorry). Everything runs fine without the info key.

@bosilca and I came up with three possible fixes:

1) The one proposed in https://github.com/open-mpi/ompi/pull/9843: guard ensuing communication before/after setting the info key with barriers. This is costly and there is a chance that it is breaking existing codes (MPI says that `MPI_Comm_set_info` is collective but no implementation is synchronizing, according to @bwbarrett). Plus, there might still be an opportunity to break the second barrier if one of its messages encounters an inconsistency between sender and receiver (unless we also exclude collective internal p2p from using allow-overtake in ob1, as proposed in #9843). 
2) Disallow dynamically setting `mpi_assert_allow_overtaking` in `MPI_Comm_set_info` and only support it in communicator creation/duplication. That will be safe and an easy fix, but there may be applications that rely on the support for dynamic setting. Info keys can be ignored at any time.
3) Fix ob1 to properly manage the case where the info value is set dynamically (draining the queue of messages that could not yet be matched, from what I understand). I don't know enough about ob1 to know whether this is viable.

**Comment by bwbarrett** [comment]
@hjelmn may have opinions as well, since he wrote most of this.

I think excluding collectives tags is probably a good idea regardless; I'm not convinced that all our collective algorithms will be ok with overtaking implementations.  That's a lot of code to audit.  Once we're excluding the collective tags, that at least makes the problem in (1) easier.

(3) sounds like the right solution, but really hard.  There's no way I can commit to working on that.

**Comment by bosilca** [comment]
I have updated the PR with (3). However, this can only be implemented in one direction: dynamically enabling overtake. I left a comment in pml_ob1.c about this.

Regarding the collectives I'm mostly confident that most, if not all, our algorithms should be OK. The reason is that the only impact of overtake is in the order of messages between the same peers, and the collective algorithms do not pipeline message to the same peer one after another, but cycle among all the peers.

In fact, I think we can reshuffle the matching in OB1 to only enforce ordering on user messages (aka tag >= 0), saving an atomic operation for all internal communications (that are not going directly over AM).
